#! /bin/csh -f
#
#  calling this script will create html-ized man pages 
#  I've not gotten man2html to work quite, there appear
#  to be at least 2 different versions available,
#  one from http://www.oac.uci.edu/indiv/ehood/man2html.html
#  the other one comes with the linux man package (author unknown)
#
#  I personally prefer gman (a Gnome utility), though tkman and xman
#  are also not bad


cd $NEMO/man
if (! -e html) mkdir html

#				this method uses rman

foreach d (1 3 5 6 8 l)
 set dir=man$d
 foreach file ($dir/*.?)
   set base=$file:t
   rman -f HTML $file  >  html/$base.html
 end
end

make_man.csh > html/index.html
make_whatis.csh > html/whatis.html

