#! /bin/csh -f
#
#   Convert a man page to a pdf
#
#   (see also an earlier script 'manlaser'
#
# to get txt files of your man page (without all the ^H^_ stuff)
#  groff -t -e -mandoc -Tascii manpage.1 | col -bx > manpage.txt
# to get high quality ps files:
#  groff -t -e -mandoc -Tps manpage.1 > manpage.ps
# or try
#  groff -man -Tps manpage.1 > manpage.ps
#
# See also:
#     mandoc mandoc -T pdf -man manpage.1  > manpage.1.pdf
#          but doesn't look at good.
#     pandoc - doesn't seem to read man files, it can create them
#
# groff: fatal error: cannot load 'DESC' description file for device 'pdf'
#    on ubuntu, both groff and groff-base need to be installed
#    see 

set o=ps      # PostScript, good backup if pdf is not working
set o=pdf     # PDF

foreach file ($*)
  if (-e $file) then
    groff -man -T$o $file > $file.$o
    echo xdg-open $file.$o
  endif
end

# man -t ascii | ps2pdf - > ascii.pdf
