.TH ADS 5NEMO "15 January 2023"

.SH "NAME"
ads \- bibcode for codes with papers on ADS using a @ads markup

.SH "SYNOPSIS"
grep ^@ads $NEMO/man/man1/*.1

.SH "DESCRIPTION"
\fICodes with Papers:\fP
In 2021 we have started to use the \fB@ads\fP doxygen-like marker
in man pages and source code to link a code with a paper using their 
\fBADS bibcode\fP. There are plenty
of examples in NEMO of codes we keep, that have a corresponding paper 
where code may not be easily available anymore. The first one we did is
in \fICGS(1NEMO)\fP:

.nf
    @ads 2005A&A...433...57T
.fi

This reference should then be resolvable via the ADS on:

.nf
    https://ui.adsabs.harvard.edu/abs/2005A&A...433...57T
.fi


The idea is that (apart from using \fIgrep(1)\fP) we will have tools that extract
these doxygen-like tags and summarize them. Currently the man page entries will
have to manually followed up in the usual "FILES" section of the man page to find the
source code from the man page. In  the 
case of CGS, this would be in \fB$NEMO/usr/trenti/CGS/\fP

.PP

Related to this is how to link software by its \fIname\fP, as suggested in the AASTeX guide for 
publishing in AAS journals:

.nf
     \\software{Astropy \\citep{astropy:2013, astropy:218}}
.fi

The \fIname\fP of a code is not always uniquely determined, but a growing list is available on 
https://github.com/teuben/ascl-tools/blob/master/asclKeywords.txt

.PP

An alternative could be a \fB@doi\fB, which for the CGS would be:   10.1051/0004-6361:20041705

.PP
During a manual update, the compiled version of all codes with papers will be on
https://teuben.github.io/nemo/man_html/bibcode.html

.SH "OTHERS"
There are at least two other code and paper linking mechanisms that are in practice:
.PP
In \fBamuse\fP each contributed code as the metadata containing a reference to the
original author.
.PP
In \fPastropy\fP the \fBastropy.__citation__\fP returns a string containing the \fIbibtex\fP
entry


.SH "SEE ALSO"
CGS(1NEMO), runbulgerot(1NEMO)
.nf

https://teuben.github.io/nemo/man_html/bibcode.html - generated by NEMO 

ASCL:  https://ascl.net
Papers with Code:   https://paperswithcode.com/  - see also 
    https://blog.arxiv.org/2020/12/10/instant-access-to-code-for-any-arxiv-paper/
.fi

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.5i +5.5i
10-apr-2021	written		PJT
15-jan-2023	added URL	PJT
.fi
