.TH AUTHORS 5NEMO "9 November 2005"
.SH NAME
authors \- authorship of NEMO
.SH DESCRIPTION
The core of NEMO was originally written in 
1986 by Joshua Barnes (JEB),
Piet Hut (PH) and Peter Teuben (PJT), Throughout NEMO
you can now find many contributions by 
a large list of authors, and this manual page attempts
to place these people in their (historic) context. Sometimes full
names are used, otherwise these abbreviations should help finding
out the main author. This list also attempts to summarize
their contributions, which may not always be so visible
.SH AUTHORS
.nf
.ta +1i
AdM	Patrick Frisch (Gottingen, 1991)
AMK 	Amanda Keller (UMD, Spring 1997)
DC      Dustin Chertoff (UMD, Spring 2002)
DP      Daniel Pfenniger
JCL  	Jean-Charles Lambert (Marseille, 1997-) - io_nemo, glnemo
JEB	Joshua Barnes (Hawai) - treecode1, ZENO
JJM	James Marshall (UMD, June 1997)
JM	Jun Makino (Tokyo) 
JCM	Chris Mihos (Michigan, USA)
JN/JAN	Jeffrey Newman  (UMD, summer 1992?)
JAS	Jerry Sellwood (Rutgers) - galaxy
KGB	Kor Begeman (Groningen; some GIPSY related code)
LA	Luis Aguilar (Ensenada, Mexico)
LH	Lyman Hurd (IAS, 1986-87)
LXH	Lars Hernquist (Harvard) - treecode, scfm
MB	Marc Balcells (U. Groningen, Netherlands - 1990)
MHS	Matthias Steinmetz (MPI, Garching, Germany)
MT  	Michele Trenti (Pisa,STSCI) - CGS 
MXW     Mark Wolfe (UMD, Spring 2003)
MW	Martin Weinberg 
NAS	N.A. Amarnath 
NEBK	Neil Killeen (ATNF - miriad)
NSK	Neal Katz
NVS	Nick Strobel (U. of Washington, USA)
PAF/ADM	Patrick A. Frisch	Germany
PAS	Christian Theis  (Kiel, Germany)
PW	Peter Wisnovski (Princeton, summer 1987)
PH	Piet Hut (IAS)
PJT	Peter Teuben (UMD)
PS	Panajotis Skordis (MIT, 1986) - filestruct
RAG	Robert A. Gruendl (UMD, 1990s)
RJS	Bob Sault (ATNF - miriad)
RPO	Rob Olling (USNO) - epicycles in potcode
SJA	Sverre Aarseth (IOA, Cambridge) - nbodyX
SMF	Scott Foster (UMD, 1992)
TRQ	Tom Quinn (U.Washington)
VS	Vikas Shah (UMD, 2000)
WD	Walter Dehnen (Leicester) - gyrfalcON + many tools
WLS	William L. Sebok (UMD) - ds
.fi
.SH CAVEATS
No doubt some have been forgotten....
.SH "SEE ALSO"
nemo(1NEMO)
.SH AUTHOR
Peter Teuben
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
27-jun-97	Created  	PJT
6-jun-01	few more updates	PJT
6-jul-01	moved more some authors over from files.8	PJT
.fi
