.TH AUTHORS 5NEMO "27 June 1997"
.SH NAME
authors \- authorship of NEMO
.SH DESCRIPTION
NEMO was originally written in 1986 by Joshua Barnes (JEB),
Piet Hut (PH) and Peter Teuben (PJT), some of it based on earlier
(fortran) codes by some of these authors. Throughout the NEMO
code you may find various authors, and this manual page attempts
to place these people in their historic context.
.SH AUTHORS
.nf
.ta +1i
AdM	Patrick Frisch (Gottingen, 1991)
LH	Lars Hernquist
JEB	Joshua Barnes
JJM	James Marshall (UMD, June 1997)
JM	Jun Makino
JAS	Jerry Sellwood (Rutgers)
KGB	Kor Begeman (Groningen; some GIPSY related code)
PH	Piet Hut (IAS)
PJT	Peter Teuben (UMD)
RAG	Robert Gruendl (UMD)
SJA	Sverre Aarseth (IOA, Cambridge)
SMF	Scott Foster (UMD, 1992)
TRQ	Tom Quinn (Washington)
VS	Vikas Shah (UMD, 2000)
.fi
.SH "SEE ALSO"
nemo(1NEMO)
.SH AUTHOR
Peter Teuben
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
27-jun-97	Created  	PJT
.fi
