.TH AUTHORS 5NEMO "8 September 2001"
.SH NAME
authors \- authorship of NEMO
.SH DESCRIPTION
NEMO was originally written in 1986 by Joshua Barnes (JEB),
Piet Hut (PH) and Peter Teuben (PJT), Throughout the NEMO
code you may find various authors, and this manual page attempts
to place these people in their historic context.
.SH AUTHORS
.nf
.ta +1i
AdM	Patrick Frisch (Gottingen, 1991)
AMK 	Amanda Keller (UMD, Spring 1997)
JCL  	Jean-Charles Lambert (Marseille, 1997-)
JEB	Joshua Barnes (Hawai)
JJM	James Marshall (UMD, June 1997)
JM	Jun Makino (Tokyo)
JCM	Chris Mihos (Michigan, USA)
JN/JAN	Jeffrey Newman  (UMD, summer 1992?)
JAS	Jerry Sellwood (Rutgers)
KGB	Kor Begeman (Groningen; some GIPSY related code)
LA	Luis Aguilar (Ensenada, Mexico)
LH	Lyman Hurd (IAS, 1986-87)
LXH	Lars Hernquist (Harvard)
MB	Marc Balcells (U. Groningen, Netherlands - 1990)
MHS	Matthias Steinmetz (MPI, Garching, Germany)
MW	Martin Weinberg 
NEBK	Neil Killeen (ATNF - miriad)
NSK	Neal Katz
NVS	Nick Strobel (U. of Washtington, USA)
PAF/ADM	Patrick A. Frisch	Germany
PAS	Christian Theis  (Kiel, Germany)
PW	Peter Wisnovski (Princeton, summer 1987)
PH	Piet Hut (IAS)
PS	Panayotis Skordos (MIT, ~1987)
RAG	Robert A. Gruendl (UMD, 1990s)
RJS	Bob Sault (ATNF - miriad)
PJT	Peter Teuben (UMD)
PxS	Panajotis Skordis (MIT, 1986)
RAG	Robert Gruendl (UMD)
SJA	Sverre Aarseth (IOA, Cambridge)
SMF	Scott Foster (UMD, 1992)
TRQ	Tom Quinn (U.Washington)
VS	Vikas Shah (UMD, 2000)
WD	Walter Dehnen (Heidelberg)
WLS	William L. Sebok (UMD)
.fi
.SH CAVEATS
No doubt some have been forgotten....
.SH "SEE ALSO"
nemo(1NEMO)
.SH AUTHOR
Peter Teuben
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
27-jun-97	Created  	PJT
6-jun-01	few more updates	PJT
6-jul-01	moved more some authors over from files.8	PJT
.fi
