.TH DATA 5NEMO "12 May 1997"
.SH NAME
bench \- NEMO benchmarks
.SH DESCRIPTION
Nemo Benchmarks (a.k.a. NemoStones)
.PP
.SH "SEE ALSO"
data(5NEMO)
.SH AUTHOR
Peter Teuben
.SH FILES
.nf
.ta +2.5i
~/data   	standard repository area for data files.
.fi
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
12-may-97	created  	PJT
.fi
