.TH DATA 5NEMO "6 September 2006"
.SH NAME
bench \- NEMO benchmarks in NemoStones
.SH DESCRIPTION
Nemo Benchmarks (a.k.a. NemoStones)
.PP
\fBbench1\fP tests the classic (1986) Barnes and Hut code in C, without
quadrupole corrections, for 10240 particles and 64 timesteps.
\fBbench2\fP tests a more modern Treecode, this one is the
O(N) version from Dehnen (2002?). Again 64 timesteps.
\fBbench0\fP has been added to compare a tree code with a 
direct N-body code, also 64 timesteps. 
\fBbench3\fP benchmarks the creation of a large (>2GB) snapshot.
.SH DATA
Here are the benchmarks
.ta +1i
.nf
\fBbench0\fP:	\fItime directcode nbody=10240\fP
\fBbench1\fP:	\fItime hackcode1 nbody=10240\fP
\fBbench2\fP:	\fItime mkplummer p1 10240; time gyrfalcON p1 . kmax=6 tstop=2\fB
\fBbench3\fP:	\fItime mkspiral s000 1000000 nmodel=40\fP
\fBbench4\fP:	\fIccdmath "" - 'ranu(0,1)' size=128 | ccdpot - . help=c\fB
.fi
.PP
and the data :
.PP
.nf
.ta +3i
bench0
       P4/3.0           342.7
       G5/2.0           472.8
       AMD-opt64/2.0    300.3
       AMD-ath64/2.0    888.7
       P4/2.8 w/cygwin  365.9
       x86_64/3.0       516.4
       x86_64/3.2       480.6
      

bench1
       P4/3.0           13.4
       G5/2.0           13.1
       AMD-opt64/2.0     9.36
       AMD-ath64/2.0    17.45
       P4/2.8 w/cygwin  15.1
       x86_64/3.0       11.7
       x86_64/3.2       10.7
       sparcv9+vis/0.36 81.5

bench2
       P4/3.0           10.8
       G5/2.0           21.0
       AMD-opt64/2.0     8.1
       AMD-ath64/2.0     8.9
       P4/2.8 w/cygwin  45.5
       x86_64/3.2        8.6
       sparcv9+vis/0.36 85.1  

bench3 
       P4/3.0	22.890u  5.980s 1:45.63 27.3%
       G5/2.0	28.400u 24.660s 1:05.41 81.1% 
       AMD-opt64/2.0	18.540u 10.921s 0:56.93 51.7% 
       AMD-ath64/2.0	29.311u 10.353s 0:59.88 66.2% (SATA)
       P4/2.8	25.541u 8.081s 0:59.98 56.0% (S/ATA)
       P4/2.8 w/cygwin	276.56u 26.35s 6:34.75 76.7% (using mkplummer V2.8)
       x86_64/3.0       21.651u 8.897s 0:48.05 63.5%    0+0k 0+0io 0pf+0w
       x86_64/3.2       21.950u 9.997s 0:39.37 81.1%  (SATA)

.fi
.SH "SEE ALSO"
gyrfalcON(1NEMO), data(5NEMO), mkspiral(1NEMO), mkplummer(1NEMO), hackcode1(1NEMO), nbody1(1NEMO), scfm(1NEMO),
triple(1NEMO), accudate(lNEMO)
.SH AUTHOR
Peter Teuben
.SH FILES
.nf
.ta +2.5i
~/data   	standard repository area for data files.
.fi
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
12-may-97	created  	PJT
26-nov-03	finally added some data		PJT
17-feb-04	added bench0 comparison  	PJT
31-mar-05	added some cygwin numbers, fixed input	PJT
.fi
