.TH CONSTANTS 5NEMO "25 August 2020"
.SH NAME
constants \- list of useful constants 
.SH DESCRIPTION
Here we tabulate some convenience values we often use in astronomy
.SH CONSTANTS
.nf
.ta +1.5i 
3.1415926	pi, math
2.7182818	e, math
57.295780	Degrees per radian (180/pi)
206264.81	Arcseconds per Radian (3600*180/pi)
2.35482		STOF = 2*sqrt(2*ln(2)) - the FWHM/sigma of a gaussian 
1.13309		BOF (beam oversampling factor) = 1.13309 * (FWHM/PIXEL)^2  = pi/(4*ln(2))
3.26163		pc/ly 

6.6743e-11	G, grav constant in MKS units
299792.458	c, speed of light, in km/s
3.155693e7	yr, seconds in a year
149597870.700	AU, in km, as per IAU 2009 resolution B2
3.08567758e13	pc, defined as 648000/pi*AU, as per IAU 2015 resolution B2, in km
1.989e30	Solar Mass, in kg
5.974e24	Earth Mass, in kg
6378.1		Earth Radius, in km
1420.405751786	HI spectral line, in MHz
115.2712018	CO(1-0) spectral line, in GHZ
29.786		average earth orbital speed around sun, km/s
0.4638		earth rotation speed at equator, km/s
.fi
.SH CAVEATS
Galactic constants such as distance to the galactic center (8.5 kpc) or orbital speed of LSR (220 km/s) , are still subject to change.  See also \fImkgalorbit(1NEMO)\fP.
.SH "SEE ALSO"
ccdstat(1NEMO), ccdsmooth(1NEMO), mkgalorbit(1NEMO), units(5NEMO), data(5NEMO)
.SH AUTHOR
Peter Teuben
.SH FILES
.nf
.ta +2.5i
inc/cgs.h	constants in CGS units
inc/mks.h	constants in MKS units
inc/stdinc.h	PI
data     	NEMO standard repository area for data files.
.fi
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
21-aug-2020	created  	PJT
.fi


