.TH CONSTANTS 5NEMO "22 August 2020"
.SH NAME
constants \- list of useful constants 
.SH DESCRIPTION
Here we tabulate some convenience values we often use in astronomy
.SH CONSTANTS
.nf
.ta +1.5i 
3.1415926	pi, math
2.7182818	e, math
57.295780	Degrees per radian (180/pi)
206264.81	Arcseconds (3600*180/pi)
2.35482		2*sqrt(2*ln(2)) - the FWHM/sigma of a gaussian (\fIccdsmooth(1NEMO)\fP)
1.13309		Number of points per beam = 1.13309 * (FWHM/PIXEL)^2  = pi/(4*ln(2))   (\fIccdstat(1NEMO)\fP)
3.26		pc/ly 

6.6743e-11	Grav constant in MKS units
299792.458	c, speed of light, in km/s
3.155693e7	seconds in a year
149597870.700	AU, in km, as per IAU 2009 resolution B2
3.085678e15	pc, defined as 648000/AU, as per IAU 2015 resolution B2, in km
1.989e30	Solar Mass, in kg
6400		Earth Radius, in km
1420.405	HI spectral line, in MHz
115.217		CO(1-0) spectral line, in GHZ
30		average earth orbital speed around sun, km/s
2		earth rotation speed at equator, km/s
.fi
.SH CAVEATS
Galactic constants such as distance to the galactic center (8.5 kpc) or orbital speed of LSR (220 km/s) , are still subject
to change.
.SH "SEE ALSO"
data(5NEMO)
.SH AUTHOR
Peter Teuben
.SH FILES
.nf
.ta +2.5i
inc/cgs.h	constants in CGS units
inc/mks.h	constants in MKS units
inc/stdinc.h	PI
data     	NEMO standard repository area for data files.
.fi
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
21-aug-2020	created  	PJT
.fi


