.TH GSPD 5NEMO "10 June 2023" 

.SH "NAME"
gsp \- binary table format for General Spherical Models

.SH "DESCRIPTION"
\fIgsp\fP is a binary table format popular in ZENO to help making spherical models.
For a precursor to this format, see \fIommod(5NEMO)\fP
.PP
A typical procedure is to ...

.SH "EXAMPLES"

.SH "SEE ALSO"
mkommod(1NEMO), king(1NEMO), plummer(1NEMO), gsp(5NEMO)

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.5i +5.5i
10-jun-2023	man written	PJT
.fi
