.TH QAC_STATS 5NEMO "4 December 2021"

.SH "NAME"
qac_stats \- provide statistics that can be used as regression

.SH "DESCRIPTION"
The \fBQAC_STATS\fP is a series of numbers associated with a file
.nf

      QAC_STATS: ngc0001.ccd -4.29944e-05 0.0126181 -0.0720263 0.0892035  75.9081 -0.00437804

.fi
that represent
the mean, rms, min and max of a set of numbers. Optionally there are 2 or more numbers
present: the flux and the signal ratio \fIsratio=(psum+nsum)/(psum-nsum)\fP, where the sums
are over the positive and negative values. For sratio=0 (or near 0) there is no signal,
it's mostly noise, whereas for sratio=1 (or near 1) it's mostly signal.
.PP
It is used by a number of programs in NEMO, e.g. \fItabstat(1NEMO)\fP and \fIccdstat(1NEMO)\fP
where the keyword \fBqac=t\fP needs to be used to active this style of output.
.PP
Of course all of the interesting science happens near sratio=0 and one will need more sophisticated
signal detection schemes.
.SH "EXAMPLES"
For a FITS file:
.nf
   fitsccd NGC0001.fits - | ccdstat - qac=t bad=0
   
.fi

.SH "SEE ALSO"
tabstat(1NEMO), ccdstat(1NEMO)

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
4-dec-2021   document created     PJT
.fi
