.TH S2PLOTP 5NEMO "15 February 2011"
.SH NAME
s2plot \- s2plot keyboard and mouse controls 
.SH DESCRIPTION
Taken from their wiki page
on http://astronomy.swin.edu.au/s2plot/index.php?title=S2PLOT:Controls
.PP
Currently only one program, \fIsnaps2plot(1NEMO)\fP is using this interface,
and has been hardcoded, though uses the \fByapp=\fP system keyword to set
the S2PLOT_DEV device.
.PP
.SH KEYBOARD and MOUSE mappings
.nf
.ta +3i
\fBGeneral Interaction and Camera Control\fP
\fBKey	Description\fP

Left Mouse Button (Hold)	Free rotation of geometry
Middle Mouse Button (Hold)	Rotate (roll) camera clockwise/anti-clockwise
Right Mouse Button (Click)	Select/deselect a handle - see cs2shcb
Shift-Right Mouse Button (Hold)	Drag a handle - see cs2sdhcb
f, F	Focus camera on centre of geometry
h, H, Home	Home position - Returns camera to original starting position
r, R	Cycle rendering mode: wireframe, flat, diffuse and specular shading
Left arrow	Rotate camera left
Right arrow	Rotate camera right
Down arrow	Rotate camera down
Up arrow	Rotate camera up
i, k	Move (translate) camera up, down
j, l	Move (translate) camera left, right
+, -	Track camera forward/backwards
[, ]	Roll anticlockwise, clockwise - same as the middle mouse button
{, }	Increase/decrease the eye-separation for stereo modes
a, A	Toggle autospin
<,>	Decrease/increase camera interaction speed
*,/	Decrease/increase autospin speed
~	Activate the command prompt for use with cs2spcb
`	Toggle between odd and even scan lines for the /s2inter (interlaced stereo) device mode
shift-ENTER	Return control to program when using s2disp
TAB	Move between panels: see xs2cp
shift-q, shift-ESC	Quit the program

\fBFunction Keys and Saving Images or Geometry\fP
\fBKey	Description\fP

F1	Toggle help information - displays a list of keyboard options
F2	 Toggle bounding box
F5	 Write geometry and camera view file to disk
F6	 Write geometry, camera view file and current screen image to disk
F7	 Toggle recording of geometry, camera view file and image
F9	 Write large (3 x 3) image to disk - saves a series of 'chopped up' images for recombining to make a high quality image
F10	 Write current screen image to disk, saved in the current working directory
F11	 Create QTVR object images - rotates the scene creating a series of images (e.g. each frame can be joined to make a movie)
F12	 Toggle image recording - same as F11 but allows the user to rotate the geometry themselves
c	 Append current camera position to camera.path file
d	Toggle debug mode - provides information on camera position, frame rates, etc.
Notes:
Saved images are in TGA format and are numbered sequentially and uniquely
On Apple OSX platforms, it is usually necesary to hold down the fn key while using the above keystrokes

\fBCallback System\fP
\fBKey	Description\fP

z, Z	Toggle drawing of dynamic geometry by disabling/enabling a callback function set with cs2scb.
0...9	Available for assigning to callback functions using cs2sncb. The default operation of keys 1...7 is to display standard camera views. 0, 8 and 9 have no default behaviour
Space Bar	This key press is available through the callback system for programmer-assigned tasks. The number of times the space bar key is pressed is passed to a callback function as a parameter. For examples, see cs2scb.

\fBHandles\fP
\fBKey	Description\fP

shift-s	Toggle drawing of handles for selection
shift-C	Toggle drawing of cross-hairs
Right Mouse Button (press)	Select a handle
Shift-Right Mouse Button (hold)	Drag a handle
Ctrl+Shift-Mouse pad (hold)	Drag a handle
.fi
.SH S2PLOT
Much like it's older cousin PGPLOT, S2PLOT uses a
number of environment variables that control the behavior
of the plotting device. 
.nf
.ta +2i +1i
S2PLOT_DEC		/?	the default device to open

.fi
.SH AUTHOR
Peter Teuben
.SH SEE ALSO
yapp(3NEMO)
.SH UPDATE HISTORY
.nf
.ta +1i +4i
15-feb-2011	doc written	PJT
.fi
