.TH TLDR 5NEMO "24 October 2021"

.SH "NAME"
tldr \- (proposed) snippets for tldr in a man page


.SH "DESCRIPTION"
In 2021 we have started to use the \fBTLDR\fP section in a man
page, that can be used by the \fBtldr\fP program.
.PP
CAVEAT: Only the \fItsf(1NEMO)\fP program has been tried out.

.SH "SEE ALSO"
tsf(1NEMO), ads(5NEMO)

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
10-apr-2021	written		PJT
.fi
