.TH UNITS 5NEMO "11 July 2006"
.SH NAME
units \- various units used in simulations
.SH DESCRIPTION
Most NEMO programs use the "virial" (sometimes also called
"N-Body") units as described by
Heggie & Mathieu (1986). We also list a few other common
units, and the value of the gravitational constant in these.
Notably some of the \fIpotential(5NEMO)\fP descriptors use
other unit systems.
.PP
The gravitational constant is often set to unity in N-body codes, since
it saves a precious floating point operation!  However, for sake
of completeness, here are a few common values of G in some other 'common'
unit systems, recalling that G*m/(r*v*v) is dimensionless:
.nf
.ta +0.7i +0.7i +1i +1i +1i +0.5i +1i
  mass	length	velocity	G       	1/G     	time	"system"

     g	cm    	cm/s    	6.6732e-8  	1.49853e+07  	s   	(cgs)
    kg	m 	m/s     	6.6732e-11 	1.49853e+10   	s    	(SI)

     M	pc   	km/s    	.           	2.32385e2     	1e6.yr	(starcluster)
     M	kpc   	km/s    	.          	2.32385e5     	1e9.yr	.
1e10.M	10.kpc	100.km/s	.             	2.32385       	1e8.yr	(galaxy)
1e10 M	1.kpc	1.km/s		43007.1		.		1e9.yr	[gadget] 
~2e4.M	kpc   	~990.km/s	1          	1             	1e6.yr	(galaxy)
1e11.M	10.kpc	~97.8.km/s	4.497       	0.22237       	1e8.yr	(galaxy)

.fi
.SH UNITS
For the purpose of comparison of results obtained by different authors,
it is very convenient if they share a common system of units. The following
system of units seems to find quite wide (if not universal) favor. The units
are such that:
.nf
            G = 1
            M = 1
            E = -1/4
where G is the gravitational constant, M the total initial mass, and E the
initial energy. The corresponding units of mass, length and time are then
            U_m = M
            U_l = - G M^2 / (4E)
            U_t = G M^2.5 / (-4E)^1.5
(cf. Henon, 1972).

.fi
The choice for E looks odd, but corresponds to a virial radius R (harmonic
mean particles separation) equal to unity for a system in virial equilibrium.
In N-body work a somewhat different, actually N-dependant, system is often
used (cf. Aarseth 1972), but leads to a crossing time scale proportional
to N^(-1/2). This system is also unsuitable for galaxy simulations, where 
neither the number of stars nor the number of particles in the simulation
is relevant to the imortant dynamical timescales. There are of course
stellar dynamical calculations for which the above described units are
unsuitable, e.g. unbound systems or cosmological simulations.
.SH "SEE ALSO"
units(1NEMO), nemoinp(1NEMO)
.nf
Heggie, D.C. and Mathieu, R.D. 
\fIStandardized Units and Time Scales\fP, in:
\fIThe Use of Supercomputers in Stellar Dynamics\fP, ed. P. Hut and
S. McMillan. (1986, Spinger Verlag)
.fi
NPL's United of Measurement webpage: http://www.npl.co.uk/npl/reference/
.fi
AstroTables: http://nedwww.ipac.caltech.edu/level5/tabular_info.html
.SH AUTHOR
Peter Teuben
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
7-may-96	Created  	PJT
.fi
