.TH VOTABLE 5NEMO "21 March 2006"
.SH NAME
VOTable \- Virtual Observatory table exchange format
.SH DESCRIPTION
A \fBVOTable\fP file is an XML file.
.SH "SEE ALSO"
tab2xml(1NEMO), table(5NEMO)
.nf
http://www.ivoa.net/twiki/bin/view/IVOA/IvoaVOTable
.fi
.SH AUTHOR
Peter Teuben
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
15-apr-2003	V1.0 introduced
11-aug-2004	V1.1 introduced
.fi
