.TH VOTABLE 5NEMO "14 February 2004"
.SH NAME
VOTable \- Virtual Observatory table exchange format
.SH DESCRIPTION
A \fBVOTable\fP file is an XML file.
.SH "SEE ALSO"
tab2xml(1NEMO), table(5NEMO)
.nf
http://www.ivoa.net/twiki/bin/view/IVOA/IvoaVOTable
.fi
.SH AUTHOR
Peter Teuben
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
14-feb-04	document created  	PJT
.fi
