# 
include $(NEMOLIB)/makedefs

help:
	@echo no help for NBODY2

nbody1:
	(cd source; $(MAKE) $@)

clean:
	(cd source; $(MAKE) $@)

install:
	(cd source; $(MAKE) $@)

bins:
	(cd source; $(MAKE) $@)


wget:
	wget ftp://ftp.ast.cam.ac.uk/pub/sverre/nbody2/nbody2.tar.Z
	wget ftp://ftp.ast.cam.ac.uk/pub/sverre/nbody2/nbody2h.tar.Z
