#
include $(NEMOLIB)/makedefs

help:
	@echo no help for NBODY1

nbody1:
	(cd source; $(MAKE) $@)

clean:
	(cd source; $(MAKE) $@)

install:
	(cd source; $(MAKE) $@)

bins:
	(cd source; $(MAKE) $@)

#  some direct links to the original sources


wget:
	wget ftp://ftp.ast.cam.ac.uk/pub/sverre/nbody1/nbody1.tar.Z
	wget ftp://ftp.ast.cam.ac.uk/pub/sverre/nbody1/nbody1_real4.tar.Z
	wget ftp://ftp.ast.cam.ac.uk/pub/sverre/nbody1/nbody1h.tar.gz
