#! /bin/csh -f
#
#  Install CFITSIO for NEMO
#
#  17-apr-04    written

#			 	.. command line keywords ..
set src=$NEMO/local/cfitsio 

#				.. parse command line ..
foreach arg ($*)
   set check = `echo $argv[1] | awk -F= '{print NF}'`
   if ("$check" == 1) break
   echo Setting: $arg
   set $arg
end

if (! -e $src) then
  echo CFITSIO source directory src=$src does not exist
  exit 1
endif



cd $src
configure --prefix=$NEMO
make
make install 
