#! /bin/csh -f
#
#   post python install (e.g. after install_anaconda3)
#   assumes that python is now loaded
#
#  Jul-2023   split install_anaconda3 and this

set amuse   = 0

# you better know what you are doing here
foreach arg ($*)
  set $arg
end

if ( -e requirements.txt) then
   pip3 install -r requirements.txt
endif


# http://projets.lam.fr/projects/unsio/
# install a default via pip
# pip install unsio uns_projects
pip3 install python-unsio python-unsiotools

# but then install the developers version if these directories exist
if ($?NEMO) then
  foreach dir ($NEMO/usr/jsl/unsio $NEMO/usr/jsl/uns_projects)
    if (-d $dir) then
      echo Installing with pip3 install $dir
      (cd $dir ; pip3 install -e .)
    else
      echo Skipping pip3 install -e $dir
    endif
  end
else
  echo Warning:  no NEMO, skipping those components
endif

# https://github.com/adrn/gala
# conda install gala --channel conda-forge
pip3 install gala

# https://github.com/jobovy/galpy
#
pip3 install galpy

# https://github.com/GalacticDynamics-Oxford/Agama
#   - this needs GSL ;  libgsl-dev
#   - needs EIGEN   libeigen3-dev didn't do it
#   - needs CVXOPT  python3-cvxopt    or:   pip install cvxopt
#   - needs UNSIO - but my previous pip install didn't work
#   - GLPK library (optional) is not found, ignored  -  libglpk-dev 
pip3 install agama

# https://github.com/webbjj/clustertools
pip3 install clustertools

# https://github.com/pynbody/pynbody
#
pip3 install pynbody

# https://github.com/kyleaoman/martini
#
pip3 install astromartini

# https://github.com/yt-project/yt
#
pip3 install yt

# http://galpak3d.univ-lyon1.fr/
# optional: PyFFTW,  MPDAF, EMCEE , PyMultinest
pip3 install galpak

# https://amusecode.github.io/getting-started
#
pip3 install amuse-framework
# and a few simple starter packages
pip3 install amuse-galactics amuse-gadget2 amuse-bhtree

# Installing AMUSE takes a LONG LONG time, so by default this is not installed at first
# It also needs a lot more packages (see below)
#   pip install numpy nose docutils mpi4py h5py
#   pip install scipy astropy jupyter pandas seaborn
if ($amuse) then
  pip3 install amuse
endif  


# ubuntu packages for amuse:
#  build-essential gfortran python-dev \
#  libopenmpi-dev openmpi-bin \
#  libgsl-dev cmake libfftw3-3 libfftw3-dev \
#  libgmp3-dev libmpfr6 libmpfr-dev \
#  libhdf5-serial-dev hdf5-tools \
#  git
