#! /bin/csh -f
#
#   create a tar ball that could be dropped inside an 'old'
#   $NEMO to make it (anonymoous) cvs enabled
#

set nemo=nemo_$$
set tar=nemo_cvsdir.tar.gz

setenv CVSROOT :pserver:anonymous@cvs.astro.umd.edu:/home/cvsroot
echo Getting new NEMO in $nemo
if (! -d $nemo) then
  cvs -Q -d $CVSROOT co -d $nemo nemo
endif
cd $nemo
echo Making $tar
tar zcf ../$tar `find . -type d -name CVS -print`
echo Cleaning $nemo
rm -rf $nemo

