#! /bin/csh -f
#

alias e echo

e "# sh script"
e "# A kludge, generated by $0 - please do not edit"
e "NEMO=$NEMO;       export NEMO"

e "NEMOBIN=$NEMOBIN;   export NEMOBIN"
e "NEMODAT=$NEMODAT;   export NEMODAT"
e "NEMODOC=$NEMODOC;   export NEMODOC"
e "NEMOHOST=$NEMOHOST; export NEMOHOST"
e "NEMOINC=$NEMOINC;   export NEMOINC"
e "NEMOLIB=$NEMOLIB;   export NEMOLIB"
e "NEMOOBJ=$NEMOOBJ;   export NEMOOBJ"
e "NEMOSITE=$NEMOSITE; export NEMOSITE"
e "NEMOSRC=$NEMOSRC;   export NEMOSRC"
e "NEMOVER=$NEMOVER;   export NEMOVER"

e "BTRPATH=$BTRPATH;       export BTRPATH"
e "POTPATH=$POTPATH;       export POTPATH"

e "FALCON=$FALCON;         export FALCON"
e "FALCONLIB=$FALCONLIB;   export FALCONLIB"
e "ACCPATH=$ACCPATH;       export ACCPATH"
e "MANIPPATH=$MANIPPATH;   export MANIPPATH"

e "YAPP=$YAPP;               export YAPP"
e "PGPLOT_DIR=$PGPLOT_DIR;   export PGPLOT_DIR"

# PGPLOT_DIR should be sufficient
#e "PGPLOT_FONT=$PGPLOT_FONT; export PGPLOT_DIR"
#e "PGPLOT_LIB=$PGPLOT_LIB;   export PGPLOT_LIB"

e "VDEVICE=$VDEVICE;         export VDEVICE"



e "PATH=$PATH;                          export PATH"
e "MANPATH=$MANPATH;                    export MANPATH"
e "LD_LIBRARY_PATH=$LD_LIBRARY_PATH;    export LD_LIBRARY_PATH"




