#! /bin/csh -f
#


alias e echo

e "# sh script"
e "# A kludge, generated by $0 - please do not edit"
e "NEMO=$NEMO;       export NEMO"

e "NEMOBIN=$NEMOBIN;   export NEMOBIN"
e "NEMODAT=$NEMODAT;   export NEMODAT"
e "NEMODOC=$NEMODOC;   export NEMODOC"
e "NEMOHOST=$NEMOHOST; export NEMOHOST"
e "NEMOINC=$NEMOINC;   export NEMOINC"
e "NEMOLIB=$NEMOLIB;   export NEMOLIB"
e "NEMOOBJ=$NEMOOBJ;   export NEMOOBJ"
e "NEMOSITE=$NEMOSITE; export NEMOSITE"
e "NEMOSRC=$NEMOSRC;   export NEMOSRC"
e "NEMOVER=$NEMOVER;   export NEMOVER"
e "BTRPATH=.:$NEMOOBJ/bodytrans;   export BTRPATH"
e "POTPATH=.:$NEMOOBJ/potential;   export POTPATH"

e "YAPP=$YAPP; export YAPP"

e 'if [ -z "${PATH}" ]'
e 'then'
e '    PATH="$NEMOBIN"; export PATH'
e 'else'
e '    PATH="$NEMOBIN:$PATH"; export PATH'
e 'fi'

e 'if [ -z "${LD_LIBRARY_PATH}" ]'
e 'then'
e '    LD_LIBRARY_PATH="$NEMOLIB"; export LD_LIBRARY_PATH'
e 'else'
e '    LD_LIBRARY_PATH="$NEMOLIB:$LD_LIBRARY_PATH"; export LD_LIBRARY_PATH'
e 'fi'

e 'if [ -z "${MANPATH}" ]'
e 'then'
  set mp=(`man -w`)
  if ($#mp == 1) then
    e '    MANPATH="$NEMO/man":$(man -w); export MANPATH'
  else
    e '    MANPATH="$NEMO/man"; export MANPATH'
  endif
e 'else'
e '    MANPATH="$NEMO/man:${MANPATH}"; export MANPATH'
e 'fi'





