#! /bin/csh -f
#
#   simple wrapper to send nemo, or fits files, to the ds9 display
#   server. If you have ds9 from astromake, you should have mirds9
#   else, SOL for now.

if ($#argv == 0) then
  mirds9
  exit
endif

foreach f ($*)
  if (-e $f.fits) then
    mirds9 $f.fits
  else if (-e $f) then
    ccdfits $f $f.fits
    mirds9 $f.fits
    rm -f $f.fits
  else
    echo $f or $f.fits does not exist
  endif
end
