#! /usr/bin/env bash
#
#    report the NEMO environment, and provide some admin shortcuts
#

if [ "$1" == help ] || [ "$1" == --help ] || [ "$1" == -h ]; then
    cat $NEMO/docs/nemo.help
    exit 0
fi
os=$(uname -s)

gitbv() {
    _branch=$(cd $1;git branch --show-current)
    _counter=$(cd $1;git rev-list --count HEAD)
    _lastdate=$(cd $1;git log -1 --format="%at" | xargs -I{} date -d @{} +%Y/%m/%d_%H:%M:%S)
    _branch="$(printf %-10s $_branch)"
    _counter="$(printf %-10s $_counter)"
}    

if [ -z $NEMO ]; then
    echo "NEMO environment not loaded (odd)"
    exit 0
else
    _version=$(cat $NEMO/VERSION)
    gitbv $NEMO
    echo "NEMO:        $NEMO  - Version:$_version"
    echo "git:         Branch:$_branch Counter:$_counter Date: $_lastdate"
fi

echo "python:      $(which python)  - $(python --version)"
if [ $os == Linux ]; then
    echo "OS_release:  $os $(lsb_release  -d)"
elif [ $os == Darwin ]; then
    echo "OS_release:  $os $(sw_vers -productVersion)"
else
    echo "OS_release:  $os (unknown)"
fi
gitbv $NEMO

# this is a relatively new git option, disable until we all have it
# (cd $LMTOY; make branch)


if [ "$1" == pull ]; then
    cd $NEMO
    make pull
fi

if [ "$1" == dev ]; then
    echo "----------------------------------------------------------"
    echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
    echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
    echo "PGPLOT_DIR:      $PGPLOT_DIR"
    echo "----------------------------------------------------------"
    echo "tsf:              "  $(tsf help=V)
    echo "tabplot:          "  $(tabplot help=V)
    echo "fitsccd:          "  $(fitsccd help=V)
    echo "----------------------------------------------------------"    
fi
