#! /usr/bin/env python
#
#   parameter editor for "keyword    value"
#                     or "keyword=value"
#   parameter files
#
#   Usage:   pedit pfile [options] a=1 f="'a.fits'"
#
#   Options:
#            -e      bash style keyword=value
#
#
#   @todo   error checking
#           implement some options:
#             -g : grep like function
#             -c : pick comment character?
#             -m : mode (e.g. using '=' between key and val)


import sys

if len(sys.argv) < 2:
    print("Usage: %s [options] parfile a=1 f=\"'a.fits'\" > parfile.new" % sys.argv[0])
    sys.exit(1)


filename = sys.argv[1]
eqmode   = False

kv = {}

for keyval in sys.argv[2:]:
    if keyval=='-e':
        eqmode = True
        continue
    ieq = keyval.find('=')
    key = keyval[:ieq]
    val = keyval[ieq+1:]
    kv[key] = val

lines = open(filename).readlines()

for line in lines:
    line = line.strip()
    w = line.split()
    if len(w) > 1:
        if w[0] in kv:
            if eqmode:
                print("%s = %s" % (w[0],kv[w[0]]))
            else:
                print("%s   %s" % (w[0],kv[w[0]]))
        else:
            print(line.strip())
    else:
        if eqmode:
            w=line.split('=')
            if len(w)==2:
                if w[0] in kv:
                    print("%s=%s" % (w[0],kv[w[0]]))
                else:
                    print("%s" % line)
            else:
                print("%s" % line)
        else:
            print(line.strip())        
        
