#! /bin/csh -f
#
#  make sure this is executed from the $NEMO directory
#

set cc=""
set f77=""

foreach arg ($*)
  set $arg
end

if (-e nemo_end) then
   source nemo_end
else
   exit 1
endif

if ("x$cc" != "x") setenv CC $cc
if ("x$f77" != "x") setenv F77 $f77


./configure --with-yapp=ps
source nemo_start
make dirs config_extra scripts
source NEMORC.local
rehash
make libs
src/scripts/testsuite -b



