#! /bin/csh -f
#

set log=/tmp/tellme.log

if ($?NEMO == 0) exit 0

touch $log

echo "=== NEMO tellme ===" > $log
date     >> $log
uname -a >> $log
whoami   >> $log
hostname >> $log
pwd	 >> $log

echo === NEMOLIB:	 >> $log
ls -l $NEMOLIB		 >> $log
echo === NEMOBIN:	 >> $log
ls -l $NEMOBIN		 >> $log

echo === NEMOBIN/cc:	 >> $log
if (-e $NEMOBIN/cc) then
  cat $NEMOBIN/cc	 >> $log
else
  echo N/A               >> $log
endif

echo === BEGIN PRINTENV >> $log
printenv      >> $log
echo === END PRINTENV >> $log




echo A file $log has been created
