#! /bin/csh -f
#
#
if ( $#argv == 0 ) then
  echo "Usage: $0 progname key1=def1 ..."
  echo "Write template NEMO program based on keywords and default values"
  echo "Output will be in a file progname.c, which cannot be overwritten"
  exit 0
endif

set name=$1.c
shift argv

if ( -e $name ) then
  echo File $name already exists
  exit 0
endif

alias e echo

e '/*' > $name
e ' *  TEMPLATE: created by NEMO ' >> $name
e ' */' >> $name
e '' >> $name
e '#include <stdinc.h>' 	>> $name
e '#include <getparam.h>'	>> $name
e '' >> $name
e 'string defv[] = {'		>> $name
foreach a ($argv)
e '    "'$a'",'			>> $name
end
e '    "VERSION=0.0",'		>> $name
e '    NULL,'			>> $name
e '};'				>> $name
e '' >> $name
e 'string usage="TEMPLATE program usage -- fill in yourself";' >> $name
e '' >> $name
e 'nemo_main()'			>> $name
e '{'				>> $name
e '  /* your code goes here */' >> $name
e '}'				>> $name
