#! /bin/csh -f
#
#
if ( $#argv == 0 ) then
  echo "Usage: $0 progname key1=def1 ..."
  echo "version 15-apr-2003"
  echo "Write template NEMO program based on keywords and default values"
  echo "Output will be in a file progname.c, which cannot be overwritten"
  
  exit 0
endif

set prog=$1
set name=$prog.c
set date=`date +%d-%b-%Y` 
shift argv

if ( -e $name ) then
  echo File $name already exists, will not overwrite it.
  exit 0
endif

alias e echo

e '/*' > $name
e ' *  TEMPLATE: created by NEMO ' >> $name
e ' */' >> $name
e '' >> $name
e '#include <stdinc.h>' 	>> $name
e '#include <getparam.h>'	>> $name
e '' >> $name
e 'string defv[] = {'		>> $name
foreach a ($argv)
e '    "'$a'\\n    some help",'	>> $name
end
e '    "VERSION=0.0\\n      '$date' XYZ",'		>> $name
e '    NULL,'			>> $name
e '};'				>> $name
e '' >> $name
e 'string usage="TEMPLATE program usage -- fill in yourself";' >> $name
e '' >> $name
e 'nemo_main()'			>> $name
e '{'				>> $name
e '  /* your code goes here */' >> $name
e '  /* e.g.   string s = getparam("s");  */'  >> $name
e '  /* e.g.   int    i = getiparam("i"); */'  >> $name
e '  /* e.g.   real   r = getrparam("r"); */'  >> $name
e '  /* e.g.   double d = getdparam("d"); */'  >> $name
e '  /* followed by lots of lovely calculations */' >> $name
e '}'				>> $name

echo "All done, $name created. You can compile it using the command"
echo "     bake $prog"
