#! /bin/bash
#
#   query which pgplot devices exist; return the first valid one
#

tmp=/tmp/yapp$$

echo circle 10 10 1 > $tmp.yapp

for arg in $*; do
    yapp - $tmp.yapp yapp=$tmp.$arg/$arg > $tmp.log 2>&1
    if [ -e $tmp.$arg ]; then
	echo $arg
	rm $tmp.*
	exit 0
    fi
done

# cleanup
rm $tmp.*
exit 1
