*       common4.
*       --------
*
      INCLUDE 'params.h'
      IMPLICIT REAL*8  (A-H,O-Z)
      INTEGER        GPID,GPSTAT,ILIST,IPIPE,ITYPE,JLIST,JPERT,
     &               KSLOW,KSTAR,KTYPE,KVEC,KZ,LIST,LISTD,LISTV,LSHORT, 
     &               NAME,NLIST,NPOP
*
      COMMON/NBODY/  X(3,NMAX),X0(3,NMAX),XDOT(3,NMAX),X0DOT(3,NMAX),
     &               F(3,NMAX),FDOT(3,NMAX),D2(3,NMAX),D3(3,NMAX), 
     &               BODY(NMAX),PHI(NMAX),STEP(NMAX),T0(NMAX)
*
      COMMON/PAIRS/  DTB,HT,TBLIST,
     &               DTAU(KMAX),FD0(4,KMAX),FP0(4,KMAX),FU(4,KMAX),
     &               FUDOT(4,KMAX),FUDOT2(4,KMAX),FUDOT3(4,KMAX),
     &               GAMMA(KMAX),H(KMAX),H0(KMAX),HDOT(KMAX),
     &               HDOT2(KMAX),HDOT3(KMAX),HDOT4(KMAX),
     &               R(KMAX),R0(KMAX),SF(7,KMAX),TDOT2(KMAX),
     &               TDOT3(KMAX),U(4,KMAX),U0(4,KMAX),UDOT(4,KMAX),
     &               NNTB,KBLIST(KMAX)
*
      COMMON/NAMES/  GPID,GPSTAT,ICOMP,IDUM1,IFIRST,IPHASE,ISEND,
     &               JCLOSE,JCMAX,JCOMP,KSPAIR,MODEL,
     &               N,NAME0,NBIN0,NC,NCH,NCRIT,NFIX,NHI0,
     &               NMERGE,NPAIRS,NPIPE,NRUN,NSUB,NTOT,NZERO,
     &               KSLOW(KMAX),KVEC(2*KMAX),KZ(40),LIST(LMAX,2*KMAX),
     &               LISTD(50),LISTV(20),LSHORT(40),
     &               NLIST(LMAX),NAME(NMAX)
*
      COMMON/COUNTS/ NBCALL,NBESC,NBLOCK,NBPREV,NCBLK1,NCBLK2,NCHAIN, 
     &               NCOLL,NDIAG,NDISS,NDUMP,NEWHI,NHIVEL,NHLIST,
     &               NIRECT,NKSHYP,NKSMOD,NKSPER,NKSREG,NKSTRY,NMERG,
     &               NMESC,NMTRY,NPRECT,NPRINT,NQUAD,NSESC,NSHORT,
     &               NSPERT,NSTEPC,NSTEPI,NSTEPQ,NSTEPS,NSTEPT,
     &               NSTEPU,NSYNC,NSYNCH,NTIDE,NTIMER,NTPERT,NTRECT,
     &               NTRIP,NTTRY,NURECT,NWARN,N1,
     &               IPIPE(20),NPOP(10)
*
      COMMON/PARAMS/ ALPHA,AZ,BBCOLL,BODY1,BODY23,BODYM,BODYN,CHCOLL,
     &               CMSEP2,CPU,CPU0,CPUTOT,DELTAS,DELTAT,DETOT,DMIN1,
     &               DMIN2,DMIN3,DMIN4,DMINC,DTADJ,DTLIST,DTMIN,
     &               EBCH0,EBH,EBIB,EBIN,EBIN0,ECLOSE,ECOLL,EDISS,
     &               EMERGE,ERROR,ERRTOT,ESUB,ESYNC,ETA,ETA0,ETAU,ETIDE, 
     &               GMAX,GMIN,ONE3,ONE6,ONE9,ONE12,PCRIT,POT,QE,
     &               RBAR,RC,RHOD,RHOM,RMAX,RMIN,RMIN2,RMIN22,RSCALE,
     &               RSPH2,RTIDE,SBCOLL,SMIN,STEPY,T,TADJ,TCR,TCRIT,
     &               TCR0,TDUMP,TIME,TLASTS,TLASTT,TLIST,TOFF,TPRINT,
     &               TSCALE,TTIME,TTOT,TWOPI,VC,ZKIN,ZMASS,ZMBAR,ZMC, 
     &               ZMTOT, 
     &               BE(3),CMR(4),CMRDOT(4),E(12),GPRINT(9),ORBITS(9),
     &               RDENS(3),SCOEFF(12),TIDAL(4),TLASTB(9),STEPJ,
     &               XDUMMY(9)
*
      COMMON/STARS/  AU,DAYS,DTPLOT,DTSHOCK,ECDOT,EKICK,EMDOT,EPOCH0,
     &               GM,PC,RAU,RG0,RMSTAR,SMU,SPNFAC,STEPX,SU,
     &               TEV10,TMDOT,TPHYS,TPLOT,TSHOCK,TSTAR,TURN,
     &               UT,VSTAR,YRS,ZMDOT,ZMET,ZMHE,ZMNH,ZMRG,
     &               ZMRO,ZMRS,ZMSN,ZMSY,ZMWD,
     &               BODY0(NMAX),EPOCH(NMAX),RADIUS(NMAX),SPIN(NMAX),
     &               TEV(NMAX),TEV0(NMAX),XSTAR(NMAX),YDUMMY(10),
     &               ZLMSTY(NMAX),ZPARS(20),
     &               IQCOLL,NAS,NBH,NBKICK,NBR,NBRK,NBS,NCHA,NCIRC,
     &               NCOAL,NCONT,NDD,NEMOD,NGB,NGLOB,NGLOB0,NHE,NHG,NHI,
     &               NHYP,NKICK,NMDOT,NMS,NNH,NRG,NRO,NROCHE,NRS,NRSAVE, 
     &               NSHOCK,NSLP,NSN,NSP,NSPIR,NSTAB,NTZ,NWD,
     &               ITYPE(KMAX,5),KSAVE(4),KSTAR(NMAX),
     &               KTYPE(0:14,0:14),ITAIL0,NTAIL,NTTOT,NSTAIL,
     &               NGDUM(5),IBLUE
*
      COMMON/BLOCKS/ TBLOCK,TPREV,DTK(40),TNEXT(NMAX)
*
      COMMON/LISTS/  ILIST(1024),JLIST(NMAX),JPERT(5*LMAX)
