include $(NEMOLIB)/makedefs

help:
	@echo "install:         install NEMOBIN/gravidy"
	@echo "rebound:         grab the code"

rebound:
	git clone http://github.com/hannorein/rebound 

clean:
	rm -rf rebound

