%    -*- LaTeX -*-     for inclusion in nemo.tex
% 26-mar-94  for V2.2
%
%  Opening statements: Acknowledgements:

\myfile{ack.inc}
% \small


Without any doubt Josh Barnes deserves {\bf the} credit for the work
that lies in front of you.  Most of the visible parts, such as the user
interface and the filestructure, were originally developed by
Josh\index{Barnes J.} Barnes, in collaboration with Piet\index{Hut P.}
Hut and  Peter\index{Teuben P.} Teuben at the Institute for Advanced
Study during the 1986/87 academic year. At the initial stages of this
project we have also benefitted from contributions by Lyman\index{Hurd
L.} Hurd, Eric\index{Roberts E.} Roberts, Mark\index{Ross M.} Ross, and
Panayotis Skordis\index{Skordis P.}. You will also find many ideas
originally developed in NEMO in derived and evolved products
such as AMUSE, Starlab and ZENO.

Of course any package will only improve when it is used.  Numerous
people, in particular the University of Maryland graduate students and
Stefano Casertano \index{Casertano S.} have suffered through several
stages of testing.  Without them and their complaints we would never be
where we are now.  Needless to say, we need more complaints! We would
also like to express our sincere thanks to \index{Aarseth S.} Sverre
Aarseth, for his hard work on the industry standard series "{\bf
NBODY*}", which has also become a part of NEMO, and Lars Hernquist,
\index{Hernquist L.} for providing a fortran version of the treecode. 
Mark Bellon \index{Bellon M.} has contributed his optimized C version of
treecode which specifically runs well on some parallel processors.  
% ds disappeared in release 3
% Bill Sebok \index{Sebok W.L.} contributed the {\tt ds} image display tool. 
The {\tt GIPSY} and {\tt MIRIAD} \index{GIPSY} programming
\index{miriad} groups are also continuesly supplying us with software.
Being one of the early
guinea pigs of the C version of Numerical Recipes
we have also benefitted  from some code from Numerical 
Recipes\index{Numerical Recipes} Software.
Finally, the {\tt Usenet} public domain has proven to be of great value,
and you will find several utilities in {\it e.g.} {\tt
\$NEMO/src/tools} and {\tt \$NEMO/usr/lib}.
There are too many to be all acknowledged at this
place, the manual pages and/or source code will contain appropriate
references. 

\begin{flushright}
{\it P.T.}  
\end{flushright}

\begin{flushleft}
{\it College Park, Maryland}\\
{\it November, 1991}\\
{\it August, 1994}\\
{\it June, 2005}\\
{\it December, 2017}
\end{flushleft}

\normalsize
