%% This file is to be included by latex in nemo.tex
%
% Appendix: Units and Coordinate Systems
\myfile{coordsys.inc}
\mylabel{a:coordsys}

\section{Coordinate Systems}

Astronomy is well known for its confusing coordinate systems: nature and math don't
always look at things through the same mirror. For example, the right handed 
coordinate system that we call X-Y-Z does not neat fit with the our galaxy, which
rotates counter-clockwise (meaning the angular moment vector points to the galactic
south pole). The $\alpha \delta$ Right-ascension Declination system is pinned on the
sky, looking up, instead of on a sphere, looking down, and thus Right-ascension
increases to the left if plotted as seen from earth.

\section{Units}



