%% This file is to be included by latex in nemo.tex
%
%   Opening statements: Disclaimer
\myfile{disclaimer.inc}
\small

Because the present version of NEMO is passed around free of
charge, we provide absolutely no warranty whatsoever. 

You are of course free to pass this package on to your friends and
enemies, but we really prefer to receive a 
mailing address of/from that new user.
This is not only to keep us informed of any new users, but also to
enable to send out information about updates.

%  
While we very much appreciate receiving bug \index{bug} 
reports\footnote{{\tt nemo@astro.umd.edu}},
presently we\index{Teuben P.}
do not have anyone officially
assigned to the task of maintaining NEMO. 
Therefore we cannot guarantee speedy reply. 

% Hopefully we will be able to release a more
% official release of NEMO in the future, and with a little bit of
% luck we may obtain funds to pay someone to start a more professional
% maintenance of this package.

If the above has not been enough of a disclaimer, let us say that this
version of NEMO is still a preliminary version of what might once become
a ``real'' system with the usual support facilities.  We strongly
discourage usage of this system if you are not in regular contact with
the distributor(s), simply because we feel that the system hasn't been
sufficiently tested yet.  At the same time, we want to make NEMO
available as soon as we can, so, voil\`a: all these disclaimers. 

The name NEMO:\index{NEMO, the name} 
originally we had set up directories owned by "{\tt nobody}", 
however it turned out that this is already a name with a predetermined
functionality in UNIX. Subsequently the latin \index{Keitao}
analog, {\it nemo}, was adopted\footnote{It's 
greek analog is KEITAO, Zeno is a NEMO descendant}.
Not meant to be used as an acronym, we owe the following one to
Luis Aguilar: {\it Not Everyone Must Observe}. \index{Aguilar L.}
Another nice one is hidden in this manual, which we leave
as an exercise to the reader.
% NEed we say MOre ?

\normalsize
