%% This file is to be included by latex in nemo.tex
%
%  References
%
\myfile{refs.inc}
\mylabel{c:refs}

{\it "The Unix C Shell Field Guide"} -
(Anderson, G. and Anderson, P., Prentice Hall, 1988).

{\it "A Hierarchical O(N log N) Force-Calculation"} -
Barnes, J.E. and Hut, P. 
(Nature, Vol. 324, pp 446 1986).

{\it The FITS tables extension.} -
Harten R.H., Grosbol, P., Greisen, E.W. and Wells, D.C.
(A\&A Suppl. 73, 365, 1988)

{\it "Hierarchical N-body Methods"} -
L. Hernquist, 
(Computer Physics Communications, Vol. 48, p. 107, 1988.)

{\it "Computer Simulation Using Particles"}
R. W. Hockney and J. W. Eastwood
(Adam Hilger; Bristol and Philadelphia; 1988)

{\it "The Numerical Solution of the N-body Problem"} -
(L. Greengard. Comp. in Phys. pp. 142, mar/apr 1990.)

{\it "Use of Supercomputers in Stellar Dynamics"} -
(S.M. McMillan and P. Hut. Berlin: Springer-Verlag 1987).

{\it "The Art of N-body Building"} J.A. Sellwood -
(Ann. Rev. Astron. Astrophys. Vol. 25, pp. 151 1987).

{\it "FITS -- "} -
(Wells et al., A\&A Suppl. 44, 363. 1981)

{\it "Effective Fortran"} - Metcalf. Oxford: Clarendon Press (1985).

{\it "Numerical Recepies"} - Press et. al. ... Various editions in various languages.

{\it "Galactic Dynamics"} - Binney, J. and Tremaine, S.
(Princeton U. Press; Princeton; 1987) [BT1]

{\it "Galactic Dynamics 2nd Ed."} - Binney, J. and Tremaine, S.
(Princeton U. Press; Princeton; 2008) [BT2]
