.TH CACM 3NEMO "12 May 2003"
.SH NAME
cacm \- C.A.C.M. algorithms
.SH DESCRIPTION
Hidden in NEMO are a number of CACM algorithms. This page described some
of their routines, and their usage.
.nf
.ta +2i
CACM 423 : decomp, solve
spline, seval            	src/kernel/misc/spline.c
.fi
.SH SEE ALSO
.nf
.ta +2i
http://www.netlib.org
http://math.nist.gov/toms/	Transactions on Mathematical Software (TOMS)
.fi
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1i +4i
12-may-03	Created       	PJT
.fi

