.TH IDFIO 3NEMO "12 August 2014"
.SH NAME
idfXXX \- Input Directive File  I/O
.SH SYNOPSIS
.nf
.B #include <idfio.h>
.PP
.SH DESCRIPTION
\fIidfio()\fP presents a set of methods to simplify running
external programs that need a simple parameter file,
with a NEMO-like interface.  


.PP
Some resemblence to the FORTRAN \fInamelist\fP is made.
.SH CAVEATS
some
.SH SEE ALSO
run(3NEMO)
.SH AUTHOR
Peter Teuben
.SH FILES
.nf
.ta +1.5i
~/src/kernel/io  	idfio.c
.fi
.SH UPDATE HISTORY
.nf
.ta +1i +4i
12-aug-2014	Created		PJT
.fi
