.TH IMSL 3NEMO "5 March 1994"
.SH NAME
icsccu, icsevu, dcsevu \- IMSL emulator routines for interpolation and differentiation
.SH DESCRIPTION
Need to document this. They emulate IMSL routines, although note that
the arguments are C-friendly: called by value where possible.
.SH HISTORY
.ta +1.0i +3.0i
5-mar-94	man created 	PJT
.fi
