.TH UNSIO 3NEMO "24 November 2010"
.SH NAME
unsio - Unified Nbody Snapshot I/O routines
.SH SYNOPSIS
.SH DESCRIPTION
\fIunsio\fP will be described later, in essence it is an I/O layer that allows you
to read a variety of Nbody snapshot formats. Currently implemented are nemo and gadget.
 See \fIuns_2dplot(1NEMO)\fP for an example.
.SH SEE ALSO
uns_2dplot(1NEMO)
.PP
https://projets.lam.fr/projects/unsio
https://projets.lam.fr/projects/uns_projects
.SH AUTHOR
Jean-Charles Lambert
.SH FILES
.nf
.ta +1.5i
~/usr/jcl/unsio     library code
~/usr/jcl/uns_project   example code
.fi
.SH UPDATE HISTORY
.nf
.ta +1i +4i
may-2010	prototype installed     JCL
.fi

