.TH BADMAN 8NEMO "7 May 1992"
.SH NAME
badman \- create reference to non-existing documentation
.SH SYNOPSIS
\fBbadman\fP \fIman_name  man_level\fP
.SH DESCRIPTION
\fIbadman\fP creates a reference to a non-existing man page using
the roff include file (.so) command to \fI$NEMO/man/man1/badman.1\fP
manual page.
.SH HISTORY
.ta +1.0i +3.0i
7-may-92	this man page created    	PJT
.fi
