.TH CHECKPARS NEMO "21 May 2021"

.SH "NAME"
checkpars \- check consistency between keywords described in man page and executable

.SH "SYNOPSIS"
.PP
\fBcheckpars.py \fI[-v] [-f tasklist]\fP

.SH "DESCRIPTION"
\fIcheckpars\fP reports on a consistency check if the parameters listed in the man page
of a program are in agreement with the ones reported via the \fIgetparam(3NEMO)\fP. Not
only should the same parameter names be documented, but also their order. Typically
the verbose output would report the two lists, e.g.
.nf

ccdmoms
man: ['in', 'out', 'mom', 'weights', 'axis', 'win', 'sigma']
bin: ['in', 'out', 'mom', 'weight', 'axis', 'win', 'sigma']

.fi

has an obvious typo.
.PP
By default a predefined \fBtasklist\fP is used, but this is not an exhaustive list. Using the
\fB-f\fP flag another list could be passed (only the first word per line is the name of the
program to be checked).


.SH "EXAMPLES"
.nf
    % \fBmake checkpars\fP
    python checkpars.py -v > checkpars.log
    Files read: 200
    Bad files found: 104
    % \fBmore checkpars.log\fP
.fi
.SH "SEE ALSO"
mknemo(8NEMO)

.SH "AUTHOR"
Parker Tewell

.SH "FILES"
.nf
.ta +1.5i
$NEMO/src/scripts/checkpars.py         	script
$NEMO/src/scripts/tasklist		default list of binaries to check
.fi

.SH "UPDATE HISTORY"
.nf
.ta +1i +4i
15-apr-2021	first version	    PPT
30-apr-2021	added -v flag	    PPT
06-may-2021	added -h flag	    PPT
21-may-2021	draft man created   PJT
29-may-2021	added -f flag	    PPT
22-jul-2021	added -u flag	    PPT


.fi
