.TH EXPORT 8NEMO "6 July 2001"
.SH NAME
export \- export new files as a tar file to remote sites (deprecated)
.SH SYNOPSIS
.B export.csh 
.I root-dir [user(s)...]
.SH DESCRIPTION
This script is now deprecated. We are now using CVS for source code
control.
.PP
\fBexport\fP is currently installed as a shell script
\fIexport.csh\fP. It's first parameter is the root directory
name of the package one wants to export from. It creates a list
of files newer than the timestamp of a checkfile, which are
combined into a tar image. This tar image is copied to
a number of sites, listed in the \fINetrc\fP file, using
\fIftp(1)\fP.
.PP
Although the original copies of all import/export files live in
$NEMO/src/nemo/adm, the working copies are placed in $NEMO/adm (\fBmake
adm\fP).  Execution of import and export scripts must be from this working
directory, as they are not placed in general accessible bin directories
in a users search path. 
.PP
The name of the tarfile is of the format \fBmmdddyy.hostname\fP. After
a tarfile has been imported by the import script, a dash (\fB-\fP) is
appended to the filename.
.SH FILES
In $NEMO/src/nemo/adm: original copies, in $NEMO/adm: working copies.
.sp 2
.nf
.ta +2.0i
$NEMO/adm	root directory for all local import/export activity
$NEMO/adm/import	imported tar files from other sites
$NEMO/adm/export	exported tar files to other sites
export.csh	export script, often called by Nightly
import.csh	import script, normally called manually
Nightly   	script run by cron
crontab   	example crontab file to run Nightly
Netrc   	file with list of remote sites for export
Last_ntar	time check file, needed by export
.fi
.SH AUTHOR
Peter Teuben
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.5i
2-apr-90	manual written	PJT
.fi
