.TH HISTORY 8NEMO "17 April 2021"
.SH NAME
history \- a history of NEMO
.SH DESCRIPTION
\fINEMO\fP was developed in 1986/87 at the Institute for Advanced
Study (Princeton) by Hut, Barnes and Teuben. These are my personal
notes and reflections on its history.
.PP

.SH AUTHOR
Peter Teuben
.SH "UPDATE HISTORY"
.nf
.ta +1i +4i
17-apr-2021	finally some notes	PJT
.fi
