.TH MANYBODY 8NEMO "13 November 2022"

.SH "NAME"
manybody \- a meta package of many n-body like codes

.SH "DESCRIPTION"
\fImanybody\fP was an effort to bring together 
various activities related to simulations of stellar systems,
starting with the MODEST collaboration.
.PP
In earlier workshops the manybody manual was used to give
examples how different packages could be used.
.PP
A more modern approach developed out of MODEST, and eventually
became AMUSE.

.SH "SEE ALSO"
.nf
http://www.manybody.org
http://www.amusecode.org
$NEMO/text/manybody
.fi

.SH "CAVEAT"
New codes have not been included, notably AMUSE

