.TH MKMAN 8NEMO "13 June 2024"

.SH "NAME"
mkman \- create a template man page from a NEMO command

.SH "SYNOPSIS"
.PP
\fB$NEMO/src/scripts/mkman command > $NEMO/man/man1/command.1\fP

.SH "DESCRIPTION"
Since NEMO commands are self-describing, this scripts takes the
output using \fBcommand help=h\fP and creates a template man
page. 
.PP
The following command would bootstrap a completely new command
in NEMO called \fBfoo\fP with four keywords and given defaults
for three of them:
.nf

  $NEMO/src/scripts/template foo  a=1 b=2 c=3 d=
  mknemo foo
  $NEMO/src/scripts/mkman foo > $NEMO/man/man1/foo.1

.fi

after which foo.c and foo.1 will need some editing, but should
be fully functional!

.SH "SEE ALSO"
help2man(1)
.PP
https://www.gnu.org/prep/standards/standards.html#Man-Pages

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.25i +4.5i
20-mar-2021	finally written		PJT
.fi
