.TH MKNEMO 8NEMO "24 August 2006"
.SH NAME
mknemo \- attempt to find NEMO programs and install them
.SH SYNOPSIS
.PP
\fBmknemo \fIprogram(s)\fP 
.SH DESCRIPTION
\fImknemo\fP attempts to find the source code of the program(s)
specified on the command line, and tries to compile them.
If successfull, the binary will be placed in \fB$NEMOBIN\fP.
Add the '-u' flag if your NEMO is under CVS control, so you can
force an update before the build.
.PP
On a first pass a single
source file \fIprogram.c\fP is looked for, which is
compiled with a local \fBMakefile\fP (or a template
if none is available). If no source code is found,
a directory with the name \fIprogram\fP is searched for, 
and a local Makefile is then used to install the \fIprogram\fP.
.PP
After the binary is moved over to \fB$NEMOBIN\fP, the script
\fImkpdoc\fP is called to see if the \fIdoc(5)\fP file needs 
to be updated.
.SH "OPTIONS"
.nf
  -c CODE   search for CODE.c to set the directory for target(s)
  -n N      selection of N-th element from unresolved list [1]
  -s DIR    root directory to start search [$NEMO/src]
  -a        also search $NEMO/usr 
  -r        remove lockfile before starting
  -d        also make doc file (only for true NEMO programs)
  -t        cleanup after having made the binaries
  -T        cleanup before making the binaries
  -u        update your NEMO cvs tree before (re)making
  -l        recompile the library before (re)making 
  -g        use gmake, instead of make
  -v        more verbose, it will report version and cvsid of program
.fi
.SH EXAMPLES
Here are some examples of the non-default control files in $NEMO/src/scripts/mknemo.d:
.nf 
.ta +2i
firstn    	nbody code
glnemo   	glnemo graphics
gyrfalcON   	falcON tools (gyrfalcON, mkplum, the acc's and manip's)
rotcur    	rotcur program (there is also a confusing rotcur \fIpotential(5NEMO)\fP)
.fi
.SH "SEE ALSO"
mkbin(8NEMO)
.SH AUTHOR
Peter Teuben
.SH FILES
.nf
.ta +3.0i
$NEMO/src/scripts/mknemo.d	directory with non-default control files for mknemo
$NEMOLIB/NEMORC		environment variables
$NEMOLIB/makedefs	make variables
$NEMOLIB/libnemo.a	main NEMO library
$NEMOLIB/yapp*.o	various device drivers
$NEMO/src          	source tree searched for programs/directories
$NEMO/adm/install/mknemo.log	logfile of all previous installs done
$NEMO/adm/install/mknemo.lock	lockfile, to prevent multiple usage
.fi
.SH "UPDATE HISTORY"
.nf
.ta +1i +4i
21-jun-91	V1.0: doc created       	PJT
25-jun-91	V1.1: added lockfile     	PJT
4-apr-01	V1.3: added extension making for NEMO V3	PJT
20-jun-03	V1.4: added -u flag	PJT
16-dec-03	V1.5: added -l flag, also cloned sbin/mkstarlab	PJT
11-jun-04	V2.4: added -a flag	PJT
.fi
