.TH BUG 1NEMO "6 March 1989"
.SH NAME
bug \- add bug reports to NEMO
.SH SYNOPSIS
\fBbug\fP
.SH DESCRIPTION
\fBbug\fP is an interactive shell script which allows you to enter one line descriptions
of a bug in NEMO. The program \fIbugs(1NEMO)\fP can be used to scan
these reports.
.PP
After the one line description is entered, the user can send this bugreport,
and optionally some more comments, to a specific e-mail address, using 
\fImail(1)\fP.
.SH SEE ALSO
bugs(1NEMO)
.SH FILES
.nf
.ta +3.0i
~/src/nemo/news   	sources
~/bugs             	bug reports directory
.fi
.SH AUTHOR
Peter Teuben
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.5i
6-Mar-89	created         	PJT
.fi
