.TH OTHER 8NEMO "22 April 2021"
.SH NAME
other \- other N-body codes
.SH DESCRIPTION
There are many more N-body codes than are (allowed to be) included
with NEMO. Here you can find some popular codes, and the list in ASCL
may also include code that are included here yet.
.PP
We also document a few other codes frequently used with NEMO
.SH NBODY CODES
.nf
.ta +1i
amiga		http://popia.ft.uam.es/AMIGA/index.html
ART
arepo   	https://gitlab.mpcdf.mpg.de/vrs/arepo
bonsai		https://github.com/treecode/Bonsai
ChaNGa		http://faculty.washington.edu/trq/hpcc/tools/changa.html
cube		https://github.com/yuhaoran/CUBE
cube3pm		https://github.com/jharno/cubep3m
enzo		https://github.com/enzo-project
fargo3d		http://fargo.in2p3.fr/
fastpm		https://github.com/fastpm/fastpm
gadget2  	https://wwwmpa.mpa-garching.mpg.de/gadget/
gadget4 	https://gitlab.mpcdf.mpg.de/vrs/gadget4
galaxy		http://www.physics.rutgers.edu/galaxy/
gasoline	https://gasoline-code.com/  https://github.com/N-BodyShop/gasoline
gracos		http://www.gracos.org/
gravidy		https://gravidy.xyz/
hnbody
HUAYNO		https://github.com/amusecode/amuse
nbody6tt
openSPH		https://gitlab.com/sevecekp/sph
petar		https://github.com/lwang-astro/PeTar
pkdgrav3	https://bitbucket.org/dpotter/pkdgrav3/src/master/
pycola		https://bitbucket.org/tassev/pycola/src/master/
ramses		https://bitbucket.org/rteyssie/ramses/src/master/
rebound		https://github.com/hannorein/rebound
tpm
vine		http://www.usm.lmu.de/people/mwetz/Overview.html
.fi
.SH
.SH OTHER CODES
.nf
.ta +1i
bbarolo		https://bbarolo.readthedocs.io/en/latest/
.fi
.SH "SEE ALSO"
programs(8NEMO), index(1NEMO)
.PP
https://ascl.net
.SH AUTHOR
Peter Teuben
.SH "UPDATE HISTORY"
.nf
.ta +1i +4i
22-apr-2021	created!man
PJT
.fi
