.TH SBATCH_NEMO 8NEMO "21 September 2022"

.SH "NAME"
sbatch_nemo.sh \- simple sbatch frontend for NEMO scripts

.SH "SYNOPSIS"
.PP
.nf
\fBsbatch_nemo.sh -r runfile\fI args ...\fP
\fBsbatch_nemo.sh -x scriptfile\fI args ...\fP 
.fi

.SH "DESCRIPTION"
\fBsbatch_nemo.sh\fP is a simple frontend that can make it easier to
submit an existing script, or series of commands from a run-file,
to a SLURM based system using \fIsbatch(1)\fP.
.PP
Some flexibility is allowed by using a local \fBsbatch_nemo.rc\fP parameter file
in which the following parameters can be modified (the defaults are listed here):
.nf

#                                        probably don't change this
runid=$$
#                                        prefix to run
prefix="/usr/bin/time xvfb-run -a"
#                                        sbatch run file
run=run_$runid.sh
#                                        max sbatch time 
tmax=04:00:00
#                                        max memory used
mem=16G

.fi

.SH "CAVEAT"
The current version only allows for single core codes.

.SH "EXAMPLES"

Here is a single explicit NEMO command
.nf

  % sbatch_nemo.sh -x $NEMO/scripts/csh/mkmh97.sh run=run_bench yapp=ps
  run_472742.sh      - use scancel JOBID to kill this one, JOBID is:
  Submitted batch job 40887

.fi
This will have created a file \fBrun_472742.sh\fP that was submitted with \fIsbatch(1)\fP, and
a logfile \fBslurm-40887-run_472742.sh.out\fP
.PP
This benchmark took:
.nf
.ta +2i
   zaratan	9.50user 0.22system 0:13.38elapsed 72%CPU   (on scratch) [AMD EPYC 7763]
   t480		13.07user 0.19system 0:13.17elapsed 100%CPU [i7-8550U]
   dl5420	7.54user 0.09system 0:07.64elapsed 99%CPU [i7-1185G7]
.fi

.SH "SEE ALSO"
sbatch(1), slurm(1), mkrunfile(8NEMO)

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.5i +5.5i
21-sep-2022	man written		PJT
.fi
