.TH SOFTWARE 8NEMO "3 June 1988"
.SH NAME
software \- list of things which need improvements
.SH AUTHOR
Peter Teuben
.SH "LIST OF SOFTWARE"
.nf
.ta \w'vtimes'u+6n +\w'vtimes'u+10n +\w'vtimes'u+10n +\w'vtimes'u+10n
\fIName\fP	\fIAppears on Page\fP	\fIDescription\fP	\fIStatus\fP	\fIPerson Responsible\fP
.ta +1.0i +1.0i +2.5i +0.4i	
.sp 5p
snapshot	??        	color of particles      	0	Barnes
max        	??          	mode analysis:            	3	Teuben
stat       	stat.1*   	density maxima           	3	Teuben
libJ.a		??       	cbrt() and rint() absent
.fi
.SH STATUS
.nf
.ta +1.0i
0	non-existent but needed
1	planning
2	coding
3	debugging
4	test-phase, available in NEMO directory
5	working
6	needs improvement
.fi
.SH "UPDATE HISTORY"
.nf
.ta +2.0i
12-feb-87	created (PJT)
16-mar-87	updated (PJT)
