.TH SUPERBOX PROGRAMS 8NEMO "18 March 2006"
.SH NAME
superbox programs \- list of currently available in superbox
.SH DESCRIPTION


.SH "16. CODE"
.nf
.ta +2.0i
.nf
super	integrator
.fi
.SH "16. DATA"
.nf
.ta +2.0i
.nf
adcontour	create isophots for sm
doitall		(idtens)
dreh		(drehimp) angular momentum
enconter	calculate distances between 2 clusters during an encounter and merger
energie   
fesc		find escapers
massbins	radial mass distribution
mcontour	isophot plots for sm
merger		calculate distances between the clusters
rmhead		remove header-data from *.CONT
rot3   
scontour   
treeconv
.fi
.SH "16. OUTPUT"
.nf
.ta +2.0i
adjbh		readout black hole data
adj_d		
adj_h   
adj_i   
dbh		write distance between black hole and galaxy centre
doitall		
dtens 
header		reads the *.HEAD file
itens   
rbh		readout black hole data
.fi
.SH "16. SETUP"
.nf
.ta +2.0i
aconc3		connects two or more .CONT files to simulate more than one galaxy with SUPERBOX
background	setup a homogeneous background
cdis3		generate a globular cluster distribution following  rho(r) propto (Rc + r)^alpha
define		
discnew		set up an exponential disc in an analytical halo no bulge is included (from magalie)
fornax3		NFW/...
galaxy		isothermal halo and disk (Hernquist method)
gluecl		clue 100 cluster together to one super-cluster but 1 object for SUPERBOX
hern6		hernquist profile
homsph		homogeneous sphere
iso5		lowered isothermal sphere
jeans7v		homogeneous sphere for cosmology
mcluster	
ncont		create a CONT-file out of a star-sample
newgrid		
nfw6		Navarro Frenk & White profile
plrot		plummer sphere with rotation
pluascii	plummer sphere in physical units for SUPERBOX
plummer		plummer sphere in physical units for SUPERBOX
plumnew		plummer sphere
two2		homogeneous sphere for cosmology
ubc7		homogeneous sphere
.fi
.SH "SEE ALSO"
.nf
programs(8NEMO)
.fi
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i 
16-Mar-06	created    	PJT

.fi
