#! /bin/bash
#
#   typical use for the benchmark:
#          ../gadget2snap_all snap.all snapshot_*
#
#   the crazy csf selection is only needed for some NEMO tools that don't like
#   it when history is embedded.....  

out=$1
shift

for g in $*;
do
    gadgetsnap $g - | csf - - SnapShot >> $out
done	 
 
