.TH INTRO LNEMO "18 January 1998"
.SH NAME
intro \- introduction to \fIlocal\fP NEMO tools
.SH DESCRIPTION
This section describes local programs and tools. They are sometimes
useful to keep within NEMO, but do not obey the NEMO
user interface rules, and are often public domain programs
which we use. Not all programs listed here are actually still
available from within NEMO and you may have to hunt them down
on internet.
.SH HISTORY
.nf
.ta +1i
14-nov-93	Document created - pjt
