#! /bin/csh
#
# remove $FALCONBIN from PATH
#
if ($?FALCONBIN) then
  set tmp=()
  foreach p ($path)
    if ($p != $FALCONBIN) then
      set tmp=($tmp $p)
    endif
  end
  set path=($tmp)
  rehash
  echo "$FALCONBIN removed from search path"
endif

# remove all FALCON related enviroment variables
unsetenv FALCONLIB
unsetenv FALCONBIN
unsetenv FALCON
if ($?FALCONACC) then
  unsetenv ACCPATH
  unsetenv FALCONACC
endif
if ($?FALCONMAN) then
  unsetenv MANIPPATH
  unsetenv FALCONMAN
endif

unalias NOclaf

# end
