#! /bin/csh
#

# remove $FALCONBIN from PATH
if ($?FALCONBIN) then
  set tmp=()
  foreach p ($path)
    if ($p != $FALCONBIN) then
      set tmp=($tmp $p)
    endif
  end
  set path=($tmp)
  rehash
  echo "$FALCONBIN removed from search path"
endif

# remove $WDUTILSLIB from PATH
if ($?WDUTILSLIB) then
  setenv LD_LIBRARY_PATH `echo $LD_LIBRARY_PATH | perl -pe "s[$WDUTILSLIB][]g;"`
endif

# remove $FALCONLIB from PATH
if ($?FALCONLIB) then
  setenv LD_LIBRARY_PATH `echo $LD_LIBRARY_PATH | perl -pe "s[$FALCONLIB][]g;"`
endif

# remove all FALCON related enviroment variables
unsetenv FALCONLIB
unsetenv FALCONBIN
unsetenv FALCON
if ($?FALCONACC) then
  unsetenv ACCPATH
  unsetenv FALCONACC
endif
if ($?FALCONMAN) then
  unsetenv MANIPPATH
  unsetenv FALCONMAN
endif

unalias NOclaf

# end
