# -*- makefile -*-
################################################################################
#
# Makefile for the falcON project
#
################################################################################

install		: TestGrav gyrfalcON

makepublic 	:= Makefile make.defs make.public

include make.defs
include make.public

################################################################################
