#! /bin/bash
#
#  this bug has got to be the mother of all bugs... (sep 2022)
#  * intel bugs out, AMD seems ok
#  * just -g compilation triggers bug faster
#  * extra filler in node(ptr) didn't solve it
#  ? zeno's treecode has similar header, will it crash too?

set -e
n=100

if [ ! -e p10 ]; then
   mkplummer p10 10
fi

# ensure local install still works
make clean install
echo "###  Test compile ok"

for i in $(seq $n); do
    echo iteration compile $i
    # just compile the code locally doesn't seem to trigger the bug,
    # the whole (?) library needs a rebuild
    # 1. => no bug
    #make clean install > /dev/null 2>&1
    # 2. => bug is triggered
    (cd $NEMO; make build2a build3) > /dev/null 2>&1
    # 3. => no bug
    #(cd $NEMO; make build2a) > /dev/null 2>&1
    #make clean install > /dev/null 2>&1
    #
    echo iteration run $i
    #hackcode1 p10 . fcells=4 tstop=0  debug=3
    hackcode1 tstop=0 debug=3
done

echo Seems ok after n=$i
