# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

TARGETDEPS += src/../bin/glnemo 
CONFIG += debug \
          warn_on \
          qt 
TEMPLATE = subdirs 
SUBDIRS += src 
