default:
	@echo "Re-generating  Makefile"
	qmake
	@echo "Compiling....."
	make -f Makefile

install:
	@echo "Re-generating  Makefile"
	qmake
	@echo "Compiling....."
	make -f Makefile
	@echo "Installing...."
	make -f Makefile install

clean:
	make -f Makefile clean
