#! /usr/bin/env bash
#
# How to Install the Boost Library in C++ on Ubuntu or any other Linux Distribution
#  https://trendoceans.com/install-boost-library-for-c/

#   sudo apt install libboost-all-dev

#   but if you MUST do it from source, here's the recipe
#   on a fast machine this takes about 2 mins

v=1_81_0   # dec-2022
v=1_86_0   # aug-2024
w=https://boostorg.jfrog.io/artifactory/main/release/%s/source/boost_%s.tar.gz


#https://github.com/boostorg/boost/tags

cd $NEMO/local


vv=$(echo $v | sed s/_/./g)
url=$(printf $w $vv $v)
echo url=$url
tgz=$(basename $url)

if [ ! -e  $tgz ]; then
    wget $url
else
    echo "Reusing existing $tgz"
fi



tar xf $tgz
cd boost_$v

# --with-toolset
./bootstrap.sh --prefix=$NEMO/opt/

./b2
./b2 install

echo boost $v `date` >> $NEMO/opt/mknemo.log
