#! /usr/bin/env bash
#
# How to Install the Boost Library in C++ on Ubuntu or any other Linux Distribution
#  https://trendoceans.com/install-boost-library-for-c/

#   sudo apt install libboost-all-dev

#   but if you MUST do it from source

v=1_81_0   # dec-2022
v=1_86_0   # aug-2024
w=https://boostorg.jfrog.io/artifactory/main/release/%s/source/boost_%s.tar.gz


#https://github.com/boostorg/boost/tags

cd $NEMO/local


vv=$(echo $v | sed s/_/./g)
url=$(printf $w $vv $v)
echo url=$url

if [ ! -e  $url ]; then
   wget $url
fi

tgz=$(basename $url)


tar xvf $tgz
cd boost_$v

# --with-toolset
./bootstrap.sh --prefix=$NEMO/opt/

./b2
./b2 install

echo boost $v `date` >> $NEMO/opt/mknemo.log
