#! /bin/bash

# version is hidden in the filename
version=3.47
wget=wgetc

for arg in $*; do
  export $arg
done

cd $NEMO/local
$wget  http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio_latest.tar.gz

tar zxf cfitsio_latest.tar.gz
cd cfitsio-*
./configure --prefix=$NEMO/opt
make -j
make install


echo Installed version=$version
