#! /bin/csh -f
#
# DICE : initial conditions for galaxies
# See also:    https://bitbucket.org/vperret/dice
#
#

set dir = $NEMO/usr/dice
set url = https://bitbucket.org/vperret/dice

if (! -e $dir) then
  mkdir -p $dir
  cd $dir
  git clone $url
else
  cd $dir
  git pull
endif

mkdir -p build
cd build
#cmake -DCMAKE_INSTALL_PREFIX:PATH=$NEMO/opt ..
#cmake -DCMAKE_INSTALL_PREFIX=$NEMO ..
cmake -DENABLE_THREADS=ON -DCMAKE_INSTALL_PREFIX=$NEMO/opt ..
make
make install
