#! /bin/bash
#
#  this is still the private falcON2
#

url=git@bitbucket.org:WalterDehnen/falcon.git
url=git@bitbucket.org:astroteuben/falcon2.git
url=git@bitbucket.org:peter_teuben/falcon.git     # during development
dir=falcon2
branch=master
branch=autoconf                                   # during development


echo "falcON2: using url=$url and git branch=$branch"

cd $NEMO/local
if [ ! -e $dir ]; then
  git clone $url $dir
  cd $dir
  git remote add upstream git@bitbucket.org:WalterDehnen/falcon.git
else
  cd $dir
  git pull
fi
git checkout $branch

#   only for linux for now
if [ ! -e tbb ]; then
  echo "TBB not present, grabbing the linux one"
  wget https://github.com/uxlfoundation/oneTBB/releases/download/v2020.3/tbb-2020.3-lin.tgz
  tar zxf tbb-2020.3-lin.tgz
fi

./configure
source falcon_start.sh


make -C utils2 inc/cachesize.h
make -C h5pp
make inc/utils inc/kepler inc/h5pp
make clean
make -j 4
