#! /bin/bash
#

version=3.3.8
wget=wgetc

for arg in $*; do
  export $arg
done
    
cd $NEMO/local
$wget http://www.fftw.org/fftw-$version.tar.gz

tar zxf fftw-$version.tar.gz
cd fftw-$version
./configure --prefix=$NEMO/opt
make -j
make install

echo Installed version=$version
