#! /bin/csh -f
#
# a quick hack       - June 2009
# added cmake option - Jan 2012
# for QT5            - Mar 2014 
# 
# ubuntu12 :    qt4-qmake libqt4-dev
# fedora17:     qt-devel   
#
# @todo:   did not clean up e.g. glnemo2/utils/lib/unix/debug/libutils.a

set dir=$NEMO/usr/jcl/glnemo2
set sys=`uname -s`
set cmake=0

# for linux
set args=""

if ($sys == Darwin) then
  # for mac
  set args="-spec macx-g++"
endif


# for some implementations it may be called 'qmake'
set qmake=qmake-qt4

if (-e $dir) then
  if ($cmake) then
    echo "WARNING: using new experimental CMAKE install for QT5"
    if ($?QTDIR5 == 0) setenv QTDIR5 /usr
    cd $dir/build
    if (-e Makefile) make clean
    cmake ..
    make
    make install
  else
    cd $dir
    $qmake -recursive $args
      if ($status) then
      echo "It appears as if the Qt library , or at least the development"
      echo "package, has not been installed on your system."
      exit 1
    endif
    make
    # hopefully only 1 subdir in bin
    # pre leiden release:   cp bin/*/glnemo2.debug $NEMOBIN/glnemo2
    make install
  endif
else
    echo mknemo.d: $dir does not exist
endif

