#! /bin/csh -f
#
# a quick hack   - June 2009
#

set dir=$NEMO/usr/jcl/glnemo2
set sys=`uname -s`

# for linux
set args=""

if ($sys == Darwin) then
  # for mac
  set args="-spec macx-g++"
endif


# for some implementations it is called 'qmake'
set qmake=qmake-qt4


if (-e $dir) then
  cd $dir
  $qmake -recursive $args
  if ($status) then
    echo "It appears as if the Qt library , or at least the development"
    echo "package, has not been installed on your system."
    exit 1
  endif
  make
  # hopefully only 1 subdir in bin
  # pre leiden release:   cp bin/*/glnemo2.debug $NEMOBIN/glnemo2
  make install
else
  echo mknemo.d: $dir does not exist
endif

