#! /bin/bash
#
# minimum packages needed:     gsl, cfitsio, wcslib   (ubuntu: libgsl-dev libcfitsio-dev wcslib-dev)
# optional:     
#
# note:   the git compile may not work yet (i didn't for me, still due to latex)
#   needed packages:   texlive-latex-base   texlive-latex-recommended  texlive-bibtex-extra  texlive-pictures

# example of alpha/beta-testing:
#       https://alpha.gnu.org/gnu/gnuastro/gnuastro-0.17.81-1a40.tar.lz
#       tar --lzip -xf gnuastro-0.17.81-1a40.tar.lz 

# version is hidden in the filename, if not, use git
version=0.23    # also uses 'latest' now
wget=wgetc
check=0
url=https://git.savannah.gnu.org/git/gnuastro.git
#  ???  https://github.com/sachinkumarsingh092/gnuastro


for arg in $*; do
  export $arg
done


cd $NEMO/local
if [ $version = "git" ]; then
    if [ ! -d gnuastro-git ]; then
        git clone $url gnuastro-git
	(cd gnuastro-git; ./bootstrap)
    else
	(cd gnuastro-git; git pull)
    fi
else
    $wget  http://ftp.gnu.org/gnu/gnuastro/gnuastro-latest.tar.gz
    tar zxf gnuastro-latest.tar.gz
    version=$(ls -d gnuastro-* | grep -v latest | grep -v git | sed s/gnuastro-//)
fi
   
echo VERSION=$version

cd gnuastro-$version
./configure --prefix=$NEMO/opt
make -j
if [ $check = 1 ]; then
    make check -j
fi
make install


echo Installed version=$version

echo gnuastro $version `date` >> $NEMO/opt/mknemo.log
