#! /bin/bash
#
#   needed for yapp_gnuplot

version=git
url=https://github.com/longradix/gnuplot_i

for arg in $*; do
  export $arg
done


cd $NEMO/local
if [ $version = "git" ]; then
    if [ ! -d gnuplot_i ]; then
        git clone $url 
    else
	(cd gnuplot_i; git pull)
    fi
else
    echo Error, no version $version
fi
   
echo VERSION=$version

cd gnuplot_i
cp gnuplot_i.[ch] $NEMOLIB

echo Installed version=$version

echo gnuplot_i $version `date` >> $NEMO/opt/mknemo.log
