#! /bin/bash
#

version=2.6

cd $NEMO/local



if [ -f $NEMO/tar/gsl-$version.tar.gz ]; then
   ln -s $NEMO/tar/gsl-$version.tar.gz
fi   
if [ ! -f gsl-$version.tar.gz ]; then
   wget ftp://ftp.gnu.org/gnu/gsl/gsl-$version.tar.gz
fi   
tar zxf gsl-$version.tar.gz
cd gsl-$version
./configure --prefix=$NEMO/opt
make -j
make install

echo Installed version=$version
