#! /bin/csh -f
#
#  falcON tools, for the version up to Aug 6, 2006 (nemo 3.2.4)

set dir=$NEMO/usr/dehnen/falcON

if (-e $dir) then
  cd $dir
  (cd ../utils; make clean)
  make -f Makefile.nemo clean nemo_bins
else
  echo mknemo.d: $dir does not exist
endif

