#! /bin/bash
#
#  Install HDF5 within NEMO
#
#
#  25-dec-2019  drafted
#

# if ($?NEMO == 0) set NEMO=`pwd`

version=4.2.14


cd $NEMO/local

if [ -f $NEMO/tars/hdf-$version.tar.gz ]; then
   ln -s $NEMO/tars/hdf-$version.tar.gz
fi   
if [ ! -f hdf-$version.tar.gz ]; then
   wget https://support.hdfgroup.org/ftp/HDF/releases/HDF$version/src/hdf-$version.tar.gz
fi

tar zxf hdf-$version.tar.gz
cd hdf-$version

./configure --prefix=$NEMO/opt
make -j
make install 
