#! /bin/bash
#
#  Install HDF5 within NEMO
#
#
#  25-dec-2019  drafted
#

# if ($?NEMO == 0) set NEMO=`pwd`

version=1.10.6
mversion=1.10


cd $NEMO/local

if [ -f $NEMO/tar/hdf5-$version.tar.gz ]; then
   ln -s $NEMO/tar/hdf5-$version.tar.gz
fi   
if [ ! -f hdf5-$version.tar.gz ]; then
   wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-$mversion/hdf5-$version/src/hdf5-$version.tar.gz    
fi

tar zxf hdf5-$version.tar.gz
cd hdf5-$version

./configure --prefix=$NEMO/opt
make -j
make install 
