#! /bin/bash
#
#  Install HDF5 within NEMO
#
#
#  25-dec-2019  drafted
#  17-mar-2020  wgetc
#

# if ($?NEMO == 0) set NEMO=`pwd`

version=1.10.6
mversion=1.10
wget=wgetc

for arg in $*; do
  export $arg
done
    
cd $NEMO/local
$wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-$mversion/hdf5-$version/src/hdf5-$version.tar.gz    

tar zxf hdf5-$version.tar.gz
cd hdf5-$version

./configure --prefix=$NEMO/opt
make -j
make install 
