#! /bin/bash
#
#  HYPRE: Scalable Linear Solvers and Multigrid Methods
#
#  Villumsen's code needs it
#
#  1-may-2021  drafted
#

# if ($?NEMO == 0) set NEMO=`pwd`

git=1
url=https://github.com/hypre-space/hypre

for arg in $*; do
  export $arg
done

    
cd $NEMO/local


if [ $git == 1 ]; then
    if [ ! -d hypre ]; then
	git clone $url hypre
    fi
    version=git
else
    echo no non-git
    exit 1
fi    

cd hypre
git pull

cd src
./configure --prefix=$NEMO/opt

make clean
make -j
make install

echo hypre $version  `date` >> $NEMO/opt/mknemo.log
