#! /bin/csh -f
#

set dir=$NEMO/usr/kuepper/mcluster

if (! -e $dir) then
  echo "mknemo: $dir does not exist, creating it"
  cd $NEMO/usr/kuepper
  git clone https://github.com/ahwkuepper/mcluster
endif

cd $dir
git pull
make clean mcluster
mv mcluster $NEMOBIN
