#! /bin/bash
#
#   mknemo build helper for montage
#
#


cd $NEMO/local

if [ ! -d Montage ]; then
  git clone https://github.com/Caltech-IPAC/Montage
fi
cd Montage
git pull
version=$(git log -1 --format=%cd)
 
make 
# bizarre, there is no prefix= or make install...
mv bin/* $NEMO/opt/bin/

echo Installed version=$version

echo montage '"'$version'"' `date` >> $NEMO/opt/mknemo.log
