#! /bin/bash
#
# Packages ubuntu:    libfltk1.3-dev   <MESA>

#
# See also
#

version=git
url=https://git.ncsa.illinois.edu/slevy/partiview


for arg in $*; do
  export $arg
done


cd $NEMO/local
if [ $version = "git" ]; then
    if [ ! -d git ]; then
        git clone $url
	cd partiview
    else
	cd partiview
	git pull
    fi
fi
   
echo VERSION=$version

cd src
#   --prefix=$NEMO/opt   doesn't seem to work
./configure 
make 
cp partiview $NEMO/opt/bin


echo Installed version=$version

echo partiview $version `date` >> $NEMO/opt/mknemo.log
