#! /usr/bin/env bash
#
#   note that redis needs -I$NEMO/opt/include/hiredis
#
#   hiredis = minimalistic C library version (this version)
#   redis = full version                     (see notes, but not used here yet)
#
#   On ubuntu the full redis needs:
#          ca-certificates wget dpkg-dev gcc g++ libc6-dev libssl-dev make git cmake
#          python3 python3-pip python3-venv python3-dev unzip rsync clang automake autoconf libtool
#   full build example:
#       export BUILD_TLS=yes BUILD_WITH_MODULES=yes INSTALL_RUST_TOOLCHAIN=yes DISABLE_WERRORS=yes
#       make -j "$(nproc)" all

url=https://github.com/redis/redis
url=https://github.com/redis/hiredis
version=git


cd $NEMO/local
if [ ! -d hiredis ]; then
    git clone $url
    cd hiredis    
else
    cd hiredis
    git pull
fi

mkdir -p build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$NEMO/opt ..

make install

echo hiredis $version `date` >> $NEMO/opt/mknemo.log
