#! /bin/csh -f
#
# a quick hack   - Nov 2010
# converted to uns_projects for the new git based distros
#
#  need:  libboost, libboost-system, libboost-thread
#
# g77:        -lfrtbegin -lg2c
# gfortran:   -lgfortran

set dir=$NEMO/usr/jcl/uns_projects

# for linux
set args=""


if (-e $dir) then
  mkdir -p $dir/build
  cd $dir/build
  cmake ..
  make
  make install 
else
  echo mknemo.d: $dir does not exist
endif

