#! /bin/csh -f
#
# a quick hack   - May 2010
# some changed dir structure   - Jan 2013
#
# g77:        -lfrtbegin -lg2c
# gfortran:   -lgfortran

set dir=$NEMO/usr/jcl/unsio

# for linux
set args=""


if (-e $dir) then
  mkdir -p $dir/build
  cd $dir/build
  cmake ..
  make
  make install 
  # new python stuff (13 march 2014)
  cd ../py
  mkdir -p build
  cd build
  cmake ..
  make
  make install
else
  echo mknemo.d: $dir does not exist
endif

