#! /bin/bash
#

#   version is sadly hidden in the filename
version=7.4
wget=wgetc

for arg in $*; do
  export $arg
done
 
cd $NEMO/local
$wget  ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib.tar.bz2
version=$(tar jtf wcslib.tar.bz2 | head -1 | awk -F/ '{print $1}' | sed s/wcslib-//)

tar jxf wcslib.tar.bz2
cd wcslib-$version
./configure --prefix=$NEMO/opt
make -j
make install

echo Installed version=$version

echo wcslib $version `date` >> $NEMO/opt/mknemo.log
