#! /bin/csh
#
# source this file to generate cachesize.h
#
echo ///
echo /// auto generated on `date`
echo /// don\'t edit this file but file \"make_cachesize\"
echo ///
echo '#ifndef' WDutils_included_cachesize_h
echo '#define' WDutils_included_cachesize_h
echo
echo namespace WDutils {
echo

if($?VENDOR && $VENDOR == apple) then
  echo '#define' LEVEL1_DCACHE_LINESIZE `sysctl -an hw.cachelinesize`
else
  echo '#define' LEVEL1_DCACHE_LINESIZE `getconf LEVEL1_DCACHE_LINESIZE`
endif

echo
echo '  'static const std::size_t sizeof_cache_line = LEVEL1_DCACHE_LINESIZE';'
echo
echo } // namespace WDutils
echo '#endif'

#end
