.TH ACS 1NEMO "30 December 2019"

.SH "DESCRIPTION"
\fBACS\fP (The Art of Computational Science) is an
effort by Piet Hut and Jun Makino how to build a
computational lab.
.PP
The initial version was written in C++ (after an earlier start in C),
but another version was written in Ruby.
.PP
As an example, within NEMO we have adopted their \fInbody_sh1(1NEMO)\fP 
hermite integrator with shared but variable time step. This version
was written in C++.

.SH "SEE ALSO"
nemo(1NEMO), zeno(1NEMO), nbody_sh1(1NEMO)

.SH "AUTHOR"
Piet Hut, Jun Makinco

.SH "FURTHER INFORMATION"
.nf
http://www.artcompsci.org/
.fi
