.TH ADDGRAVITY 1NEMO "12 May 2004"
.SH NAME
addgravity \- adds pot & acc to a snapshot using falcON = Force ALgorithm with Complexity O(N)
.SH SYNOPSIS
\fBaddgravity\fP [parameter=value]
.SH DESCRIPTION
No description available. This manual page was created by mkman
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
input file [???]     
.TP 20
\fBout=\fP
output file [???]     
.TP 20
\fBtimes=\fP
time range [all]     
.TP 20
\fBeps=\fP
softening length [0.05]     
.TP 20
\fBkernel=\fP
softening kernel [1]     
.TP 20
\fBtheta=\fP
tolerance parameter at M=M_tot [0.60]   
.TP 20
\fBNcrit=\fP
max # bodies in un-split cells [6] 
.SH EXAMPLES
.SH SEE ALSO
.SH FILES
.SH AUTHOR
Walter Dehnen
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
.TP 20
06-may-2004 V1.4 for NEMO	WD
.fi
