.TH BADMAN XNEMO "29 June 1989"
.SH NAME
badman \- reference to non-existing documentation
.SH DESCRIPTION
This is a kludge for all things which are not documented in NEMO.
.PP
You have just requested documentation that should have existed,
but does not exist yet. File a bug report using the NEMO bug command.
.SH HISTORY
.ta +1.0i +3.0i
29-Jun-89	created  	(PJT)
.fi
