.TH BADNEWS 1NEMO "19 June 1989"
.SH NAME
badnews \- display bad news for user
.SH SYNOPIS
\fBbadnews\fP
.SH DESCRIPTION
\fBbadnews\fP displays some bad news to the user. Installation dependant.
It may have logical links coming to it from various files which do not
work for some reason on the system that you are using. 
.SH "SEE ALSO"
nemo(1NEMO)
.SH FILES
.nf
.ta +2i
~/src/pjt/clib	badnews.c badnews.1
.fi
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4i
19-jun-89	V1.0: created	PJT
.fi
