.TH CCD2VEL 1NEMO "28 April 2017"
.SH NAME
ccd2vel \- convert map of wave/freq/velocities to doppler velocities
.SH SYNOPSIS
\fBccd2vel\fP [parameter=value]
.SH DESCRIPTION
This program converts an input map to doppler velocity map. The input
units can be in wavelenth (restwave is needed), frequency (restfreq is needed)
or one of three doppler velocity frames of reference (radio, optical, relativistic).
The output map will be in one of the doppler velocity frames of reference
 (radio, optical, relativistic). Units are normally km/s.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given
.TP 20
\fBin=\fP
Optional input image file []   
.TP
\fBout=\fP
Output image file []    
.TP
\fBfrom=\fP
Frame of reference (relativistic, radio, optical) [rel] 
.TP
\fBto=\fP
Frame of reference (relativistic, radio, optical) [rel] 
.TP
\fBrestwave=\fP
Rest wavelength, in the units of the map.  
Only one of restwave of restfreq can be used.
.TP
\fBrestfreq=\fP
Rest frequency, in the units of the map
.TP
\fBclip=\fP\fImin,max\fP
Clipping of output (none, or two values needed)
.TP
\fBunits=km/s\fP
Desired output units (km/s, m/s) [km/s]  
.SH EXAMPLES
Here is how one converts a fits cube in optical wavelengths to a relatistic velocity field:
.nf
fitsccd NGC2347.V500.rscube.fits  -|ccdsub - - z=1435:1485|ccdmom - - mom=3|ccd2vel - vel-Ha-3.ccd opt rel 6562.80 clip=4000,4800
.fi
and here
.nf
NGC2347.VoptFromHa.fits - | ccd2vel - NGC2347.VrelFromHa.ccd opt rel
.fi
.SH SEE ALSO
ccdsky(1NEMO), ccdmath(1NEMO), fitsccd(1NEMO)
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
27-Apr-17	V0.3 Created	PJT
.fi
