.TH CCDBENCH 1NEMO "19 March 2024"

.SH "NAME"
ccdbench \- benchmark taking moments along an axis of an image

.SH "SYNOPSIS"
\fBccdbench\fP [parameter=value]

.SH "DESCRIPTION"


.SH "PARAMETERS"
.so man1/parameters
.TP 20
\fBin=\fP
Input image file [???]    
.TP
\fBorder=\fP
Order to loop over cube, where the last
.TP
\fBiter=\fP
How often to loop [1]   

.SH "EXAMPLES"

.SH "SEE ALSO"
snapbench(1NEMO)

.SH "FILES"
src/image/misc

.SH "AUTHOR"
Peter Teuben

.SH "HISTORY"
.nf
.ta +1.5i +5.5i
18-mar-2024	Created ...	PJT
.fi
