.TH CCDBLOB 1NEMO "30 May 2025"

.SH "NAME"
ccdblob \- properties of a blob in an image

.SH "SYNOPSIS"
\fBccdblob\fP [parameter=value]

.SH "DESCRIPTION"
\fBccdblob\fP is a poor man's source extractor and 
computes some properties of a blob ("star") in an image. With given rough pixel coordinates
and a box size, it will determine the peak, shape and flux of the blob, assuming the background signal (box
needs to be big enough for this) is well characterised by the median value. This current algorithm thus does not
work in crowded fields.
.PP
The current draft version is based off \fIccdshape(1NEMO)\fP and thus inherits some keywords and output
that may disappear or change meaning.
.PP
Pixel coordinates are 1-based.
.PP

.SH "PARAMETERS"
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input NEMO image file
.br
No default.
.TP
\fBpos=\fP\fIx,y\fP
(x,y) center of the \fBbox\fP. Positions are 1-based integers
With the special value \fBpos=max\fP the location of the maximum in the image is used.
.br
Default is center of image. 
.TP
\fBbox=\fP
Box size to use around \fBpos\fP.
.br
Default: 32
.TP
\fBclip=\fP
Use only values above \fBclip\fP. 
.br
Default will use all values within the box.
.TP
\fBwcs=t|f\fP
Use WCS of the cube (otherwise use pixel coordinates 1..N).
.TP
\fBradecvel=t|f\fP
Split the RA/DEC from VEL
.br
[f]  
.TP
\fBweight=t|f\fP
Weigh moments of inertia by intensity?
.br
[t]    
.TP
\fBcross=\fP
Use cross correlations between X and Y to...
.TP
\fBpeak=N\fP
Find the N-th peak. Only used if \fBpos\fP is not given.
For \fBpeak=0\fP the center of the map is used, otherwise
it will find the N-th peak.
.br
Default: 1
.br
\fInot implemented yet\fP


.SH "EXAMPLES"
Analysing a Betelgeuse images from an all-sky camera:
.EX

% file=ASC/MASN-01/archive/201601/20160102/IMG00700.FIT
% fitsccd $file - | ccdblob - 724,305
 BLOB 726 305  724.573 305.38 32   6546 42731 139121

.EE
Where the BLOB line lists the peak position (pixels are 1-based), followed
by an intensity weighted position, the box size around the estimated center,
followed by the median, peak and total blob flux (corrected for the median
background).
.PP
An example of creation a gaussian blob with a given Signal/Noise (ns=) and running it
through ccdblob:
.EX

sn=10
ccdgen - gauss 1,3 128,128  | ccdgen - noise 0,1/$sn in=- seed=123 | ccdblob -

Npoints:    1024
Box:        32
DataMinMax: -0.278395 1.07276
Min at:     77 51 (1 based)
Max at:     66 65
Mean:       0.0541314
Median:     -0.0910571
DataSum:    55.4305
Flux:       148.673
ImSize:     128 128 1
Center:     63.7424 62.9733 0 [wcs]
BLOB:  66 65  63.7424 62.9733 32   -0.0910571 1.07276 148.673
        e_x:     1.00000     0.97453    -0.22426     0.00000    90.0  -13.0
        e_y:     1.00000     0.22426     0.97453    -0.00000   -90.0   77.0
        e_z:     1.00000     0.00000     0.00000     1.00000     0.0    0.0
      qpole:    20.25961     0.97453    -0.22426     0.00000
                 1.23397     0.22426     0.97453     0.00000
                 0.00000     0.00000     0.00000     1.00000
a,b:  4.50107 1.11084
inc:  75.712 (meaningless without radecvel)
pa:   77.0407 (meaningless without radecvel)

.EE

.SH "SEE ALSO"
ccdshape(1NEMO), ccdstat(1NEMO), image(5NEMO)
.nf
https://github.com/perwin/imfit
.fi
.SH "FILES"
src/image/misc/ccdblob.c

.SH "AUTHOR"
Peter Teuben

.SH "HISTORY"
.nf
.ta +1.25i +4.5i
15-feb-2020	V0.1 Created	PJT
14-feb-2025	V0.3 fix boxsize when no pos given	PJT
30-may-2025	V0.5 allow pos=max	PJT
.fi
