.TH CCDCROSS 1NEMO "11 April 2022"

.SH "NAME"
ccdcross \- cross correlate images with a reference image

.SH "SYNOPSIS"
\fBccdcross\fP [parameter=value]

.SH "DESCRIPTION"
\fBccdcross\fP finds the optimal offset one (or more) images and a reference image based on the
cross-correlation between two images.  By selecting a specific \fBcenter=\fP and
half \fBbox=\fP size, one can focus on a specific area, assuming the offset is less than
the box-size.

.SH "PARAMETERS"
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input image files, first image is the reference image. At least two images need
to be given. No default.
.TP
\fBout=\fP
Output cross image [???]    
.TP
\fBcenter=\fP
X-Y Reference center (0-based pixels) []  
.TP
\fBbox=\fP
Half size of correlation box. The output image is forced to have an odd pixel size, 2*box+1.
.TP
\fBclip=\fP
Only use values above this clip level []
.TP
\fBbad=\fP
bad value to ignore [0]   

.SH "EXAMPLES"

Here two gaussian shaped sources with noise are created with a small 1 pixel offset from
each other.

.nf

    ccdgen "" - gauss 1,2 size=128,128 center=64,64  | ccdgen - g64 noise spar=0,0.05 
    ccdgen "" - gauss 1,2 size=128,128 center=65,65  | ccdgen - g65 noise spar=0,0.05
    ccdcross g64,g65 shift.ccd box=16
    ...
    ### nemo Debug Info: max 12.2081 @ 17 17
    ### nemo Debug Info: X,Y mean: -0.00904199 -0.00432744
.fi

.SH "SEE ALSO"
ccdmath(1NEMO), image(5NEMO)

.SH "FILES"
src/image/mics	ccdcross.c

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.5i +5.5i
11-Apr-2022	V0.1 Created	PJT
.fi
