.TH CCDCMP 1NEMO "29 September 2001"
.SH NAME
ccdcmp \- compare two images/cubes using Student T and F test for mean and variance 
.SH SYNOPSIS
\fBccdcmp\fP [parameter=value]
.SH DESCRIPTION
\fBccdcmp\fP ...
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin1=\fP
First image dataset [???]    
.TP
\fBin2=\fP
Second image dataset [???]    
.TP
\fBxmin=\fP
In case minimum used (need both minmax) []
.TP
\fBxmax=\fP
In case maximum used (need both minmax) []
.TP
\fBbins=\fP
Bins (number in min-max range, or boundaries) [16]
.SH EXAMPLES
.SH SEE ALSO
.SH FILES
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
29-Sep-01	V0.3 Created 	PJT
.fi
