.TH CCDCROSS 1NEMO "18 April 2024"

.SH "NAME"
ccdcross \- cross correlate images with a reference image

.SH "SYNOPSIS"
\fBccdcross\fP [parameter=value]

.SH "DESCRIPTION"
\fBccdcross\fP finds the optimal offset one (or more) images and a reference image based on the
cross-correlation between two images.  By selecting a specific \fBcenter=\fP and
half \fBbox=\fP size, one can focus on a specific area, assuming the offset is less than
the box-size.

.SH "PARAMETERS"
.so man1/parameters
.TP 20
\fBin=\fP\fIref,im1,...\fP
Input image files, first image is the reference image. At least two images need
to be given. No default.
.TP
\fBout=\fP\fIim\fP
Output cross image. No default.
.TP
\fBcenter=\fP\fIx0,y0\fP
X-Y Reference center around which a box (see \fBbox=\fP below) is taken.
The are 0-based integer pixels. By default the center of the image
is used.  Default: center of first input image.
.TP
\fBbox=\fP\fIb2\fP
Half size of correlation box. The output image is forced to have an odd pixel size, 2*box+1.
The shift between the images should not exceed \fBbox\fP.
By default half the mapsize is used. 
.TP
\fBclip=\fP\fIc\fP
Only use values above this clip level. By default values are not clipped.
.TP
\fBbad=\fP\fIb\fP
bad value to ignore. By default there is no bad value recognized.

.SH "CAVEAT"
Only 2D images are handled.
.PP
The WCS is ignored, 0-based pixel coordinates are reported.
.PP
Images should ideally be the same size, but nothing will stop the program from
running off without that. The user is then responsible for computing the true offsets
as all bets are off.

.SH "EXAMPLES"

Here two gaussian shaped sources with noise are created with a small 1 pixel offset from
each other.

.EX

    ccdgen - gauss 1,2 size=128,128 center=64,64 | ccdgen g64 noise spar=0,0.05  in=-
    ccdgen - gauss 1,2 size=128,128 center=65,65 | ccdgen g65 noise spar=0,0.05  in=-
    ccdcross g64,g65 shift.ccd box=16
    ...
    ### nemo Debug Info: Max cross 13.968 @ 16 16
    ### nemo Debug Info: X,Y mean: 0.393391 0.412221
    ### nemo Debug Info: X,Y sig:  1.7885 1.76623
    ### nemo Debug Info: Center at: 0.393391 0.412221
    0.393391 0.412221  0.393391 0.412221  16 16  13.968

.EE

.SH "SEE ALSO"
ccdmath(1NEMO), image(5NEMO)

.SH "FILES"
src/image/mics	ccdcross.c

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.5i +5.5i
11-Apr-2022	V0.1 Created	PJT
3-aug-2023	V0.2 fix absolute coordinate	PJT
18-apr-2024	V0.3 add peak flux in correlation map	PJT
.fi
