.TH CCDFLIP 1NEMO "22 February 1997"
.SH NAME
ccdflip \- flip an image
.SH SYNOPSIS
\fBccdflip\fP [parameter=value]
.SH DESCRIPTION
\fBccdflip\fP flips the coordinates of one of the principle axes
(X, Y or Z) of an image.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input image file     
.TP
\fBout=\fP
Output file      
.TP
\fBflip=\fP
Flip in x,y or z?   
.SH EXAMPLES
.SH SEE ALSO
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
22-Feb-97	man written	PJT
.fi
