.TH CCDGEN 1NEMO "5 January 2005"
.SH NAME
ccdgen \- create or add objects to an image
.SH SYNOPSIS
\fBccdgen\fP [parameter=value]
.SH DESCRIPTION
\fBccdgen\fP creates or modified images by 
adding simple parameterized two-dimensional objects. For arbitrary
expressions use \fIccdmath(1NEMO)\fP instead. 
.PP
An odd feature is that the objects can be added as if they are
in a "galactic" disk with given inclination and position angle. The
default is a "face-on" view. No corrections for brightness
due to inclination are made however.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input file (optional) to be added to the output file. Default: none,
map is generated.
.TP
\fBout=\fP
Output file, in standard \fIimage(5NEMO)\fP format. No default.     
.TP
\fBobject=\fP
Object type. Valid are flat, exp, gauss, bar, spiral, noise. See below for
an explanation and their parameters. Default: flat
.TP
\fBspar=\fP
Parameters for this object. The first parameter is often the peak 
value, and the second one a scale length. Some object have more
complex geometries and require more parameters. The meaning
of the peak value can be modified by setting \fBtotflux=t\fP
(see below). The defaults are defined per object, but
are typically 1,1...
.TP
\fBcenter=\fP
Center of object in pixels. The lower left hand
pixel is counted as (0,0) here. Default: mapcenter.
.TP
\fBsize=\fP
Mapsize. It is allowed to have a different size in X and Y.
.TP
\fBcell=\fP
Cellsize [1]      *not used yet*
.TP
\fBpa=\fP
Position Angle of disk in which object lives. Counted positive
starting at North through East in the standard astronomical
fashion. Default: 0
.TP
\fBinc=\fP
Inclination Angle of disk in which object lives. 0 is face on.
Default: 0
.TP
\fBtotflux=t|f\fP
If set to true, the amplitude (always the first parameter in
\fBspar\fP is interpreted as the total integrated intensity
instead of the peak value of the object
.TP
\fBcrpix=\fP
Override/Set crpix (1,1,1) 
.TP
\fBcrval=\fP
Override/Set crval (0,0,0) 
.TP
\fBcdelt=\fP
Override/Set cdelt (1,1,1) 
.TP
\fBseed=\fP
Random seed [0]    
.SH OBJECTS
.nf
.ta +1i +2i
flat	A		A
exp	A.exp(-r/h)	A,h
gauss	A.exp(-r^2/(2h^2))	A,h
bar	A.exp(-r/h)	A,h,e,b   (e=1-minor/major   b=bar position angle w.r.t. disk)
noise	gaussian(m,s)	mean,sigma
spiral  A.exp(-r/h)	A,h,k,p,r0,p0
.fi 
.SH EXAMPLES
Here's how to make a barred galaxy:
.nf
ccdgen out=- object=exp spar=1,40 pa=60 inc=45 size=256 |\\
 ccdgen - bar.ccd object=bar spar=10,6,0.5,70 pa=60 inc=45

.fi
or if you want them to be a bit more astronomical, you'll need to make the units
come out in degrees for the conversion to FITS, viz.:
.nf

ccdgen out=- object=exp spar=1,40/3600 pa=60 inc=45 size=256 cdelt=-1/3600,1/3600 |\\
 ccdgen - - object=bar spar=10,6/3600,0.5,70 pa=60 inc=45 |\\
 ccdfits - bar.fits radecvel=t
.fi
.PP
Spirals are a bit more complex: A and h are the usual peak and exponential scale-length.
k is the wavenumber (related the pitch angles, see also \fImkspiral(1NEMO)\fP), 
p controls the relative width of the spiral (assumed to be cos^2p, thus you 
should set p>1), r0 the starting radius of the spiral (defaults to 0), and p0 the
phase of the spiral at radius r0.
.SH SEE ALSO
ccdmath(1NEMO), image(5NEMO)
.SH FILES
src/image/trans
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
05-Jan-05	V0.1 Created	PJT
.fi
