.TH CCDGEN 1NEMO "5 January 2005"
.SH NAME
ccdgen \- image creation with objects
.SH SYNOPSIS
\fBccdgen\fP [parameter=value]
.SH DESCRIPTION
\fBccdgen\fP creates or modified images by 
adding simple parameterized two-dimensional objects. For arbitrary
expressions use \fIccdmath(1NEMO)\fP instead. 
.PP
An addition feature of this program is that the objects can be added
in a "galactic" disk with given inclination and position angle.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input file (optional) to be added to the
.TP
\fBout=\fP
Output file [???]     
.TP
\fBobject=\fP
Object type []     
.TP
\fBspar=\fP
Parameters for this object []   
.TP
\fBcenter=\fP
Center of object (defaults to mapcenter) in pixels
.TP
\fBsize=\fP
2- or 3D dimensions of map/cube (only if
.TP
\fBcell=\fP
Cellsize [1]      
.TP
\fBpa=\fP
Position Angle of disk in which object lives
.TP
\fBinc=\fP
Inclination Angle of disk in which object lives
.TP
\fBcrpix=\fP
Override/Set crpix (1,1,1) // ignored []  
.TP
\fBcrval=\fP
Override/Set crval (0,0,0) // ignored []  
.TP
\fBcdelt=\fP
Override/Set cdelt (1,1,1) // ignored []  
.TP
\fBseed=\fP
Random seed [0]     
.SH EXAMPLES
.SH SEE ALSO
ccdmath(1NEMO), image(5NEMO)
.SH FILES
src/image/trans
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
05-Jan-05	V0.1 Created	PJT
.fi
