.TH CCDMASK 1NEMO "21 May 2013"
.SH NAME
ccdmask \- image masking
.SH SYNOPSIS
\fBccdmask\fP [parameter=value]
.SH DESCRIPTION
No description available. This manual page was created by mkman
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input file(s), separated by comma's (optional) [???] 
.TP 20
\fBout=\fP
Output file [???]     
.TP 20
\fBclip=\fP
Clip level(s) for each input file [0.0] 
.SH EXAMPLES
.SH SEE ALSO
.SH FILES
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
21-May-13	V0.1 Created	PJT
.fi
