.TH CCDPEAKSTATS 1NEMO "3 May 2016"
.SH NAME
ccdpeakstats \- spectral peak statistics of an image
.SH SYNOPSIS
\fBccdpeakstats\fP [parameter=value]
.SH DESCRIPTION
\fBccdpeakstats\fP looks at all spectra through a cube and for signals above
a clip level determined by \fBsigma=\fP and \fBnsigma=\fP it will compute
the peak signal, mean channel and channel width
within a segment that is deemed
to be "single" line (as determined by \fBminchan=\fP and \fBmaxgap=\fP).
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input image filename [???]    
.TP 20
\fBsigma=\fP
Noise level [???]     
.TP 20
\fBnsigma=\fP
Number of sigma over which line segments are detected.  The cutoff is
determined by \fIsigma*nsigma\fP. Default: 5
.TP 20
\fBminchan=\fP
Min number of channels over cutoff to count. Default: 5
.TP 20
\fBmaxgap=\fP
Max number of channels below cutoff allowed in. Default: 2
.TP 20
\fBx=\fP
Pick an X pixel (0....) for debug one spectrum []  
.TP 20
\fBy=\fP
Pick an Y pixel (0....) for debug one spectrum []  
.TP 20
\fBtab=\fP
If given, print out data values [] 
.SH EXAMPLES
.nf
% ccdpeakstats sample.ccd
#  peak   <channel> FWHM    #channels
0.0232928 562.954   1.95056 7
0.0463414 856.056   3.31661 13
.fi
.SH SEE ALSO
ccdstat(1NEMO)
.SH FILES
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
2-nov-15	V0.1 Created	PJT
.fi
