.TH CCDPPM 1NEMO "17 December 2003"
.SH NAME
ccdppm \- convert image to a PPM file, with optional color cable
.SH SYNOPSIS
\fBccdppm\fP [parameter=value]
.SH DESCRIPTION
No description available. This manual page was created by mkman
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input image filename [???]    
.TP 20
\fBout=\fP
Output PPM filename [???]    
.TP 20
\fBmin=\fP
Minimum overrride []     
.TP 20
\fBmax=\fP
Maximum overrride []     
.TP 20
\fBbad=\fP
Use this as masking value to ignore data
.TP 20
\fBlut=\fP
optional selection of a lut from NEMODAT/lut []
.TP 20
\fBVERSION=\fP
16-dec-03 PJT [1.0]     
.SH EXAMPLES
.SH SEE ALSO
fitstiff(1NEMO)
.SH FILES
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
17-Dec-03	V1.0 Created	PJT
.fi
