.TH CCDPPM 1NEMO "17 December 2003"
.SH NAME
ccdppm \- convert image to a PPM file, with optional color cable
.SH SYNOPSIS
\fBccdppm\fP [parameter=value]
.SH DESCRIPTION
\fBccdppm\fP converts a NEMO image to a 24bit PPM file.
A color table can be optionally added, also in 8bit mode.
.PP
ppm files are probably the most versatile output graphics 
format, since it is very easy to write (no special library
is needed) and they can be easily converted to other formats
(gif, jpg,....) and are understood by most image processing
systems.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input image filename. Must be a \fIimage(5NEMO)\fP. Currently the
3rd dimension is ignored, and for datacubes the first slice is
taken. See \fIccdsub(5NEMO)\fP to select a plane. No default.
.TP
\fBout=\fP
Output PPM filename. No default.
.TP
\fBmin=\fP
Overrride data minimum used in scaling. By default it will look for
the minimum.
.TP
\fBmax=\fP
Overrride data maximum used in scaling. By default it will look for
the minimum.
.TP
\fBbad=\fP
Use this as masking value to ignore data. By default no data is 
considered bad.
.TP
\fBlut=\fP
optional selection of a lut from NEMODAT/lut. Currently the full path
to the file must be given. By default it will be using a grey scale
(red=green=blue).
.TP
\fB8bit=t|f\fP
Force up to 256 discrete colors. This can be useful if you want to convert
the normally 24bit ppms to 8bit images and not 'loose' any colors
in the conversion. 
[\fBfalse\fP].
.SH EXAMPLES
Here is an example to take the 5th plane from a fits file into a 24bit PPM file:
.nf
    % fitsccd cube.fits - | ccdsub - - z=4 | ccdppm - plane4.ppm lut=$NEMODAT/lut/ronekers.lut
.fi
.SH SEE ALSO
fitstiff(1NEMO), lut(5NEMO)
.SH FILES
$NEMODAT/lut   :  repository of \fIlut(5NEMO)\fP color lookup tables.
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
17-Dec-03	V1.0 Created (100 year Wright first flight anniversary)	PJT
.fi
