.TH CCDSHARP 1NEMO "10 January 2012"
.SH NAME
ccdsharp \- enhance/sharpen an image
.SH SYNOPSIS
\fBccdsharp\fP [parameter=value]
.SH DESCRIPTION
Various methods to sharpen/image enhance an image can be tried out here.
The program is not very consistent in coordinate systems, some 
(such as laplace) preserve it, others (aregan/pregan) shift the image
by half a pixel. Most images will have some edge effects too. For
divergence/vorticity the images are assumes to be \fBvx\fP and
\fBvy\fP, in that order.
.PP
All sharpening operations are applied to each plane independantly. 
If you need to sharpen in 3D, use \fIccdsharp3(1NEMO)\fP.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input image file. For certain modes (see \fBmode=\fP below)
the input file must contain at least two images. No default.
.TP 20
\fBout=\fP
Output image file.
No default.
.TP 20
\fBmode=\fP
Modes (laplace, aregan, pregan, divergence, vorticity, grad).
Minimum match applies. 
[Default: \fBlaplace\fP].
.SH EXAMPLES
To compute the vorticity of two images, vx and vy, containing
the X and Y velocities you would:
.nf
    cat vx vy | ccdsharp - v.vor vor
.fi
.SH SEE ALSO
ccdsharp3(1NEMO), ccdmath(1NEMO)
.SH AUTHOR
Peter Teuben, 
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
20-Sep-95	V0.1 Created 	PJT
5-apr-96	V0.2 added divergence, vorticity	PJT
12-jan-2012	
.fi
