.TH CCDSUB 1NEMO "9 April 2009"
.SH NAME
ccdsub \- sub/average of an image
.SH SYNOPSIS
\fBccdsub\fP [parameter=value]
.SH DESCRIPTION
\fBccdsub\fP takes a subimage from an image, as described by a new
set of coordinates in X, Y and/or Z (since the expression of the
selected axes is arbitrary, the resulting coordinate system may
be bogus).
.PP
Since cubes/images produced by this program may have dummy
axes (length 1), you will need to use \fIccdslice(1NEMO)\fP to
get rid of them, or use the \fBdummy=\fP keyword below.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input image file     
.TP
\fBout=\fP
Output image file     
.TP
\fBx=\fP
X coordinates to select. 
Valid numbers are 1..nx. By default all will be selected.
.TP
\fBy=\fP
Y coordinates to select.
Valid numbers are 1..ny. By default all will be selected.
.TP
\fBz=\fP
Z coordinates to select.
Valid numbers are 1..nz. By default all will be selected.
.TP
\fBnxaver=\fP
Number X to aver (size remains same) 
.TP
\fBnyaver=\fP
Number Y to aver (size remains same) 
.TP
\fBnzaver=\fP
Number Y to aver (size remains same) 
.TP
\fBdummy=t|f\fP
Write out dummy axes as well? [true]
.TP
\fBreorder=xyz\fP
New order of axes after all previous actions have been taken.
The default is no reordering, i.e. keep it in \fBxyz\fP order.
To reverse only the X and Y axis, \fBreorder=yxz\fP is needed.
** NOT IMPLEMENTED YET **
.SH SEE ALSO
ccdslice(1NEMO), ccdmom(1NEMO), image(5NEMO)
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
1993     	code written     	PJT
22-Feb-97	man page written	PJT
12-aug-02	more doc	PJT
17-jun-03	WCS for simple subsetting	PJT
9-apr-09	V1.6 replace skip= with dummy=, fix bug nzaver=  	PJT
.fi
