.TH CLFIND3 1NEMO "9 April 2013"
.SH NAME
clfind3 \- experimenting with ClumpFind in 2D or 3D 
.SH SYNOPSIS
\fBclfind3\fP [parameter=value]
.SH DESCRIPTION

.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input file name [???]    
.TP 20
\fBout=\fP
Output clump identification file name [???]  
.TP 20
\fBstep=\fP
Contour step [0.05]     
.TP 20
\fBstart=\fP
Starting step [1]     
.TP 20
\fBlevmin=\fP
Test one level: min []   
.TP 20
\fBlevmax=\fP
Test one level: max []   
.TP 20
\fBVERSION=\fP
28-feb-2013 PJT [0.1]     
.SH EXAMPLES
.SH SEE ALSO
.nf
http://adsabs.harvard.edu/abs/1994ApJ...428..693W - ClumpFind
http://arxiv.org/abs/astro-ph/0601706/ - cprops
.fi
.SH FILES
.SH AUTHOR
mkman
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
09-Apr-13	V0.0 Created by mkman	NEMO
.fi
