.TH ELLIPSE 1NEMO "23 April 2003"
.SH NAME
ellipse \- ellipse (de)projection properties
.SH SYNOPSIS
\fBellipse\fP [parameter=value]
.SH DESCRIPTION
No description available. This manual page was created by mkman
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBba=\fP
Axis ratio of bar. An array is allowed. [???]   
.TP 20
\fBinc=\fP
Inclination of galaxy. An array is allowed [???]    
.TP 20
\fBphi=\fP
Angle between bar and disk in sky plane. An array is allowed.
Either phi or theta (not both) are required. It determines if
projection (theta) or deprojection (phi given) is done.
.TP 20
\fBtheta=\fP
Angle between bar and disk in galax plane. An array is allowed.
.TP 20
\fBVERSION=\fP
28-oct-02 PJT [0.1]     
.SH EXAMPLES
.SH SEE ALSO
.SH FILES
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
23-Apr-03	V0.3 finally created	PJT 
.fi
