.TH FALCON 1NEMO "21 April 2024"

.SH "NAME"
falcon \- Process falcon HDF5 snapshots

.SH "SYNOPSIS"
\fBfalcon\fP [parameter=value]

.SH "DESCRIPTION"
This program convert the HDF5 based \fBfalcON\fP snapshot format
into a NEMO format. It is still under development.
.PP
Selection by time or snapshot number, as well as particle type
can be made eventually.  Note NEMO can only handle one particle type.

.SH "PARAMETERS"
.so man1/parameters
.TP 20
\fBin=\fP
Input \fIfalcon(5NEMO)\fP snapshot filename.
No default.
.TP 20
\fBout=\fP
Output \fIsnapshot(5NEMO)\fP filename.
No default.

.SH "SEE ALSO"
snapprint(1NEMO), tsf(1NEMO), falcON(5NEMO), snapshot(5NEMO)

.SH "FILES"
src/nbody/io/falcon.c

.SH "AUTHOR"
Peter Teuben

.SH "HISTORY"
.nf
.ta +1.5i +5.5i
20-apr-2024	V0.1 Created		PJT
.fi
