.TH TEST 1NEMO "24 December 2023"

.SH "NAME"
henyey \- search for periodic orbits in a potential (Henyey's method)

.SH "SYNOPSIS"
\fBhenyey\fP [parameter=value]

.SH "DESCRIPTION"
\fBhenyey\fP computes periodic orbits using the Henyey method
of searching for periodic solutions of a system of 
differential equations in an (optionally rotating) 2D potential.
.PP
The method has been used first by T.S. v. Albada & 
R.H. Sanders (1982) MNRAS, 201, 303. 
For more details see also: Henyey et al.(1964) ApJ 139, 309
.PP
The method originated from the same equations as looking for solutions of
pulsation stars (RR Lyr, Cepheids). See e.g. van Albada and Baker (1971)

.SH "PARAMETERS"
.so man1/paramters
.TP 20
\fBx0=\fP
Initial launching x coordinate [1]
.TP
\fBy0=\fP
Initial launching y coordinate [0] 
.TP
\fBu0=\fP
Initial launching u velocity [0]
.TP
\fBv0=\fP
Initial launching v velocity  [1]
.TP
\fBper=\fP
Period, corresponding to the orbit \fBtype\fP [3]
.TP
\fBtype=\fP
Type of orbit {1,2,3} referring to half, full or quarter orbit (in some TDB order)  [1]
.TP
\fBome=\fP
Pattern speed of potential    [0]
.TP
\fBnorbit=\fP
Number of extra orbits to compute   [1]
.TP
\fBstep=\fP
Step to increase the non-zero (x or y) position for extra orbits   [0.1]

.SH "EXAMPLES"

.EX

  # henyey:
  ./henyey 0.6 0 0 1.9 1.0 1 0.0 0 > bench1.log
  tabcomment bench1.log | tabplot - 3 4 -1 1 -1 1 line=1,1 yapp=1/xs

  # perorb:
  perorb phase=0.6,0,0,0,1.89,0 dir=x potname=bar83 potpars=0,1,1,0.2,1  out=o2
  orbplot o2 xrange=-1:1 yrange=-1:1  yapp=2/xs

.EE

.SH "CAVEATS"
For a bar-only model this code has been confirmed to produce the same orbits
as \fIperorb(1NEMO)\fP.
.PP
Unlike other NEMO orbit related programs, the potential has been hard-coded.
The corresponding Makefile makes it relatively easy to plug in another potential.
Parameters are passed through FORTRAN common blocks, but again, hard-coded and not
available via the command line interface yet, with the exception of the pattern speed.

.SH "SEE ALSO"
perorb(1NEMO)
.nf

1964ApJ...139..306H - A New Method of Automatic Computation of Stellar Evolution.
1982MNRAS.201..303V -  Periodic orbits and gas flow in barred spirals 
.fi

.SH "ADS"

@ads 1982MNRAS.201..303V

.SH "AUTHOR"
Tjeerd van Albada, Peter Teuben (NEMO adaptation)

.SH "HISTORY"
.nf
.ta +1.5i +5.5i
28-may-1979	original version as SBORB	TVA
1981?     	Cyber7600 version - sheltran	PJT
xx-may-92	V0.0 ported to NEMO     	PJT
xx-mar-03	V0.01 .. and still working ..	PJT
24-dec-2023	V0.2 renumbered, cleanup, confirm perorb	PJT
.fi
