.TH KEP2KEP 1NEMO "19 Jun 1992"
.SH NAME
kep2kep \- interactive transformations between kepler orbit coordinates
.SH SYNOPSIS
\fBkep2kep\fP [parameter=value]
.SH DESCRIPTION
\fIkep2kep\fP is one of the few interactive programs in NEMO, and 
aids in transforming between different orbit
descriptions that exist for Keplerian (2-body) orbits.
.PP
Transformations can be done between the following systems
.nf
.ta +1i +0.7i  +0.7i  +0.7i  +0.7i  +0.7i  +0.7i  +0.7i 
cartesian	x	y	z	vx	vy	vz
spherical	rmod		theta	phi	vrad	vtheta	vphi
scattering	imp.param	imp.angle	init.separ	v_at_inf	theta	phi
tscattering	imp.param	imp.angle	encount.time.	v_at_inf	theta	phi
trueanomaly	a	e	i	OMEGA	omega	f
eccanomaly	a	e	i	OMEGA	omega	E
meananomaly	a	e	i	OMEGA	omega	M
peripassage	a	e	i	OMEGA	omega	T
.fi
.PP
The final transformation is a combination of only three types
of transformation. Within each class of coordinate systems there
is one prototype which has the same name as the class. To get from
A to B, the first transformation is from A to prototype(A), then from
prototype(A) to prototype(B), and finally from prototype(B) to B.
these three transformations are called \fIcan\fP, \fItrans\fP, \fIcast\fP, 
respectively.
.nf
  
   ___________     trans     __________________________________________
  |           |------------>|                                          |
  | CARTESIAN |<------------|               TRUEANOMALY                |
  |___________|             |__________________________________________|
       |  A                  c |  A             |  A             |  A
       |  |                  a |  | c           |  |             |  |
       |  |                  s |  | a           |  |             |  |   
       |  |                  t |  | n           |  |             |  |
   ____V__|___            _____V__|___     _____V__|____     ____V__|_____   
  |           |          |            |   |             |   |             |  
  | SPHERICAL |          | ECCANOMALY |   | MEANANOMALY |   | PERIPASSAGE |
  |___________|          |____________|   |_____________|   |_____________|
.fi
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.SH SEE ALSO
kep2kep.c
.SH FILES
.nf
.ta +1i
~/src/nbody/kepler      kep2kep.c
.fi
.SH AUTHOR
Piet Hut
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
Dec 1987	Created - Piet Hut  @ Inst. f. Adv. Study, Princeton, NJ 08540, USA
Mar 1991	adapted for NEMO V2 - no local error() and warning()	PH/PJT
Jun 1991	one more appeasement for GCC	PJT
May 1992	removed local versions of error(*) and warning()	PJT
19-jun-92	fixed all those gcc warnings about local declaration mismatch	PJT
.fi
