.TH LINEID 1NEMO "18 January 2026"

.SH "NAME"
lineid \- identify peaks in a spectrum and optionally identify lines

.SH "SYNOPSIS"
\fBlineid\fP in=file [parameter=value]

.SH "DESCRIPTION"
\fBlineid\fP identifies peaks in a spectrum (or directly given), 
and attempts to identify spectral lines. The units of the frequency
axis will need to be specified (the default is GHz) in order for the line identification to work.
.PP
It will also inter-operate between sky-freq, rest-freq and doppler velocity, in different doppler conventions:
radio, optical or relativistic.
.PP
Operation can occur in several modes.
.br
1. If the VEL is given, a LineID is attempted. Either from a given
restfreq, or from a linelist.
.br
2. If the RESTFREQ is given, a VEL is determined from the frequency of the
fitted peak.
.br
3. If neither is given, just the peak(s) are reported.
.br
4. A special case can be made when both RESTFREQ and VEL are given, and the x-axis
is given in km/s.  The VEL was computed
from that given (possibly wrong) RESTFREQ, it will then re-compute the sky frequency axis,
and compute rest frequencies and following up with a line ID.
.br
5. The input table can also be a list of already identified peaks. The first
line is the one associated with the restfreq, if that's relevant. Appropriate values
(depending on if \fBrestfreq=\fP or \fBvel=\fP is given) are returned for the other lines,
essentially following the 4 cases described in 1-4.
.br
6. Compare dopper conventions
.PP
See also \fItablsqfit(1NEMO)\fP with the option \fBfit=peak\fP, and \fIccdmom(1NEMO)\fP has
an algorithm to find (properties of) the Nth peak using mom=3,30,31,32,33,34
.PP
More sophisticated algorithms can be fond in for example ADMIT's LineID task, in particular
dealing with multiple "spectra" derived from a fits cube.

.SH "PARAMETERS"
.so man1/parameters
.TP 20
\fBin=\fP\fIfile\fP
Input (table) file name. Should have two columns, but see below for single column
files.
.br
No default.
.TP
\fBxcol=\fP\fIx-column\fP
X coordinate column, representing the frequency or wavelength axis.
Units are GHz, unless specified with the \fBxunit\fP keyword. Column 1 is the first
column.
.br
[1]
.TP
\fBycol=\fP\fIy-column\fP
Y coordinate column, reprepenting an intensity. If not used, the xcol is assumed
to have the already determined values of the lines to be identified or
converted to doppler velocities.
.br
By default not used.
.TP
\fBdxcol=\fP\fIx-err-column\fP
Errors in the X coordnates. Only makes sense if no ycol is given
.br
By default not used.
.TP
\fBxunit=\fP
X axis unit (GHz, MHz, A, nm, km/s, z) -- not all are implemented yet.
.br
[GHz]
.TP
\fBvel=[#[,unit]]\fP
VEL of object, in km/s, independent of \fBxunit\fP. Optionally can have a unit added, e.g. \fIvel=1.2,z\fP.
As for unit, only \fIkm/s\fP and the dimensionless \fIz\fP are allowed.
.br
Not set by default. If a value is given, the unit is \fIkm/s\fP.
.TP
\fBrestfreq=\fP
If line is known, give rest frequency in \fBxunit\fP.
.br
Not set by default.
.TP
\fBlinelist=\fP
Table with frequencies and lines. There is a simple list in $NEMODAT/z_lines.list
with some common high-Z lines.
.br
Not set by default.
.TP
\fBdv=\fP
Slop (in km/s) allowed in identifying lines.
Negative values will use nearest neighbor and report the dv.
.br
[10]
.TP
\fBclip=\fP
Do not fit peaks below this clip level.
.br
Default: not used
.TP
\fBmode=0|1\fP
Fitting mode:  0=no fit needed, the xcol already contains the frequencies (or doppler velocities)
of the lines. No ycol is needed (0 can be used)   1=peak fit (see also \fItabpeak(1NEMO)\fP
for more options).
.br
[1]
.TP
\fBveldef=RAD|OPT|REL\fP
Mode of velocity axis. Radio, Relativistic, or Optical are supported.
.br
[OPT]

.SH "CAVEATS"

Currently frequency conversions are done using the \fI(1+z)\fP formula
with \fIz=VEL/c\fP, i.e. the optical convention.

The code was developed with frequency in mind, only GHz and km/s are supported. Wavelength
is planned.

Looks for emission lines in mode=1. May not work for absorption lines yet, or use \fItabpeak(1NEMO)\fP.

Although different doppler conventions are supported, coordinate frames are ignored.

.SH "EXAMPLES"
The following example generates a random table of 115 values, smoothes by 10 channels to create a handful
of peaks and investigates the strongest peak, which happens to be near 40 "GHz". 
.EX

  tabgen - 115 1 2 123 | tabsmooth - 1 12 10,5 | lineid - 0 1 
  ### nemo Debug[0]: Peak: 40.1222 0.169591

  tabgen - 115 1 2 123 | tabsmooth - 1 12 10,5 | lineid - 0 1 vel=1.87,z
  ### nemo Debug[1]: 1b: Line at 40.122154, Look near freq = 115.150582 GHz for a lineid; vel=560612  

  tabgen - 115 1 2 123 | tabsmooth - 1 12 10,5 | lineid - 0 1 vel=1.87,z linelist=$NEMODAT/z_lines.list
  ### nemo Debug[1]: 1b: Line at 40.122154, Look near freq = 115.150582 GHz for a lineid; vel=560612
  # Commented lines do not fall within dv=10 km/s
  #    guess    ID    LINE     dFreq    deltaV  NAME
  # 115.150582   2 115.271202 0.120619 313.702 CO(1-0)

?
  tabgen - 115 1 2 123 | tabsmooth - 1 12 10,5 | lineid - 0 1 restfreq=115
  ### nemo Debug[1]: 1a: Line at 40.122154 GHz has z=1.86625 or vel=559487 km/s (cz)
  # restfreq=115
  # SkyFreq Vrad  Vrel   Vopt
  1  195198 234729 559487



  tabgen - 115 1 2 123 | tabsmooth - 1 12 10,5 | tabpeak -  0 1 | lineid - 1 restfreq=115
  # restfreq=115
  # SkyFreq Vrad  Vrel   Vopt
  29.914  221810 261794 852717
  40.1222  195198 234729 559487
  72.1352  111744 130493 178145

.EE

and some examples specifying either velocity or frequency of the line(s) directly

.EX
  echo 5000 | lineid - restfreq=1.420405751786 xunit=km/s
  ### nemo Debug[1]: 0a: Line at 5000.000000 km/s has skyfreq 1.397105   (z=0.016678)

  echo 1.420405751786 | lineid - vel=5000 xunit=GHz
  ### nemo Debug[1]: 0c: Line at 1.420406 GHz has restfreq 1.444096 GHz z=0.0166782

  echo 1.397105 | lineid - restfreq=1.420405751786 xunit=GHz
  ### nemo Debug[1]: 0b: Line at 1.397105 GHz has z=0.016678 or vel=4999.903122 km/s (cz)
  # restfreq=1.42041
  # SkyFreq Vrad  Vrel   Vopt
  1.39711  4917.88 4958.21 4999.9


.EE

and here an example of the CO(1-0) and CO(2-1) lines from the CO ladder, deliberately
doppler shifted a bit by 300 km/s (give or take):

.EX
  nemoinp 110.092,115.155,220.179,230.308  |\\
      lineid - linelist=$NEMODAT/z_lines.list vel=300 dv=2.5

  ### nemo Debug[0]: Found 23 lines in the listlist /home/teuben/NEMO/nemo/data/z_lines.list
  # There are 4 restfreq's to identify:
  #    guess    ID    LINE     dFreq    deltaV   NAME
    110.202168   1 110.201354 0.000814 -2.21418  13CO(1-0)
  # 115.270235   2 115.271202 0.000967  2.51514  CO(1-0)
    220.399331   3 220.398680 0.000651 -0.886089 13CO(2-1)
    230.538467   4 230.538000 0.000467 -0.607859 CO(2-1)
.EE



Here an example of known lines in velocity space and deriving their restfreq's. The first line
in the list
will be the one belonging to the known restfreq of CO(1-0), and was detected at -20 km/s. But
there was a weak line at -312 km/s. What line is this? We need to find the restfrquency
and then a lineid.

.EE
  nemoinp -20,-310 | lineid - restfreq=115.2712018 xunit=km/s
  # There are 2 restfreq's to identify: (use linelist= to find names)
  115.271202
  115.382823
.EX

Indeed, the SiC2,v=0 line at 115.382367 had been previously detected in IRC+10216 in 1986 
by the NRAO 11m (Thadeus).

.PP

Compare different doppler conventions (veldef)
.EX
  echo 0 | lineid - vel=5000 veldef=rel
  ### nemo Debug[0]: rad=4958.99 rel=5000 opt=5042.4
.EE

.SH "LINELIST"
The input linelist is a very simple ascii table of (frequency,name).
There are many sources for a linelist, we mention a few:
.nf

1. $NEMO/data/z_lines.list : common high-Z lines, from HI at 1.4GHz upwards

2. ADMIT'S has a few in $ADMIT/etc/*list

3. Splatalogue at https://www.splatalogue.online/

4. Astroquery based:   https://astroquery.readthedocs.io/en/latest/nist/nist.html and
   https://astroquery.readthedocs.io/en/latest/atomic/atomic.html


.fi

.SH "SEE ALSO"
tablsqfit(1NEMO), tabpeak(1NEMO), tabpp(1NEMO), ccdsky(1NEMO), table(5NEMO)
.PP
admit::LineID_AT()

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.25i +4.5i
13-dec-2024	0.1 Draft created	PJT
3-jul-2025	0.3 add mode=	PJT
15-jan-2026	0.4 added simple nearest neighbor line_id	PJT
16-jan-2026	0.5 implemented veldef=		PJT
17-jan-2026	0.6 mode= deprecated	PJT
18-jan-2026	0.7 ...
.fi
