.TH MK2BODY 1NEMO "3 March 2019"
.SH NAME
mk2body \- make a 2 body system
.SH SYNOPSIS
\fBmk2body\fP [parameter=value]
.SH DESCRIPTION
Creates initial conditions for a 2-body problem but where the main body
is initially at the origin with unit mass. Only the mass and phase space
coordinates of the 2nd body can given. 
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBout=\fP
output file name. No default.
.TP
\fBm=\fP
mass of 2nd particle [0.1]   
.TP
\fBx=\fP
X position of 2nd particle [1]  
.TP
\fBy=\fP
Y position of 2nd particle [0]  
.TP
\fBz=\fP
Z position of 2nd particle [0]  
.TP
\fBvx=\fP
VX velocity of 2nd particle [0]  
.TP
\fBvy=\fP
VY velocity of 2nd particle [1]  
.TP
\fBvz=\fP
VY velocity of 2nd particle [0]  
.TP
\fBmass=\fP
Mass of central particle [1.0]
.TP
\fBzerocm=\fP
if true, zero the center of mass [true]
.TP
\fBheadline=\fP
verbiage for output []    
.SH SEE ALSO
mkconfig(1NEMO), mktt72(1NEMO), snapbinary(1NEMO), snapshot(5NEMO)
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
29-Jul-09	V1.0 Created	PJT
7-jun-10	V2.0 added mass=	PJT
.fi
