.TH MKGALORBIT 1NEMO "19 April 2005"
.SH NAME
mkgalorbit \- Make a galactic orbit with from given initial conditions
.SH SYNOPSIS
\fBmkgalorbit\fP [parameter=value]
.SH DESCRIPTION
Unlike \fImkorbit(1NEMO)\fP where an arbitrary orbit can be initialized,
\fImkgalorbit(1NEMO)\fP is specifically intended to initialize orbits
in a galactic potential w.r.t. an assumed solar motion (LSR).
.PP
The sun is assumed to be along the negative X axis, i.e. at (-R0,0,0)
and rotate clock wise, i.e. (0,V0,0).
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBout=\fP
output filename (an orbit) [???]   
.TP
\fBlon=\fP
Longitude (in degrees) []    
.TP
\fBlat=\fP
Latitude (in degrees) []    
.TP
\fBdist=\fP
Distance (in kpc). []
.TP
\fBpmlon=\fP
Proper Motion in Longitude (mas/yr) []  
.TP
\fBpmlon=\fP
Proper Motion in Latitude (mas/yr) []  
.TP
\fBR0=\fP
LSR distance (in kpc) [8.0]   
.TP
\fBV0=\fP
LSR velocities (in km/s) [220.0]   
.TP
\fBlsr=\fP
Use LSR correction of sun going (-9,12,7) [f]
.TP
\fBcoordsys=\fP
lon/lat coordinate system: equ=RA/DEC gal=GLON/GLAT [gal]  
.TP
\fBtime=\fP
time [0.0]      
.TP
\fBpotname=\fP
optional potential(5NEMO) []     
.TP
\fBpotpars=\fP
.. with optional parameters []   
.TP
\fBpotfile=\fP
.. and optional datafile name []  
.TP
\fBheadline=\fP
random verbiage []     
.SH EXAMPLES
Here's an orbit representing the LSR 
.nf
   % mkgalorbit orb1    0 0 0   0 0 0
   ...
   pos: -8.000000 0.000000 0.000000
   vel: 0.000000 220.000000 0.000000
.fi
and solar motion
.nf
   % mkgalorbit orb2    0 0 0   0 0 0
   ...
   pos: -8.000000 0.000000 0.000000
   vel: -9.000000 232.000000 7.000000 
.fi
and the benchmark case, the
example from the gal_uvw IDL script, HD 6755 from the Hipparcos catalog:  (**not working yet**)
.nf
   % mkgalorbit orb3 ten(1,9,42.3)*15. ten(61,32,49.5)  0.144       627.89 77.84  -321.4    coordsys=equ
	===>  u=154  v = -493  w = 97        ;km/s
.fi
.SH SEE ALSO
mkorbit(1NEMO), potcode(1NEMO), potential(5NEMO)
.nf
http://idlastro.gsfc.nasa.gov/ftp/pro/astro/gal_uvw.pro
Johnson & Soderblom (1987, AJ, 93,864)   -- though they define U 
Hipparcos catalog - introduction contains the J2000 transformation matric (ra,dec) -> (glon,glat)
.fi
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
18-Apr-05	V0.1 Created	PJT
.fi
