.TH MKSPHERE 1NEMO "8 September 1995"
.SH NAME
mksphere \- construct an arbitrary spherical mass distribution
.SH SYNOPSIS
\fBmksphere\fP \fBout=\fP \fBnbody=\fP [parameter=value]

.SH "DESCRIPTION"
\fBmksphere\fP creates a spherical mass distribution consistent
with a user supplied density profile.

.SH "PARAMETERS"
.so man1/parameters
.TP 20
\fBout=\fP
Output file name, in standard \fIsnapshot(5NEMO)\fP format. No default.
.TP 
\fBnbody=\fP
Number of particles, no default.
.TP
\fBradii=\fP
Radii in sphere. Must be given in ascending order, but can be any
\fInemoinp(3NEMO)\fP expression, e.g. 0:10:0.1. 
.TP 
\fBdensity=\fP
Associated densities at given radii. If fewer densities are given
than radii, the last entered density will repeat.
.TP
\fBalpha=\fP
If given, rho=radius^{-alpha} power law [Default: none]
.TP 
\fBseed=\fP
Seed for the random number generator. [Default: 0]
.TP
\fBzerocm=\fP
Center the snapshot after creation?     [Default: \fBt\fP]
.TP
\fBrmin=\fP
minimum radius, if to override from radii. Default first radius.
.TP
\fBrmax=\fP
maximum radius, if to override from radii. Default last radius.
.TP
\fBheadline=\fP
Verbiage for output. Default none.

.SH SEE ALSO
snapscale(1NEMO), snapadd(1NEMO), snapshot(5NEMO)
.SH TODO
Add velocities, a fake hubble flow. Look at Vincent Icke's nbodyinit.f
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
8-sep-95	V1.0 Created as toy model for 1995 NHK production	PJT
.fi
