.TH NEMO2GADGET 1NEMO "8 November 2006"
.SH NAME
nemo2gadget \- Convert NEMO snapshot to GADGET snapshot
.SH SYNOPSIS
\fBnemo2gadget\fP [parameter=value]
.SH DESCRIPTION
No description available. This manual page was created by mkman
.PP
This program is currently to be preferred over \fIsnapgadget(1NEMO)\fP.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
NEMO input [???]     
.TP
\fBout=\fP
GADGET output [???]     
.TP
\fBng=\fP
#gas particles [0]     
.TP
\fBnh=\fP
#halo particles [0]     
.TP
\fBnd=\fP
#disk particles [0]     
.TP
\fBnb=\fP
#bulge particles [0]     
.TP
\fBns=\fP
#stars particles [0]     
.TP
\fBfiles=\fP
#output gadget files [1]    
.TP
\fBswap=\fP
#swap data from/to little/big endian. [f]  
.SH EXAMPLES
.SH SEE ALSO
gadget2nemo(1NEMO),snapgadget(1NEMO)
.SH FILES
src/nbody/io/gadget
.SH AUTHOR
Jean-Charles Lambert
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
08-Nov-06	V0.0 Created by mkman	NEMO
.fi
