.TH OCTCODE 1NEMO "11 November 2015"
.SH NAME
octcode \- global octupolar order N-body code integrator
.SH SYNOPSIS
\fBoctcode\fP \fBin=\fP\fIsnapshot\fP [\fIparameter\fP=\fIvalue\fP] .\|.\|.
.P
\fBoctcode.exe\fP 
.SH DESCRIPTION
\fIoctcode\fP is (Aguilar's fortran) version of quadcode with
octupolar terms added. It is being ported to NEMO.
.SH SEE ALSO
quadcode(1NEMO), CSG(1NEMO)
.SH AUTHOR
Luis Aguilar
.SH FILES
.nf
.ta +2i
usr/aguilar/
.fi
.SH HISTORY
.nf
.ta +1i +4i
11-nov-2015	we just talked about porting it....	PJT
.fi
