.TH ORBSTAT 1NEMO "21 February 2003"
.SH NAME
orbstat \- tabulate some orbital statistics
.SH SYNOPSIS
.PP
\fBorbstat in=\fPorbit  [parameter=value]
.SH DESCRIPTION
\fBorbstat\fP will tabulate some statistical properties of a series
or orbits, as given in an input file. Currently time, energy (or first
integral of motion), the maximum extent in X, Y, VX and VY are given,
as well as the mean and dispersion in the angular momentum for 
(XY) planar orbits are given.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword is also
given:
.TP 20
\fBin=\fIin-file\fP
Input file, which must be an \fIorbit(5NEMO)\fP. [No default].
.TP
\fBellipse=t|f\fP
Check how well the orbit is ellipsoidal. 
This option was really added to check on the amazing property the
loop orbits have in potentials that are a function of
ellipsoidal coordinate with constant axis ratio.
Default: \fBf\fP.
.SH CAVEAT
The \fBellipse=t\fP option only makes sense for closed orbits, since
the maximum extent in position and velocity is used for scaling factors
to check the ellipsoidability.
.SH "SEE ALSO"
orblist(1NEMO)
.SH AUTHOR
Peter Teuben
.SH FILES
.nf
.ta +2.5i
~/src/orbit/misc 	orbstat.c
.fi
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
23-mar-95	V1.0 Created	PJT
21-feb-03	V1.1 check how well ellipsoidal 	PJT
.fi
