.TH ORBSTAT 1NEMO "25 April 2005"
.SH NAME
orbstat \- tabulate some orbital statistics
.SH SYNOPSIS
.PP
\fBorbstat in=\fPorbit  [parameter=value]
.SH DESCRIPTION
\fBorbstat\fP will tabulate some statistical properties of a series
or orbits, as given in an input file. Currently time, energy (or first
integral of motion), the maximum extent in X, Y, VX and VY are given,
as well as the mean and dispersion in the angular momentum for 
(XY) planar orbits are given.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword is also
given:
.TP 20
\fBin=\fIin-file\fP
Input file, which must be an \fIorbit(5NEMO)\fP. [No default].
.TP
\fBellipse=t|f\fP
Check how well the orbit is ellipsoidal.  If set to true, it
will print 
\fIT, E, r2_min, r2_max, v2_min, v2_max, r2_mean, r2_sigma, v2_mean, v2_sigma, Lmin/Lmax\fP.
Default: \fBf\fP.
.TP
\fBrelative=t|f\fP
Should energy statistics be done relative to the "known" value by subtracting it?
This is to improve the statistics if the integration is very accurate.
Default: \fBf\fP.
.TP
\fBtab=t|f\fP
Output a table with quantities
Default: \fBf\fP.
.SH CAVEAT
The \fBellipse=t\fP option only makes sense for closed orbits, since
the maximum extent in position and velocity is used for scaling factors
to check the ellipsoidability.
.SH EXAMPLES

.nf
  % mkorbit orb1 1 0 0 0 0.1 1 potname=plummer 'potpars=0,1/sqrt(2),1/sqrt(2)'
  % orbint orb1 - 100 1 mode=euler | orbstat -
# T     E       x_max   y_max   u_max   v_max   j_mean  j_sigma e_mean  e_sigma [abs]
100 -0.0723503 1 4.04463 0 0.1 0.184855 0.0101289 0.163057 0.0239529
  % orbint orb1 - 200 0.5 mode=euler | orbstat -
100 -0.0723503 1 2.34815 0 0.1 0.137628 0.00395845 0.0401559 0.00887043
  % orbint orb1 - 100 1 mode=rk4 | orbstat -
100 -0.0723503 1.91846 0.745393 0.872376 0.1 0.0998526 7.33814e-05 -0.0746802 0.000728993
  % orbint orb1 - 200 1/2 mode=rk4 | orbstat -
100 -0.0723503 1.93045 0.710908 0.871285 0.1 0.0999952 2.51481e-06 -0.0724567 3.22187e-05

.fi
.SH "SEE ALSO"
orblist(1NEMO)
.SH AUTHOR
Peter Teuben
.SH FILES
.nf
.ta +2.5i
~/src/orbit/misc 	orbstat.c
.fi
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
23-mar-95	V1.0 Created	PJT
21-feb-03	V1.1 check how well ellipsoidal 	PJT
25-apr-05	V2.0 add relative= and tab=	PJT
.fi
