.TH QBINSNAP 1NEMO "26 June 2012"
.SH NAME
qbinsnap \- convert binary files to snapshot
.SH SYNOPSIS
\fBqbinsnap\fP [parameter=value]
.SH DESCRIPTION
No description available. This manual page was created by mkman
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input rvc file [???]    
.TP 20
\fBout=\fP
Output snapshot file [???]    
.TP 20
\fBnbody=\fP
Number of bodies [0]    
.TP 20
\fBbody=\fP
Body variables [pos,vel]     
.TP 20
\fBnp=\fP
Np [256]      
.TP 20
\fBlbox=\fP
Box (MPc/H) [512]     
.TP 20
\fBh=\fP
Hubble [72]      
.TP 20
\fBheadline=\fP
Random verbiage []     
.TP 20
\fBVERSION=\fP
26-jun-2012 PJT [0.3]     
.SH EXAMPLES
.SH SEE ALSO
.SH FILES
.SH AUTHOR
mkman
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
26-Jun-12	V0.3 Created	PJT
.fi
