.TH QSF 1NEMO "25 May 2024"

.SH "NAME"
qsf \- query a structured file

.SH "SYNOPSIS"
\fBqsf in=\fP\fIin-file\fP

.SH "DESCRIPTION"
\fIqsf\fP queries if a file is a proper \fIbinary structured file\fP. If so,
it returns a 0 status to the parent shell, if not, 1 is returned.
Most \fBNEMO\fP programs will exit when structured files are
expected, and no such thing was encountered.
.PP
\fIascii structured files\fP can be converted to \fIbinary\fP using
\fIrsf(1NEMO)\fP. Other format converted are problem specific.
.PP
A unix pipe (usually respresented by a "-" in NEMO) is never considered
a structured file, and will thus return a 0.

.SH "PARAMETERS"
.so man1/parameters
.TP 20
\fBin\fP=\fIin-file\fP
Input filename to test. 
.br
[no default].
.TP
\fBshow=t|f\fP
Show the return value on screen as well (0 or 1).
.br
[Default: f]

.SH "EXAMPLES"

.EX
 $ qsf $NEMODAT/iau.dat  ; echo $?
 0
 
 $ qsf $NEMODAT/iau.data  ; echo $?
 1
 
 $ if [ $(qsf $NEMODAT/iau25.dat show=t) = 0 ]; then
      echo "found a structured file"
   fi	
 
.EE
The signature of a binary file is a hex code "0b" and "92" as the first two
bytes (the reverse is also allowed), viz.:

.EX
 $ hexdump -C iau25.dat | head -2
 00000000 0b 92 63 00 48 65 61 64  6c 69 6e 65 00 00 00 00 |..c.Headline....|
 00000010 34 00 00 00 00 49 41 55  20 32 35 2d 62 6f 64 79 |4....IAU 25-body|
.EE

NEMO tries to be able to work with byte swapped data, but this hasn't been
verified since Apple's M-chip was introduced.


.PP
The \fIfile(1)\fP command can also be made to work, but it would
require a patch to \fB/etc/magic\fP.

.SH "SEE ALSO"
tsf(1NEMO), rsf(1NEM0), file(1)

.SH "AUTHOR"
Peter Teuben

.SH "FILES"
.nf
.ta +1.5i
$NEMO/src/kernel/io  	qsf.c
$NEMO/src/kernel/io  	magic.nemo

.fi

.SH "HISTORY"
.nf
.ta +1.25i +4.5i
13-feb-92	V1.0: created	PJT
25-may-2024	V1.1: added show= and EXAMPLES	PJT
.fi
