.TH REB2S 1NEMO "4 July 2024"

.SH "NAME"
reb2s \- convert REBOUND SimulationArchive to NEMO snapshot

.SH "SYNOPSIS"
\fBreb2s\fP [parameter=value]

.SH "DESCRIPTION"
\fBreb2s\fP converts a REBOUND SimulationArchive (RSA) to a NEMO \fIsnapshot(5NEMO)\fP. It currently
converts all snapshots from the RSA, and only converts mass, position and velocity,
the accellerations are still ignored.
.PP
Using \fBverbose=t\fP a number of additional (integration) variables present in an RSA are shown.

.SH "PARAMETERS"
.so man1/parameters
.TP 20
\fBin=\fP
input SimulationArchive.
.br
No default. 
.TP
\fBout=\fP
optional output snapshot; If not specified, the input RSA is just scanned, and snapshot times
are reported.  
.br
Default: no output given, only scan the input.
.TP
\fBverbose=t|f\fP
If verbose is set, additional information for each snapshot in the RSA is given
(time, energy, angular momentum, center of mass, etc.).
.br
[Default: \fBf\fP]

.SH "CAVEAT"
Since verbose output is on standard out, the following pipe will fail in unpredictable ways
.EX
   reb2s p100.reb - verbose=t | tsf -
.EE
since now NEMO's snapshot as well as the verbose output are in the pipe.

.SH "SEE ALSO"
s2reb(1NEMO), reb_viewer(1NEMO), reb_integrate(1NEMO), snapshot(5NEMO), rebound(8NEMO)
.nf
https://rebound.readthedocs.io
.fi

.SH "FILES"
NEMO/usr/hannorein/nemo/reb2s.c - source code

.SH "AUTHOR"
Peter Teuben

.SH "HISTORY"
.nf
.ta +1.5i +5.5i
16-jan-2024	Created		PJT
18-jan-2024	0.6 added a verbose option	PJT
.fi
