.TH ROTCURTAB 1NEMO "29 January 2008"
.SH NAME
rotcurtab \- prints a table of a rotation curve
.SH SYNOPSIS
\fBrotcurtab\fP [parameter=value]
.SH DESCRIPTION
See also \fIrotcurshape\fP.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBradii=\fP
Radii where to sample the rotation curve []
.TP 20
\fBrotcur1=\fP
Rotation curve <NAME>, and parameters []  
.TP 20
\fBrotcur2=\fP
Rotation curve <NAME>, and parameters []  
.TP 20
\fBrotcur3=\fP
Rotation curve <NAME>, and parameters []  
.TP 20
\fBrotcur4=\fP
Rotation curve <NAME>, and parameters []  
.TP 20
\fBrotcur5=\fP
Rotation curve <NAME>, and parameters []  
.TP 20
\fBload=\fP
dynamically loadobject file with rotcur_<NAME> []  
.SH SEE ALSO
\fIrotcurshape(1NEMO)\fP
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
29-Jan-08	V1.0 Created	PJT
.fi
