.TH RUNCHEMH2 1NEMO "5 February 2019"
.SH NAME
runchemh2 \- Frontend to the CHEMH2 program
.SH SYNOPSIS
\fBrunchemh2\fP [parameter=value]
.SH DESCRIPTION
No description available yet.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBrundir=\fP
Run directory [???]     
.TP 20
\fBdat=\fP
Example Input datafile [chemie6.dat]    
.TP 20
\fBDENS0=\fP
2nd line... []     
.TP 20
\fBZETACR=\fP
... []      
.TP 20
\fBG0=\fP
... []      
.TP 20
\fBABUNC=\fP
... []      
.TP 20
\fBABUNO=\fP
... []      
.TP 20
\fBXPRES=\fP
3rd line... []     
.TP 20
\fBABUNMG=\fP
... []      
.TP 20
\fBABUNSI=\fP
... []      
.TP 20
\fBABUNFE=\fP
... []      
.TP 20
\fBABUNS=\fP
... []      
.TP 20
\fBABUNF=\fP
... []      
.TP 20
\fBABUNCL=\fP
... []      
.TP 20
\fBFGPUMP=\fP
5th line... []     
.TP 20
\fBIBRLO=\fP
... []      
.TP 20
\fBISO=\fP
... []      
.TP 20
\fBITURB=\fP
... []      
.TP 20
\fBITHP=\fP
... []      
.TP 20
\fBVERSION=\fP
5-feb-2018 PJT [0.1]     
.SH EXAMPLES
.SH SEE ALSO
.SH FILES
.SH AUTHOR
mkman
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
05-Feb-19	V0.0 Created by mkman	NEMO
.fi
