.TH RUNCHEMH2 1NEMO "5 February 2019"
.SH NAME
runchemh2 \- Frontend to the CHEMH2 program
.SH SYNOPSIS
\fBrunchemh2\fP [parameter=value]
.SH DESCRIPTION
\fBrunchemh2\fP is a front-end for Wolfire's \fIlegacy\fP program \fBchemh2\fP.
Based on a standard template parameter file (chemie6.dat, which is in a very specific ASCII format),
a number of its parameters are selected to be editable (see PARAMETERS below). It will then
run \fBchemh2\fP in a specified run directory, after setting some other conditions needed for the run.
.PP
Some complications concerning the Meudon Merge Option (IBRLO=1) still need to be described and worked out here.
.PP
In the run directory standard files (chemie6.dat, chemh2.log etc.) are present, this is where
the command
.nf
        chemh2 > chemh2.log
.fi
ran, and all other output files (see FILES below) are located.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBrundir=\fP
Run directory [???]     
.TP
\fBdat=\fP
Example Input datafile [chemie6.dat]    
.TP
\fBDENS0=\fP
2nd line... []     
.TP
\fBZETACR=\fP
... []      
.TP
\fBG0=\fP
... []      
.TP
\fBABUNC=\fP
... []      
.TP
\fBABUNO=\fP
... []      
.TP
\fBDVDOP=\fP
... []      
.TP
\fBXPRES=\fP
3rd line... []     
.TP
\fBABUNMG=\fP
... []      
.TP
\fBABUNSI=\fP
... []      
.TP
\fBABUNFE=\fP
... []      
.TP
\fBABUNS=\fP
... []      
.TP
\fBABUNF=\fP
... []      
.TP
\fBABUNCL=\fP
... []      
.TP
\fBFGPUMP=\fP
5th line... []     
.TP
\fBIBRLO=\fP
Meudon flag ... []      
.TP
\fBISO=\fP
... []      
.TP
\fBITURB=\fP
... []      
.TP
\fBITHP=\fP
... []      
.SH SEE ALSO
nemoinp(1NEMO), hisf(1NEMO)
.SH EXAMPLES
In a typical environment you would set the CHEMPATH environment variable to point to a directory (or : separated set
of directories) where all the DATA FILES are located. Typically you would have a sample (template) chemie6.dat file in your
working directory, from where you can then easily run several chemh2's runs, e.g.
.nf
    setenv CHEMPATH /usr/local/data/chemh2:~/chemh2
    
    runchemh2 run001 DENS0=0.5  G0=0.80 &
    runchemh2 run002 DENS0=1.0  G0=0.75   ABUNC=2.0e-4 &
    runchemh2 run003 DENS0=1.5  G0=0.70 &
.fi
.SH FILES
The following files need to be present in the current directory, or in a specified
set of colon separated directories listed in $CHEMPATH 
.nf
.ta +2i
chemie6.dat	standard parameters for chemh2 (can be overridden with \fBdat=\fP)
nprd.in		input file for the Meudon Merge Option (TBD what to do with this)
euv633.dat
marks_spect.snreuv.dat4
avrout.dat
twophasepg10fh20.dat
twophasepg10fh21em4.dat
twophasepg10fh21em3.dat
twophasepg10fh23em3.dat
twophasepg10fh21em2.dat
twophasepg10fh23em2.dat
twophasepg10fh21em1.dat
twophasepg10fh23em1.dat
twophasepg10fh25em1.dat
twophaqsepg10fh27em1.dat
twophasepg10fh29em1.dat
q_ph2_12c160.dat
.fi
The following files are dumped in the run directory:
.nf
.ta +2i
chemie6.dat	Parsed input file for chemh2
chemh2.log	Log file from running chemh2
history.bin	How the program was run (command:  \fBhisf history.bin\fP)
XYZ		output file(s) from chemh2
.fi
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1i +4i
5-Feb-2019	V0.2 hacked up in NEMO		PJT
.fi
