.TH RUNVELFITSS07 1NEMO "27 October 2008"
.SH NAME
runvelfitss07 \- frontend to run Spekkens & Sellwood's 2007 velfit code
.SH SYNOPSIS
\fBrunvelfitss07\fP [parameter=value]
.SH DESCRIPTION
RUNVELFITSS07 is a NEMO frontend to VELFITSS07 , and fits a
bisymmetric flows to disk galaxy velocity fields.
For more details and a full explanation of the paramers, see 
Spekkens and Sellwood (2007ApJ...664..204S)
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
input velocity field [???]    
.TP
\fBout=\fP
output model field [???]    
.TP
\fBpar=\fP
output parameter file [???]    
.TP
\fBcenter=\fP
center of vel field [0,0]   
.TP
\fBvsys=\fP
systemic velocity [0]     
.TP
\fBpa=\fP
position angle of disk (E of N) [0]
.TP
\fBinc=\fP
inclination angle of disk [0]   
.TP
\fBrmsism=\fP
ISM turbulence [0]     
.TP
\fBflags=\fP
Flags which to be fitted/done: geom (inc and pa), center, vsys, radial (m=0), bar (m=1,2...), error estimates.
[1,1,1,0,0,0]
.TP
\fBm=\fP
harmonic order of bar perturbation (1 or 2).
[2]
.TP
\fBseed=\fP
Random Seed [-50]     
.TP
\fBbootstrap=\fP
Number of bootstrap samples if error to be determined. Note using boostrap 
(enabling the last flag) will result in a large runtime.
[200]
.TP
\fBj=\fP
correlation length [1]     
.TP
\fBrcirc=\fP
Radius beyond which no non-circular rmotions fitted [50]
.TP
\fBradii=\fP
Ring Radii at which velocity field components are are extracted.
.TP
\fBexe=\fP
name of VELFITSS07 executable [velfitss07]   
.SH EXAMPLES
After copying the \fBexamp.vels\fP datafile in the current directory, the standard example
from the Users Guide can be run as follows:
.nf
runvelfitss07 examp.vels examp.m examp.p vsys=500 pa=80 inc=60 radii=2.5:50:2.5
.fi
and the next 3 examples from the users guide are run as follows:
.nf
runvelfitss07 examp.vels examp.m examp.p vsys=500 pa=80 inc=60 radii=2.5:50:2.5 flags=1,1,1,1,0,0 rmsism=2.0
runvelfitss07 examp.vels examp.m examp.p vsys=500 pa=80 inc=60 radii=2.5:50:2.5 flags=1,1,1,1,0,1 rmsism=2.0
runvelfitss07 examp.vels examp.m examp.p vsys=500 pa=80 inc=60 radii=2.5:50:2.5 flags=1,1,1,0,1,1 rmsism=2.0
.fi

.SH SEE ALSO
rotcur(1NEMO), velfit(1NEMO), rotcurshape(1NEMO)
.nf
2007ApJ...664..204S (Spekkens & Sellwood, 2007)
http://www.physics.rutgers.edu/~spekkens/velfit/
.fi
.SH FILES
velfit.inc - in the local directory. This will hamper running the program in parallel
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
27-oct-2008	V1.0 : frontend for velfitss07 V1.0 (oct 2008)	PJT
.fi
