.TH RVSNAP 1NEMO "14 May 1997"
.SH NAME
rvsnap \- convert Carlberg's binary 'RV' format to snapshot format
.SH SYNOPSIS
\fBrvsnap\fP [parameter=value]
.SH DESCRIPTION
No description available yet.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input file (RV format). No pipe can be used.
.TP 20
\fBout=\fP
Output file (snapshot).
.SH SEE ALSO
snaprv(1NEMO), rv(5NEMO)
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
14-May-97	V1.0 Created 	PJT
.fi
