.TH SCALE_EPS 1NEMO "12 May 2004"
.SH NAME
scale_eps \- scales individual softening lengths
.SH SYNOPSIS
\fBscale_eps\fP [parameter=value]
.SH DESCRIPTION
No description available. This manual page was created by mkman
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
input file [???]     
.TP 20
\fBout=\fP
output file [???]     
.TP 20
\fBfac=\fP
scale factor for eps_i [???]   
.TP 20
\fBwrite=\fP
what to write to out [mxve]  
.TP 20
\fBtimes=\fP
times of snapshots to scale [all]  
.TP 20
\fBVERSION=\fP

.TP 20
\fBCOMPILED=\fP
May 12 2004, 10:03:05, with gcc-3.2 [] 
.SH EXAMPLES
.SH SEE ALSO
.SH FILES
.SH AUTHOR
Walter Dehnen
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
30-apr-2004	V1.2 added to NEMO	WD
.fi
