.TH SIGCCD 1NEMO "1 Januare 2004"
.SH NAME
sigccd \- convert (WASP sig)tables into images
.SH SYNOPSIS
\fBsigccd\fP [parameter=value]
.SH DESCRIPTION
No description available. This manual page was created by mkman
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input sig (table) file [???]   
.TP 20
\fBout=\fP
Output image file [???]    
.TP 20
\fBnx=\fP
first dimension??? [16]     
.TP 20
\fBdcol=\fP
Column for data [2]    
.TP 20
\fBnmax=\fP
Allocation space for piped I/O [100000]  
.TP 20
\fBVERSION=\fP
1-jan-04 PJT [1.1a]     
.SH EXAMPLES
.SH SEE ALSO
.SH FILES
.SH AUTHOR
mkman
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
01-Jan-04	V0.0 Created by mkman	NEMO
.fi
