.TH SNAPIPDIST 1NEMO "25 June 2020"
.SH NAME
snapipdist \- some stats on interparticle distances
.SH SYNOPSIS
\fBsnapipdist\fP [parameter=value]
.SH DESCRIPTION
This program will  brute force compute for each particle the distance to the nearest particle. It will report
the two particle ID's and the distance. Optionally the input coordinates can also be reported. By default
the particle ID is just the ordinal (0..N-1), but with \fBkey=t\fP the stored particle \fBKey\fP can be used
instead.
.PP
In a future version we may offer more options. See also \fIsnapkmean(1NEMO)\fP for finding clumps
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input file (snapshot) [???]    
.TP
\fBtimes=\fP
Times of snapshot [all]    
.TP
\fBpos=t|f\fP
Show x,y,z as well? [f]
.TP
\fBkey=t|f\fP
Use the key of the body instead of the ordinal (0..Nbody-1). The key could be any integer,
in whatever way it was set. [f]
.SH EXAMPLES
If you want a sorted list of the nearest particle distance, sort the 3rd column:
.nf

mkplummer - 4 seed=123 | snapipdist - | sort -n +2
2 3 0.345923
3 2 0.345923
0 3 1.08003
1 2 4.58542

.fi
which shows that particles 2 and 3 are close neighbors.
.SH SEE ALSO
snapstat(1NEMO), snapkmean(1NEMO), snapkey(1NEMO), snapshot(5NEMO)
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
24-Jun-20	V0.1 Created		PJT
.fi
