.TH SNAPKMEAN 1NEMO "24 September 2007"
.SH NAME
snapkman \- find kmean in selected phase space of a snapshot
.SH SYNOPSIS
.PP
\fBsnapkmean in=\fPsnap_in  [parameter=value]
.SH DESCRIPTION
\fIsnapkmean\fP computes the mean coordinates of K clumps in a snapshot
by iteratively finding the best matching clumps using the \fIK-mean\fP
method.
.SH PARAMETERS
The following parameters are recognized in any order if the 
keyword is also given:
.TP 20
\fBin=\fIin-file\fP
Input file, in \fIsnapshot(5NEMO)\fP format [no default].
.TP
\fBvar=\fIvar_list\fP
List of coordinates to be used. Any \fIbodytrans(3NEM0)\fP
functions can be used in an arbitry expression.
[default: \fBx,y,z\fP].
.TP
\fBk=\fP
K. Typically a small integer.
[default: \fB2\fP].
.TP
\fBtimes=\fItimes-string\fP
Time values/intervals of which snapshots should be used. 
[default: \fBall\fP]
.SH SEE ALSO
snapmode(1NEMO)
.SH AUTHOR
Peter Teuben
.SH FILES
.nf
.ta +3.0i
~/src/nbody/reduc     snapkmean.c
.fi
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
24-sep-07	V1.0: created          	PJT
.fi


