.TH SNAPRV 1NEMO "15 March 2005"
.SH NAME
rvsnap \- convert snapshot format to Carlberg's binary 'RV' format
.SH SYNOPSIS
\fBsnaprv\fP [parameter=value]
.SH DESCRIPTION
No description available yet.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input file (RV format). No pipe can be used.
.TP
\fBout=\fP
Output file (snapshot).
.TP
\fBtimes=\fP
Times to be selected for ouput.
[\fBall\fP]
.SH SEE ALSO
rvsnap(1NEMO), snapshot(5NEMO), rv(5NEMO)
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
13-mar-05	V1.0 document created 	PJT
.fi
