.TH SNAPKINPLOT 1NEMO "04 Jul 2021"

.SH "NAME"
snapkinplot \- plot various diagnostics from snapkinem

.SH "SYNOPSIS"
\fBsnapkinplot\fP [parameter=value]

.SH "DESCRIPTION"
No description available. This manual page was created by mkman

.SH "PARAMETERS"
.so man1/parameters
.TP 20
\fBin=\fP
Input file (snapshot) [???]    

.SH "EXAMPLES"

.SH "SEE ALSO"

.SH "FILES"

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.0i +4.0i
04-Jul-21	V0.0 Created by mkman	NEMO/teuben
.fi
