.TH TABBLEND 1NEMO "21 December 2011"
.SH NAME
tabblend \- create (blended) lines and grid them
.SH SYNOPSIS
\fBtabblend\fP [parameter=value]
.SH DESCRIPTION
\fBtabblend\fP creates a blended line spectrum, grids them,
optionally with hanning smoothing and outputs a table that
can be compared with observations, or be fitted.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBx=\fP
X coordinates (velocities if you wish) of the line(s). Multiple
velocities can be given here.
.TP 20
\fBa=\fP
Amplitudes for each line. 
If not enough values are given, the last value repeats.
[1]
.TP 20
\fBd=\fP
FWHM of the lines (FWHM=2.355*sigma) [1]  
.TP
\fBs=\fP
Points where to sample [-16:16:0.01]    
.TP
\fBg=\fP
Points where to lay the grid [-10:10:1]    
.TP
\fBfwhm=\fP
If non-zero, smooth points with this beam [0]
.TP
\fBhanning=t|f\fP
Optional hanning.
.TP
\fBfft=t|f\fP
Use FFT to compute observed spectrum? (not implemented)
.TP
\fBrms=\fP
RMS value for the noise added to the final spectrum. Default: 0
.TP
\fBseed=\fP
The usual random seed (see also \fIxrandom(1NEMO)\fP). Default: 0
.TP 
\fBmode=\fP
Output mode. 0 will output the raw spectrum before smoothing 
and gridding etc.   1=will output the final spectrum, after 
all gridding and noise addition. Default: 1
.SH EXAMPLES
.nf
   tabblend x=-4,0,2 a=0.5,1,0.5 | tabplot - line=1,1
.fi
.SH SEE ALSO
tabplot(1NEMO)
.SH FILES
NEMO/src/kernel/tab : sources
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
21-dec-11	V0.0 Created	PJT
.fi
