.TH TABDATE 1NEMO "9 May 2005"
.SH NAME
tabdate \- Convert a date/time column
.SH SYNOPSIS
\fBtabdate\fP in_file out_file in_format out_format
.SH DESCRIPTION
\fBtabdate\fP converts a file with the string representation of one date
format into another. It is simply a wrapper of 
\fIstrptime(4)\fP to \fIstrftime(4)\fP.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
input file name(s). 
No default.
.TP
\fBout=\fP
output file name. 
No default.
.TP
\fBformat1=\fP
format to read with. The field descriptors are 
explained in \fIstrptime(3)\fP and \fIdate(1)\fP.
No default.
.TP
\fBformat2=\fP
format to write with.
No default.
.TP
\fBtcol=\fP
Columns to use for the input time. A number of columns can be give, but they
will be pasted together
If none supplied, the whole line will be used to extract the time from.
.TP
\fBtime0=\fP
If given, this will be the format (as used by \fBformat1=\fP) to reference the
time to. The output is now forced to be \fBformat0=%s\fP, i.e. number of seconds
since \fBtime0\fP. The special value 0 is used to define the reference time as
the first timestamp in the file. Default: none.
.SH EXAMPLES

.nf
  % echo '2001-11-12 18:31:01' | tabtime - - '%Y-%m-%d %H:%M:%S' '%c'
  Mon Nov 12 18:31:01 2001

  % date +%s | tabtime - - %s %c
  Mon May  9 16:16:06 2005
.fi
and a contrived way to turn time into seconds
.nf
  tabdate tab0 - %T "1970 %T" | tabdate - - "%Y %T" %s
.fi
and here an example to find the number of seconds between two time-stamps:
.nf
  % set t0="`date +%s`"
  ...
  % set t1="`date +%s`"
  % printf "%s\n%s\n" "$a"  "$b" | tabdate - - "%c" %s time0=0
.fi
.SH BUGS
Cannot handle fractional seconds.
.SH SEE ALSO
date(1), strptime(3), strftime(3)
.SH FILES
.nf
src/kernel/tab	tabdate.c
.fi
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
1-Feb-05	V0.1 Created	PJT
9-may-05	V0.2 added a working time0= and future tcol=	PJT
.fi
