.TH TABHEAD 1NEMO "30 March 2023"

.SH "NAME"
tabhead \- Generate an ascii table header

.SH "SYNOPSIS"
\fBtabhead\fP [parameter=value]

.SH "DESCRIPTION"
No description available. This manual page was created by mkman

.SH "PARAMETERS"
.so man1/parameters
.TP 20
\fBcols=\fP
Column names []     
.TP
\fBmode=\fP
Mode: 0=colN 1=spreadsheet []    
.TP
\fBprefix=\fP
Prefix []
.TP
\fBsepar=\fP
Extra separator between column names.
.TP
\fBncols=\fP
Number of columns in case cols= not given

.SH "EXAMPLES"

.SH "SEE ALSO"
tabgen(1NEMO), table(5NEMO)

.SH "FILES"

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.5i +5.5i
30-mar-2023	Created ...	PJT
.fi
