.TH TABHEAD 1NEMO "30 March 2023"

.SH "NAME"
tabhead \- Generate an ascii table header

.SH "SYNOPSIS"
\fBtabhead\fP [parameter=value]

.SH "DESCRIPTION"
Some programs that manipulate tables, especially those outside of NEMO,
benefit from having a descriptive header.  The \fItable(5NEMO)\fP describes
a number of them.

\fBtabhead\fP will generate headers, depending on the mode (see \fBmode=\fP below),
automagically.

.SH "PARAMETERS"
.so man1/parameters
.TP 20
\fBcols=\fP
Column names []     
.TP
\fBmode=\fP
Mode: 0=colN 1=spreadsheet []    
.TP
\fBprefix=\fP
Prefix []
.TP
\fBsepar=\fP
Extra separator between column names.
.TP
\fBncols=\fP
Number of columns in case cols= not given

.SH "EXAMPLES"
To give a simple alpabetically ordered column names to a table with 10 columns:
.nf

   % tabhead ncols=10 mode=2 > ex1.tab
   % tabgen - nr=100 nc=10  >> ex1.tab

.fi

.SH "SEE ALSO"
tabgen(1NEMO), table(5NEMO)

.SH "FILES"
src/kernel/tab

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.5i +5.5i
30-mar-2023	Created ...	PJT
.fi
