.TH TABLINT 1NEMO "18 May 2005"
.SH NAME
tablint \- \fIprototype\fP table syntax checker
.SH SYNOPSIS
\fBtablint\fP in= lint= [parameter=value]
.SH DESCRIPTION
\fItablint\fP checks tables and can optionally apply selections and output
this in the same format. 
.PP
The current version only checks for a consistent number of columns in the
file, by default the first non-empty/comment line determines the number of
columns, unless \fBmaxcol=\fP was used to set it.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
input file name     
.TP
\fBlint=\fP\fIlint_form\fP
lint specification      
.TP
\fBmaxcol=\fP
Number of columns allowed. If set to 0, it will use the first row that looks like
data to count the number of columns. Default: 0
.TP
\fBlinelen=\fP
Override some sensible maximum linelength (normally 16384 in maxsizes.h).
.TP
\fBout=\fP
For those rows that pass the criteria specified in \fIlint_form\fP ** not used **
.SH LINT FORMAT
The \fIlint_form\fP is a simple ASCII file that describes the table
is some uniform way. You can also apply checks on any column, set
validity intervals, and use it to output a new table with these
selections applied. Here is an example
.nf
# this is an example 'lint' specification for tablint
#
\fBmaxcol\fP 10

\fBcol\fP 1 {
    \fBname\fP id		# name of a column (optional)
    \fBtype\fP int
    \fBrange\fP -10:10 
    \fBblank\fP -999		# although outside range, this signifies BLANK ???
}

col 2 {
    name town
    type char
    length 1:10		# a string 1-10 characters in length
}

col 3 {
    name zipcode
    type char
    length 2		# all strings must be 2 chars length
    match DC|MD|VA	# example of exclusive OR-ed
}

col 4 {
    name any
    type char
}

col 5 {
    name bad		
    type float		# example of a non-existent type
    john doe		# example of a non-existent 
}

col 6 {
    name good
    type real
    range 0:		# example of a half-infinite range interval
}

.fi
.SH SEE ALSO
tabmath(1NEMO), table(5NEMO)
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
13-Jan-95	V0.1 Prototype created  	PJT
18-may-05	V0.3 deprecate lint= for now, and just simple column counting check	PJT
.fi
