.TH TABPEAK 1NEMO "19 January 2026"
.SH "NAME"
tabpeak \- find peaks in a table

.SH "SYNOPSIS"
\fBtabpeak\fP [parameter=value]

.SH "DESCRIPTION"
\fBtabpeak\fP finds local maxima (and/or minima) and fit a local paraboloid, return the location and
value of the peaks, or valleys. See also \fItablsqfit(1NEMO)\fP and \fIccdmom(1NEMO)\fP for more
advanced versions of peak finding.
.PP
The default is to search for local 3 point extrema. Using \fBedge=\fP one can force it
away from the edge, and using \fBpmin=\fP one can increase the minimum number of points
that need to be in the extreme.
.PP
For noisy data \fItabsmooth(1NEMO)\fP can be useful to get more robust estimates of the peaks.
.PP
\fBtabpeak\fP can also be a useful tool to determine lines in a spectrum and pass them
to \fIlineid(1NEMO)\fP

.SH "PARAMETERS"
.so man1/parameters
.TP 20
\fBin=\fP
Input file name, in \fItable(5NEMO)\fP format.
.br
No default
.TP
\fBxcol=\fP
X-Column 
.br
[1]      
.TP
\fBycol=\fP
Y-column
.br
[2]
.TP
\fBclip=\fP
Only consider points above this value
.br
[0]
.TP
\fBdelta=\fP
If a positive value is used, single peaks larger than this value on either side of this
peak are reported.
.br
[0]
.TP
\fBpmin=\fP
[EXPERIMENTAL]
Require the peak to contain at least \fBpmin\fP points. By default, only 3 are required, in which
case a polynomial is fit (though this is an exact fit).  By setting this higher, more points are
required to be part of a peak which is then required to be monotonously decreasing.
.br
[1]
.TP
\fBedge=\fP
Number of points near the edge to skip for a peak finder.   For the simplest 3-point peak
finder this should be at least 1.
.br
[1]
.TP
\fBvalley=t|f\fP
Also fit valleys, in which case the signal has to be below -clip.
.br
[f]
.TP
\fBmean=t|f\fP
Use intensity weighted mean ?
.br
[f]
.TP
\fBnpeak=\fP
extract the Nth peak (N>0). If npeak=0, no extraction done. Other keywords will be ignored
if a peak is ectracted for further analysis.
.br
[0]
.TP
\fBepeak=\fP
expand around the N-th peak extracted by npeak>0 by this factor. By default the segment around
a peak is defined until the first point away from the peak will increase again.
.br
[1]
.TP
\fBnmax=\fP
max size if a pipe
.br
[100000]

.SH "CAVEATS"
Only fits location of peaks, does not attempt to find the width, like a gaussian fit would do.

.SH "EXAMPLES"
The peak in a simple paraboloid:
.EX

  nemoinp 1:3 | tabmath - - "-(2.2-%1)**2+10" | tabpeak -
  2.200000 10.000000
  
.EE
Here is a pipeline extracting the first peak, fitting a gaussian to it, and plotting the data and residuals
(in the PGPLOT driver the data will be in red, the residuals in green, and the fit in blue):
.EX

  tabpeak spec.tab | tabnllsqfit - fit=gauss1d out=- | tee fit.log |\\
          tabcomment - | tabplot - 1 2,3,4 color=2,3,4 line=1,1
  cat fit.log
   
.EE
.PP
Finding single peaks by setting an appropriate delta (related to a robust dispersion of
the differences of the data):

.EX
  tabtrend L1157-B1_109989__1.bstats.tab  2 | tabhist - robust=t
  ...
  Robust Mean Disp     : 1.52724e-05 0.00640417
  
  tabpeak L1157-B1_109989__1.bstats.tab  delta=0.05
  #  X       Y       Ypeak    Delta    Delta
  166.000000 1.591776  0.083979 0.087718 0.080239
  286.000000 26.544859  25.062155 25.063228 25.061082
  452.000000 1.838022  0.324911 0.324182 0.325639
  ...
  3524.000000 1.520718  0.229133 0.229248 0.229019
  3810.000000 0.427400  -0.871551 0.870384 0.872717

.EE

.SH "SEE ALSO"
tablsqfit(1NEMO), tabnllsqfit(1NEMO), tabtrend(1NEMO), tabhist(1NEMO), tabplot(1NEMO),
tabsmooth(1NEMO), lineid(1NEMO), table(5NEMO)

.SH "AUTHOR"
Peter Teuben

.SH "UPDATE HISTORY"
.nf
.ta +1.25i +4.5i
28-May-2013	V0.1 Created	PJT
30-may-2013	V0.2 added valley=	PJT
23-mar-2022	V0.4 added pmin=	PJT
25-mar-2022	V0.5 added edge=	PJT
23-jan-2023	V0.7 added npeak, epeak=	PJT
25-may-2023	0.8 added delta=	PJT
.fi
