.TH TABHIST 1NEMO "10 October 2006"
.SH NAME
tabplot \- general table plotter
.SH SYNOPSIS
.PP
\fBtabplot in=\fPinfile [parameter=value]
.SH DESCRIPTION
\fItabplot\fP plots datapoints from an ascii table, optionally
connects the datapoints by lines, plots different styles for the
points and (if available) uses different colors.
It can also bin the data in X, and compute/plot
error-bars in X and Y derived from the dispersion within those bins.
.PP
\fItabplot\fP can also plot one-to-many, many-to-one as well as pair-wise
plotting. However, it is (not yet) possible to pair-wise plot from
multiple files with different number of rows. See also \fIpaste(1)\fP or
\fItabmath(1NEMO)\fP how to combine tables.
.PP
\fItabplot\fP is really intended for quick and dirty display of the data. 
For more complicated plots, full plotting packages should be used
(Mongo, SM, WIP, gnuplot, Grace, matplotlib etc.), though 
moderately sophisticated
plots can also be made using \fBlayout=\fP. The \fBreadline=\fP is
available to give some degree of interactive usage.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword is also
given:
.TP 20
\fBin=\fIinfile\fP
input file, in (ASCII) tabular format [no default].
.TP
\fBxcol=\fIx-column\fP
column(s) from which the X values are taken. Multiple columns can be
taken, but if so, the number of Y columns must be the same for
pairwise plotting.
[default \fB1\fP].
.TP
\fBycol=\fIy-column\fP
column from which the Y values are taken. Multiple columns can be
given. The number of X columns can either be 1 or must be equal to
the number of Y columns.
[default \fB2\fP].
.TP
\fBxmin=\fIx_min\fP
Minimum value along X-axis to include [default: minimum of datapoints].
.TP
\fBxmax=\fIx_max\fP
Maximum value along X-axis to include [default: maximum of datapoints].
.TP
\fBymin=\fIy_min\fP
Minimum value along y-axis to include [default: minimum of datapoints].
.TP
\fBymax=\fIy_max\fP
Maximum value along y-axis to include [default: maximum of datapoints].
.TP
\fBxbin=\fIboundaries\fP
When used either the number of datapoints used to average to a plotted
datapoint or the bin boundaries (in X-world-coordinates) must be given.
The program can distinguish from both cases by the number of variables
given to this keyword. One means fixed number of datapoints used in
averaging, more than one means the numbers are bin boundaries. The output
is controlled using \fBtab=\fP and contains the
mean X, Y followed by the dispersion in X and Y and the number of
points in that bin.
[default: not used, datapoints from file are used].
.TP
\fBpoint=\fP\fItype,size\fP
Pairs of integers, (one pair for each plotted column) describing the
point type (0=none, 1=point, 2=circle, 3=plus, 4=square)
and size in cm (see also \fIyapp(3NEMO)\fP). Pairs not specified
inherit from the last one entered. Default: 1,0.1
.TP
\fBline=\fP\fItype,width\fP
Pairs of integers, (one pair for each plotted column) describing the
line type and width (see \fIplltype(3NEMO)\fP). Default: 0,0
.TP
\fBcolor=\fP\fIcolor\fP
Integer denoting color. This will be \fIyapp(3NEMO)\fP specific.
Colors not specified will inherit from the last
one entered.
Default: not used (i.e. default drawing color used)
.TP
\fBerrors=x|y|xy\fP
Specify which error bars to draw in case binning is used. If error bars
are used in either raw X or Y columns, this option cannot be used.
Default: none.
.TP
\fBxlab=\fIx-label\fP
Label along the X-axis [default: \fBX\fP].
.TP
\fBylab=\fIy-label\fP
Label along the Y-axis [default: \fBY\fP].
.TP
\fBxcoord=\fP\fIx1,x2,...\fP
A list of numbers (see \fInemoinp(3NEMO)\fP for valid syntax) that will
cause vertical lines at these X coordinate to be drawn. Default: none
.TP
\fBycoord=\fP\fIy1,y2,...\fP
Y coordinates for the horizontal lines, same as \fBxcoord=\fP.
.TP
\fBxbox=\fP
Extent of the plotting frame in the X direction.
[Default: 2:18]
.TP
\fBybox=\fP
Extent of the plotting frame in the Y direction.
[Default: 2:18]
.TP
\fBnxticks=\fP
Number of tickmarks along the X axis. This divides the X axis in
\fInxticks+1\fP pieces. [Default: \fB7\fP].
.TP
\fBnyticks=\fP
Same for Y.
.TP
\fBxscale=\fP
Scaling factor applied to all X values. Default: 1
.TP
\fByscale=\fP
Scaling factor applied to all Y values. Default: 1
.TP
\fBdxcol=\fP
Columns representing error bars in X. These currently need to match the \fBxcol=\fP.
By default no error column(s) are used.
.TP
\fBdycol=\fP
Columns representing error bars in Y. These currently need to match the \fBycol=\fP.
By default no error column(s) are used.
.TP
\fBnmax=\fP
Maximum number of lines that are allocated in pipes. [10000]
.TP
\fBmedian=f|t\fP
Use median to compute "average" binning values. It is used to 
compute the X as well as Y coordinates of the binned point, however
error bars are still computed using the mean.
Default: \fBf\fP.
.TP
\fBheadline=\fItext\fP
Random verbiage, will be plotted along right top of plot for id. [default: none].
The left top will contain the filename \fIinfile\fP.
.TP
\fBtab=t|f\fP
Output table to stdout if binning is used? Default: false;
.TP
\fBfullscale=t|f\fP
Use full scale in one axis if other axis is autoscaled? In versions older
than 2.0 fullscale was always on (t), by default it is now off (f).
.TP
\fBcursor=\fP
This will be the name of an ascii file that will contain coordinates
that have been marked with the cursor,
not the nearest datapoint (currently only implemented for
PGPLOT). Cursor keys are in the usual definition: A=left mouse will mark,
D=middle mouse has no function, X=right mouse will exit. 
Default: not used.
.TP
\fBlayout=\fP
Optional Layout file that contains draw commands. Default: none.
.TP
\fBfirst=t|f\fP
Should the layout file be called first or last ?  
[\fBf\fP]
.TP
\fBreadline=t|f\fP
After all batch plotting is done, should an interactive layout annotator
(see also \fIlayout(5NEMO)\fP) be called. 
[\fBf\fP]
.SH BUGS
tab= doesn't work properly with multiple columns
.SH EXAMPLES
Here is an example working with layout files. 
.nf

  % nemoinp 1:20 | tabmath - -  'ranu(0,1),ranu(0,1)' all > ran.tab
  % tabmath ran.tab - '2+%1*16,2+%2*16,0.2' all | awk '{print "circle",$0}' > ran.layout
  % tabplot ran.tab 1 2 0 1 0 1 layout=ran.layout

.fi
It plots the data points from the file \fBran.tab\fP as dots, and
converts, using tabmath and awk, these to a layout file where the
same points as plotted as open circles in \fBran.layout\fP. Note that
currently the user has to convert to \fIyapp\fP (cm) units, and 
actually know that most yapp plots runs from 2 to 18 cm in both X and Y.
This will likely change in a future version where points can be given
in a more reasonably WCS.
.PP
Here are some examples of plotting multiple columns/rows, assuming each example
of the tab1 and tab2 table has 2 columns:
.nf

   % paste tab1 tab2 | tabplot - 1 4                     headline=x1,y2
   % tabmath tab1,tab2 - %1-%3,%2-%4 all | tabplot - 1 2 headline=dx,dy
   % paste tab1 tab2 | tabplot - 1,3 2                   headline=x1,x2,y1
   % paste tab1 tab2 | tabplot - 1   2,4                 headline=x1,y1,y2
   % paste tab1 tab2 | tabplot - 1,2 3,4                 headline=(x1,y1),(x2,y2)

.SH "SEE ALSO"
tablsqfit(1NEMO), tabmath(1NEMO), yapp(5NEMO)
.PP
http://vostat.org
.SH AUTHOR
Peter Teuben
.SH FILES
.nf
.ta +3.0i
~/src/kernel/tab	tabplot.c
.fi
.SH "UPDATE HISTORY"
.nf
.ta +1.0i +5.5i
25-nov-88	V1.0 - created  	PJT
13-nov-90	V1.1 deleted nmax= by using file_lines()	PJT
26-jan-95	V1.5a multi-column plotting support, trickmarks, extra coord lines	PJT
14-feb-96	V1.6 added cursor= keyword (*PGPLOT only*)	PJT
7-may-98	V2.0 added median= for binning method	PJT
25-jul-98	V2.0b added line=lwidth,lstyle w/ lstyle<0 histogram (thank Kartik)	PJT
31-mar-99	V2.1 autoscaling now takes range in other axis into account	PJT
28-jul-99	V2.2 added color=
21-jul-00	V2.3 min & max can be separately set	PJT
2-aug-02	V2.5 allow number of x columns to be > 1	PJT
17-sep-05	V2.8 added readline= and documented first=	PJT
2-dec-05	V2.9 implemented missing many-to-one plotting mode	PJT
20-dec-05	V3.0 added xscale,yscale and started dxcol,dycol. Fixed xbin= bug	PJT
10-oct-06	V3.0e finished dxcol=, dycol=	PJT
.fi
