.TH TABSPLINE 1NEMO "5 April 2001"
.SH NAME
tabspline \- interpolate in a table
.SH SYNOPSIS
\fBtabspline\fP [parameter=value]
.SH DESCRIPTION
\fBtabspline\fP interpolates any function y=f(x) in tabular format.
It actually is not required that x in monotonically increasing or
decreasing, the function could be a parametrized table (x=f(t),y=g(t)).
The interpolation can occur in X as well as Y. It is currently linear,
but spline is to be added.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input file      
.TP
\fBxcol=\fP
X column [1].
.TP
\fBycol=\fP
Y Column [2].  
.TP
\fBx=\fP
For this X, find the corresponding Y. 
Can be an array using \fInemoinp(3NEMO)\fP notation.
[default: not used]
.TP
\fBy=\fP
For this Y, find the corresponding X 
Can be an array using \fInemoinp(3NEMO)\fP notation.
[default: not used]
.TP
\fBn=\fP
How many to find. By default it will find all possible roots, but
one can limit the number using this keyword. (0=all). [0]
.TP
\fBformat=\fP\fIC-fmt\fP
Output format in C format (\fIprintf(3)\fP) notation.
[Default: \fB%g\fP]
.SH EXAMPLES
Here is an cute way to estimate sqrt(2):
.nf
% nemoinp 1:2:0.001 | tabmath - - '%1*%1' | tabspline - y=2
1.41421 2
.fi
.SH SEE ALSO
.nf
table(5NEMO)
.fi
.SH FILES
.nf
.ta +2i
src/kernel/tab/tabspline.c	source code
.fi
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
15-Apr-98	V2.0 TOOLBOX made functional for Sally	PJT
16-apr-98	split code and placed in src/kernel/tab 	PJT
23-jan-01	V2.1 added x=,y= arrays for Mousumi	PJT
5-apr-01	V2.2: added format=	PJT
.fi
