.TH TABSMOOTH 1NEMO "20 December 2010"
.SH NAME
tabsmooth \- (hanning) smooth columns of a table
.SH SYNOPSIS
\fBtabsmooth\fP [parameter=value]
.SH DESCRIPTION
No description available. This manual page was created by mkman
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input file name [???]    
.TP 20
\fBxcol=\fP
Column(s) to use [1]    
.TP 20
\fBnmax=\fP
max size if a pipe [100000]  
.SH SEE ALSO
tabmath(1NEMO)
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
20-Dec-10	V0.0 Created	PJT
.fi
