.TH TABSMOOTH 1NEMO "21 June 2024"

.SH "NAME"
tabsmooth \- smooth columns of a table (Hanning, Savitzky-Golay)

.SH "SYNOPSIS"
\fBtabsmooth\fP [parameter=value]

.SH "DESCRIPTION"
\fIsmooth\fP selected column(s) of an ASCII table
without paying attention to the X coordinate (meaning: a constant
step size is assumed).
.PP
The \fBfilter=\fP option is used to select the filter, for example
a Hanning, Boxcar, Gaussian and a Savitzky-Golay filter (and some of their
derivates) can be selected.   A pass-through is also allowed. Some of the
filters need additional argument(s), given by \fBpars=\fP.
.PP
Optionally the smoothing kernel can be shown using \fPshow=t\fP.

.SH "PARAMETERS"
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input file name.
.br
No default
.TP 
\fBxcol=\fP
Column(s) to use. Although multiple columns can be used, only those 
columns are output to stdout.
.br
[1]
.TP
\fBfilter=\fP
Filter option. The way the options are set will likely change, this
is work in progress.
.nf
   -1 passthrough, the column is not modified
   0  hanning (1,2,1)
   1  SK2 5pt smooth
   2  SK2 1st derivative with h=1 (sum=0)
   3  SK2 2nd derivative with h=1 (sum=0)
   4  SK4 7pt smooth
   5  SK4 1st derivative  (sum=0)
  11  boxcar, needs  pars=width
  12  gaussian, needs pars=stdev[,nsigma=4]
  13  trapezoidal, needs pars=width (width=1 is also the hanning)
.fi
The smoothing kernels are normalized to 1 conserve "flux" (defined as the sum of values here).
.br
Default: 0
.TP 
\fBpars=\fP\fIpar1,par2,...\fP
Optional parameters some of the filters need
.br
Default: not used
.TP 
\fBsmooth=\fP
Manually set the smoothing array. By default, the filter= is used to set the smoothing
array.  Be sure to enter an odd number
of array elements, for example a normalized Hanning would be
smooth=0.25,0.5,0.25.
.br
Default: not used.
.TP 
\fBtcol=\fP
Optional column designating the independant variable. Currently the actual value is ignored,
but this column will be output before the smoothed column(s).
.br
Default: not used.
.TP 
\fBshow=t|f\fP
If set, it  will show the smoothing kernel. No input file is needed in this case.
.br
Default: f
.TP
\fBedge=0|1\fP
(future) how to deal with edges, e.g. should flux be conserved by mirroring the kernel
.br
Not implemented yet.

.SH "EXAMPLES"
Here we draw 100000 random values from a normal distribution (mean 0, dispersion 1) and smooth them
with various filters, and observe what the resulting dispersion is:
.nf

tabgen - 100000 1 2 123| tabsmooth - 1 -1 | tabstat - | grep disp
1.0022
tabgen - 100000 1 2 123| tabsmooth - 1  0 | tabstat - | grep disp
0.6128
tabgen - 100000 1 2 123| tabsmooth - 1  1 | tabstat - | grep disp
0.6973
tabgen - 100000 1 2 123| tabsmooth - 1  4 | tabstat - | grep disp
0.7537

.fi
Here is the gaussian smoothing kernel, then applied to the previous example using
a NEMO @file 
.EX

  $ tabsmooth . filter=12 pars=1,2 show=t
  0.0544887
  0.244201
  0.40262
  0.244201
  0.0544887
  
  $ tabsmooth . filter=12 pars=1,2 show=t > smg.tab
  $ tabgen - 100000 1 2 123| tabsmooth - 1 smooth=@smg.tab | tabstat - | grep disp
  disp:    0.536438
  

.EE

.SH "CAVEATS"
Near the edge the smoothing array is cut off, thus there is some loss of flux.
Otherwise in general the smoothing filter is normalized and should conserve flux.
The \fBedge=\fP keyword will try and deal with this, for example by allowing to
mirror the smoothing kernel.

.SH "SEE ALSO"
tabmath(1NEMO), tabtrend(1NEMO), tabrows(1NEMO), tabcols(1NEMO), ccdsmooth(1NEMO), table(5NEMO)

.SH "AUTHOR"
Peter Teuben

.SH "HISTORY"
.nf
.ta +1.25i +4.5i
20-dec-2010	V0.1 Created	PJT
13-oct-2014	documented smooth=
28-sep-2023	V0.5 added filter=	PJT
29-sep-2023	V0.6 converted to table V2	PJT
29-nov-2023	V0.7 added tcol=	PJT
21-jun-2023	V0.8 added show= and pars= for filters 	PJT
.fi
