.TH TABTREND 1NEMO "15 June 2016"
.SH NAME
tabtrend \- difference rows from previous rows
.SH SYNOPSIS
\fBtabtrend\fP [parameter=value]
.SH DESCRIPTION
\fBtabtrend\fP takes a single column from an ASCII table, and differences subsequent
values, creating a new column that is thus one row shorter.
.PP
Note that for a gaussian signal, 
differencing subsequent elements will create a distribution
with a noise sqrt(2) larger than the input signal.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input file name. No default.
.TP
\fBxcol=\fP
Column(s) to use [1]
.TP
\fBcumul=t|f\fP
Cumulative, instead of differences.  Default: false
.TP
\fBnmax=\fP
max size if a pipe [100000]  
.SH EXAMPLES
Create 10000 numbers gaussian distributed with dispersion 1, observe the following:
.nf
set n = 10000

seq $n | tabmath - - 'rang(0,1)' all seed=-1 |                             tabhist - 1 -2 2 nmax=$n
# sigma=1
seq $n | tabmath - - 'rang(0,1)' all seed=-1 | tabsmooth - |               tabhist - 1 -2 2 nmax=$n
# sigma=0.612 (sqrt(3/8))
seq $n | tabmath - - 'rang(0,1)' all seed=-1 | tabtrend -  |               tabhist - 1 -2 2 nmax=$n
# sigma=1.414 (sqrt(2))
seq $n | tabmath - - 'rang(0,1)' all seed=-1 | tabsmooth - | tabtrend -  | tabhist - 1 -2 2 nmax=$n
# sigma=0.5
seq $n | tabmath - - 'rang(0,1)' all seed=-1 | tabtrend -  | tabsmooth - | tabhist - 1 -2 2 nmax=$n
# sigma=0.5
.fi
Note that smoothing and trending are related, so their resulting dispersions in the last two 
examples do not multiply.
.PP
This also means if you don't know if a signal had been applied a Hanning smoothing, compute the sigma
before and after a difference operator. If that ratio is sqrt(2), it means it was not, it was a pure
un-correllated gaussian. However, if the ratio is sqrt(2/3) = 0.816, it was a Hanning smoothed signal
to begin with.
.SH SEE ALSO
tabsmooth(1NEMO), tabmath(1NEMO), nemoinp(1NEMO), tabhist(1NEMO)
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
26-Nov-2012	finally documented	PJT
13-oct-2014	better examples		PJT
15-jun-2016	added cumul=		PJT
.fi
