.TH TIPSYSNAP 1NEMO "28 august 2001"
.SH NAME
tipsysnap \- convert tipsy file to snapshot
.SH SYNOPSIS
\fBtipsysnap\fP [parameter=value]
.SH DESCRIPTION
\fBtipsysnap\fP converts a \fItipsy\fP ascii or binary formatted data file,
consisting of gas, dark and star- particles to \fIsnapshot(5NEMO)\fP
format. Simple selections by particle kind can be made.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input TIPSY file. No default.
.TP
\fBout=\fP
Output snapshot file. No default.
.TP
\fBoptions=\fP
Output which particles?. Valid options are
\fBgas\fP, \fBdark\fP and \fBstar\fP. Default:
\fBgas,dark,star\fP (all).
.TP
\fBmodes=ascii|binary\fP
Read ascii or binary TIPSY file format. Default: ascii
.TP
\fBswap=t|f\fP
Swap bytes. This is needed if you want to be able to read
standard (XDR, big endian) or native binary files.
Default: false.
.TP
\fBoffset=0\fP
Number of bytes to offset the data portion from the header. Normally
this would be 0, but the header strcture (tipsydefs.h) containing
one double and 5 integers, some architectures may read this as
32 bytes, whereas it was meant to be 28 bytes. By using offset=-4
in this case, data with 28 byte headers can still be read. Equally
so, the opposite can also happen, in which case offset=4 is needed.
Default: 0
.SH DATA FORMAT
See also \fItipsy(5NEMO)\fP on some basic concepts of tipsy data. The
ascii format of a TIPSY "\fIgds\fP" (gas-dark-star) snapshot is essentially
a single long column of data with the following items
.nf
ntot ngas nstar      [noting that ndark=ntot-ngas-nstar]
ndim                 [usually 3, i've not see ndim=2 data]
time                 [a floating point number]
M(g),M(d),M(s)       [but all of these in 1 column]
X(g),X(d),X(s)
Y(g),Y(d),Y(s)
Z(g),Z(d),Z(s)
VX(g),VX(d),VX(s)
VY(g),VY(d),VY(s)
VZ(g),VZ(d),VZ(s)
EPS(d), EPS(s)
\.\.\.
.fi
.SH BUGS
In \fBmode=binary\fP the gas, dark and star particles are output
in separate snapshots.
.SH SEE ALSO
snaptipsy(1NEMO), stoa_tip(1ZENO), tipsy(5NEMO)
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
02-Sep-94	V1.0 Created 	PJT
19-aug-00	V2.0 add mode= to allow binary files, added swap= 	PJT
28-aug-01	V2.1 process binary data, added offset= (replaces shortlives fix32=t|f)	PJT
.fi
