.TH TSF 1NEMO "19 February 2020"
.SH NAME
tsf \- type a structured file
.SH SYNOPSIS
\fBtsf in=\fPfile [parameter=value] .\|.\|.
.SH DESCRIPTION
\fItsf\fP types the contents of a structured binary file
(see \fIfilestruct\fP(3NEMO)) in a human readable form
on the standard output.
The type, tag, dimensions (if any) and contents of all items are listed.
The contents of \fICharType\fP items are printed directly; 
\fIFloatType\fP and \fIDoubleType\fP
items are printed in floating-point notation; all other types are printed in 
octal for portability reasons (see \fBoctal=\fP below).
\fIXML\fP format can optionally be selected as well, but this is not been well
exercised. A \fIjson\fP mode has been considered.
.PP

.SH PARAMETERS
The following parameters are recognized.
.TP 24
\fBin=\fP\fIfile\fP
Input data is read from \fIfile\fP, which must be a structured binary file.
No default.
.TP
\fBmaxprec=t|f\fP
If true, print float and double item data with maximum precision.
[Default: \fBf\fP].
.TP
\fBmaxline=\fP\fIlines\fP
Limits the number of lines of data typed for each item to \fIlines\fP.
See \fBallline=\fP below.
[Default: \fB4\fP].
.TP
\fBallline=t|f\fP
Print all lines, it overrides any value of \fBmaxline\fP.
If xml format selected, allline will always be set to t.
[Default: \fBf\fP].
.TP
\fBindent=\fP\fIset-indent\fP
Amount to indent contents of item-sets.
[Default: \fB2\fP].
.TP
\fBmargin=\fP\fIright-margin\fP
Righthand margin for output. Set this to a high value to prevent
possible string problems if file needs to be read by \fIrsf\fP.
[Default: \fB72\fP].
.TP
\fBitem=\fP\fIitem-name\fP
select only this item for output. Default: all items selected.
.TP
\fBxml=t|f\fP
Output in xml mode? 
If not, old-style human readable tsf mode is selected.
[Default: \fBf\fP].
.TP
\fBoctal=t|f\fP
Output of (short/long) integers in octal? Old versions used to
exchange integer information in octal, we have now switched
by default to decimal (more human readable). By using 
\fBoctal=t\fP you can force this program back in the old
mode. If take output of tsf to be read into rsf, you now
need to force octal=t.
[Default: \fBf\fP].
.SH SEE ALSO
ls(1v), file(1), rsf(1NEMO), csf(1NEMO), qsf(1NEMO), bsf(1NEMO), filestruct(3NEMO).
.SH DEBUG
\fBdebug=2\fP reports values of \fIMaxSetLen\fP
as defined in "\fBfilestruct.h\fP".
For \fIMaxTagLen\fP and \fIMaxVecDim\fP see \fIrsf(1NEMO)\fP.
.SH EXAMPLE
An example of converting all double precision numbers to single
precision in a NEMO file:
.nf
    % tsf in=double.dat out=float.dat convert=d2f

.fi
And here is an N-body snapshot of a Plummer sphere with 10 particles:
.nf

    mkplummer - 10 | tsf -

char Headline[35] "init_xrandom: seed used 1582131517"
char History[27] "mkplummer - 10 VERSION=3.0"
set SnapShot
  set Parameters
    int Nobj 10 
    double Time 0.00000 
  tes
  set Particles
    int CoordSystem 66306 
    double Mass[10] 0.100000 0.100000 0.100000 0.100000 0.100000 
      0.100000 0.100000 0.100000 0.100000 0.100000 
    double PhaseSpace[10][2][3] 0.394003 -1.98053 -0.836643 -0.466656 
      0.0439966 0.367178 -0.0762312 -0.0201540 0.0852010 0.238130 
      0.344608 0.379148 0.173722 0.311941 0.0433718 0.405117 0.747783 
      -0.555947 -0.778804 -0.580657 0.537069 -0.101942 0.0555890 
      . . .
  tes
tes

.fi
.SH BUGS
The algorithm for implementing \fBmaxline\fP is crude.
.PP
If \fBindent=\fP and \fBmargin=\fP are choosen too large, resp. too
small, they can bump into each other and cause illegable output, which
cannot be read by \fIrsf\fP either.
.SH AUTHOR
Joshua E. Barnes.
.SH HISTORY
.ta +1i +4i
.nf
xx-xxx-86	V1.0 original version	JEB
xx-apr-88	V2.0 new filestruct package	JEB
9-dec-90	V2.3 helpvec and other minor things	PJT
21-mar-01	V2.7 experimental xml output option	PJT
14-jun-02	V3.0 added octal=, but default output of integers is now decimal	PJT
.fi
