.TH U4TOS 1NEMO "7 April 1993"
.SH NAME
u4tos \- Convert NBODY unit-4 file to snapshot
.SH SYNOPSIS
\fBu4tos\fP [parameter=value]
.SH DESCRIPTION
No description available. This manual page was created from
the inline program help
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
Input file (in UNIT 4 format)  
.TP 20
\fBout=\fP
Output file (snapshot(5NEMO) format)    
.TP 20
\fBnbody=\fP
Input Number of particles    
.SH AUTHOR
Peter Teuben
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
07-Apr-93	V0.0 Created	PJT
.fi
