.TH uns_projects 1NEMO "March 17, 2020"

.SH DESCRIPTION
\fIuns_projects\fP is a set of programs based on unsio
technology. (see https://projets.lam.fr/projects/unsio/wiki)

.SH PROJECTS

.TP
\fBuns_info\fP gives information about an uns snapshot (see man uns_info)
.TP
\fBuns2uns\fP converts an uns snapshot to another uns format (see man
uns2uns)
.TP
\fBuns_tonemo\fP converts an uns snapshot to NEMO format (see man uns_tonemo)
.TP
\fBuns_2dplot\fP plots particles positions of an uns snapshot (see man
uns_2dplot)
.TP
\fBuns_density\fP computes local density on an uns snapshot (see man uns_density)
.TP
\fBuns_addgravity\fP adds acceleration and potential of an uns
snapshot (see man uns_addgravity)
.TP
\fBuns_stack\fP stacks two uns snapshot (see man uns_stack)
.TP
\fBuns_glindex2nemo\fP saves in NEMO format, particles pos,vel and
mass, selected from a  list of particles identifiers stored in a file,
and created with glnemo2 program
.TP
\fBuns_getradius\fP returns the radius where x% of the particles belong
.TP
\fBuns_mover\fP uns version of mover program
.TP
\fBuns_barangle\fP detects bar angle of an uns snapshot (experimental
but works fine)

.SH SEE ALSO
unsiof, snapshot(5NEMO)

https://projets.lam.fr/projects/unsio/wiki
 
.SH AUTHOR
Jean-Charles LAMBERT
.SH HISTORY
.nf
.ta +1i +4i
05-Dec-11	V1.0 created	JCL
17-Mar-20	V2.0 manual updated	JCL

.fi

