.TH VELFIT 1NEMO "10 April 2011"
.SH NAME
velfit \- fit rotation curve to coplanar disk (WWB73 method)
.SH SYNOPSIS
\fBvelfit\fP [parameter=value]
.SH DESCRIPTION
VELFIT fits a theoretical velocity pattern (\fBvmod\fP) to an
observed isovelocity image (\fBvobs\fP), optionally
weighted by an intensity image and a
geometric factor specified by model input parameters.
The default option is to fit a rotation curve
to an isovelocity
image of a rotating disk. The rotation curve and rms for the
fit are tabulated and can be used to find the best fit to the
other parameters. For more details see 
Warner, Wright and Baldwin (1973MNRAS.163..163W).  This may not be 
the best method to fit a rotation curve (see also \fIrotcur(1NEMO)\fP),
but it is very simple and elegant to program.
.PP
Optionally an output map can be generated with amusing quantities, 
as well an output table that contains, amongst, the rotation curve.
For additional map manipulations, see also \fIvelmap(1NEMO)\fP.
.SH PARAMETERS
The following parameters are recognized in any order if the keyword
is also given:
.TP 20
\fBin=\fP
input observed velocity field, in \fIimage(5NEMO)\fP format. We refer to
this as \fBvobs\fP. No default.
.TP
\fBradii=\fP
radii of the ring boundaries. For N rings, N+1 values need to be given.
They need to be sorted by increasing radius.   See \fInemoinp(1NEMO)\fP
for syntax, though \fIrmin:rmax:rstep\fP is a common shortcut.
No default.
.TP
\fBpa=\fP
position angle of disk, in degrees. [0]
.TP
\fBinc=\fP
inclination angle of disk, in degrees [45]   
.TP
\fBvsys=\fP
systemic velocity b[0]     
.TP
\fBcenter=\fP
rotation center. Default is the mapcenter ((Nx-1)/2,Ny-1)/2)
where 0,0=center of lower left pixel.
.TP
\fBden=\fP
input density image, used to weigh the velocities. If missing,
weights are uniform (but see \fBcoswt=\fP below). Default: none.
.TP
\fBfrang=\fP
free angle around minor axis (2*frang is the total angle around
the minor axis used), where data are ignored.
[Default: 0]
.TP
\fBblank=\fP
Value of the blank pixel to be ignored. Default: 0.0
.TP
\fBcoswt=\fP
power of cos(theta) weighting [1]   
.TP
\fBwwb73=\fP
use the classic WWB73 method? Currently there is no other 
method.  See \fIrotcur(1NEMO)\fP and \fIrotcurshape(1NEMO)\fP for
alternate discussions. [t]  
.TP
\fBmode=\fP
Output mode for the output image data file. Valid are:
\fBvtan\fP (=(vobs-vsys)/(cost*sini)),
\fBvmod\fP, 
\fBvres\fP (=vobs-vmod), 
\fBvtan/r\fP, 
\fBome\fP (=vtan/r), 
\fBvrad\fP (=vres/(sint*sini)), or
\fBdv/dr\fP (spline derivative of rotation curve)
.TP
\fBout=\fP
Optional output image. If selected, it will contain the 
nominal rotation speed as derived from the local radial
velocity in the disk, appropriately corrected for the
geometric factors.
Default: none.
.TP
\fBtab=\fP
Optional output table file. This will contain the 
radius, rotation speed, dispersion in the ring and some
other values. 
Default: none
.SH SEE ALSO
rotcur(1NEMO), runvelfitss07(1NEMO), rotcurshape(1NEMO), velmap(1NEMO)
.SH FILES
src/image/rotcur :  velfit.c
.SH EXAMPLES
The following example fits a velocity field for NGC 6503, produces a table and 
plots the rotation curve with error bars
.nf
% fitsccd N6503.xmom1.fits - | ccdmath - n6503.vel %1/1000.0
% velfit n6503.vel 0:1:0.002 -57 71.5 467,543 20 frang=0 tab=n6503.vtab
% tabplot n6503.vtab dycol=3 xmin=0 xmax=0.2
.fi
The N6503 example was taken from the 1996 VLA data, published  in 2009
by Greisen et al. (2009AJ....137.4718G) and generally available.
.SH AUTHOR
Mel Wright (Fortran version), Peter Teuben (C version)
.SH UPDATE HISTORY
.nf
.ta +1.0i +4.0i
30-sep-92	new task in MIRIAD	MCHW
5-oct-2003	V1.0 : C version in NEMO	PJT
22-oct-2005	V1.1 : added out=	PJT
4-feb-2011	V1.2 : added tab= and mode=	PJT
10-apr-2011	V1.4 : added mode=dv/dr 	PJT
.fi
