CC= cc
X11 = /usr/X11
OBJ = yapp_x.o X.o Xutil.o font.o event.o button.o
CFLAGS= -I/usr/include -I$(X11)/include
DESTINATION=.
#DESTINATION=$(NEMOLIB)

L = -lnemo
Y = $(DESTINATION)/libyapp_x.a -lX11

yapp: $(OBJ)
	ar ruv $(DESTINATION)/libyapp_x.a $(OBJ) 

yappx: $(OBJ) testyapp.c
	$(CC) -o yappx testyapp.c $(OBJ) $(L) $(Y) -lm 

clean: 
	rm *.o libyapp_x.a yappx
