
#

zeno:  zeno_jeb zeno_pjt
	@echo 'You will need to create a symlink zeno -> zeno_XYZ'
	@echo Pick from:
	@echo ln -s zeno_jeb zeno
	@echo ln -s zeno_pjt zeno

zeno_jeb:
	git clone https://github.com/joshuabarnes/zeno/ zeno_jeb

zeno_pjt:
	git clone https://github.com/teuben/zeno zeno_pjt
