#!/bin/bash
#
#  the benchmark :  0:01:04.75 on i7-8550U
   

#set -x
export DEBUG=-1

#                 parameters for the script that can be overriden via the commandline
run=run1        # basename of the files belonging to this simulation
nbody=10000     # number of bodies in the first ring
tstop=10        # stop time of the integration
kmax=8
step=0.05
eps=0.05
seq=0,500,9000
mode=1          # 1=gyrfalcoN 2=hackcode1
seed=0


#             simple keyword=value command line parser for bash
for arg in $*; do
  export $arg
done

#             delete this old run
rm -f $run.*


mkplummer $run.in $nbody seed=$seed scale=-1
if [ $mode = 1 ]; then
    gyrfalcON $run.in $run.out eps=$eps kmax=$kmax give=mxvpa step=$step tstop=$tstop > $run.log
    tabcomment $run.log - delete=t  | awk '{print $1,$2}' > $run.etot
elif [ $mode = 2 ]; then
    hackcode1 $run.in $run.out eps=$eps freq="2**$kmax" freqout=1/$step tstop=$tstop options=mass,phi,acc > $run.log
    snapdiagplot $run.out yapp=/null > $run.etot
else
    exit 0
fi

nstep=$(nemoinp $nbody/20)
nlast=$(nemoinp $nbody-1)
for i in $(seq 0 $nstep $nlast); do
    #snapcopy $run.out - | snapmask - - $i| snapprint - t,etot | tabstat - 2 qac=t >> $run.stats
    snapcopy $run.out - | snapmask - - $i| snapprint - t,etot > $run.$i.etot
    tabstat $run.$i.etot 2 qac=t >> $run.stats
done	    

if [ $mode = 1 ]; then
    de0=$(tabstat $run.etot 2 qac=t | txtpar - -%2/%1 p0=1,3 p1=1,4)    
else
    de0=$(txtpar $run.etot p0=Worst,1,9)
fi

de1=$(awk '{print -$4/$3}' $run.stats | tabstat - qac=t | txtpar - p0=1,3 p1=1,4)

echo $nbody $mode $kmax $eps $de0 $de1

