#! /usr/bin/env bash
#
#    view the "same" orbit in Plummer potential three different ways:
#    1. in a live nbody simulation
#    2. in a frozen nbody potential
#    3. in an analytical Plummer potential
#
#    We only pick 1 particle, the last one, of the Plummmer realization

run=run1
nbody=400
freq=50
tstop=50
eps=0.1
hack1=1
seed=0
plot=1
box=2

if [ -e "$1" ]; then
    echo Special recovery $1
    source $1
else
    for arg in $*; do
	export $arg
    done
fi

rm -f $run.*
mkplummer $run.in $nbody scale=-1 seed=$seed

if [ $hack1 = 1 ]; then
    hackcode1 $run.in $run.hc1                 freqout=$freq freq=$freq tstop=$tstop eps=$eps options=mass,phase,acc,phi > $run.log1
    snapmask $run.hc1 - $nbody-1  | snapplot - trak=t yapp=1/xs
fi	     
hackcode3 $run.in $run.out nrigid=$nbody-1 freqout=$freq freq=$freq tstop=$tstop eps=$eps options=mass,phase,acc,phi potname=zero > $run.log3
snapplot $run.out trak=t yapp=3/xs
#snapplot3 $run.out trak=t
snapprint $run.out etot | tabstat - qac=t
snapmask $run.in - $nbody-1 | snapprint - > $run.phase
x=$(txtpar $run.phase p0=1,1)
y=$(txtpar $run.phase p0=1,2)
z=$(txtpar $run.phase p0=1,3)
u=$(txtpar $run.phase p0=1,4)
v=$(txtpar $run.phase p0=1,5)
w=$(txtpar $run.phase p0=1,6)
mkorbit $run.iorb $x $y $z $u $v $w potname=plummer
orbint $run.iorb $run.orb nsteps=$tstop*$freq dt=1/$freq mode=leapfrog
orbplot $run.orb yapp=2/xs
cat $run.phase
tsf $run.in | head -2
snapmask $run.hc1 - $nbody-1  | snapprint - x,y,z > $run.tab1
orblist $run.orb | awk '{print $3,$4,$5}' > $run.tab2
snapprint $run.out x,y,z > $run.tab3
seed=$(tsf run1.in | head -1 | txtpar - %1 p0=1,6 format=%.0f)

echo '# pars'         > $run.rc
echo "nbody=$nbody"  >> $run.rc
echo "freq=$freq"    >> $run.rc
echo "tstop=$tstop"  >> $run.rc
echo "eps=$eps"      >> $run.rc
echo "hack1=$hack1"  >> $run.rc
echo "seed=$seed"    >> $run.rc
echo "box=$box"      >> $run.rc

$NEMO/scripts/csh/plummer_orbits.py $run
